### ISSUE TITLE
ctrl-a ctrl-e does not work and print 9;5u. 5;5u

### ISSUE THREAD

**Issue by jixiuf** [akermu/emacs-libvterm#106]
![image](https://user-images.githubusercontent.com/461743/62216018-937a0280-b3da-11e9-8544-0d652107e494.png)
ctrl-A Ctrl-e  does not work .

**Comment by akermu** [comment]
Yeah, I broke it in ecd362b5d. Fixed in eceae190. Whole key handling is a mess, e.g. completely broken in a terminal window.
