### ISSUE TITLE
Remote connections hang

### ISSUE THREAD

**Issue by Sbozzolo** [akermu/emacs-libvterm#109]
Recently, I've been experiencing occasional troubles in using remote machines. For instance, I would log in, and the shell would hang. If I kill the terminal buffer and re-open it several times, then, the shell would start to work fine. The problem doesn't occur with other terminals, so I must conclude that it is related to vterm.

Which information can I provide to help to debug this problem?

**Comment by akermu** [comment]
Are you talking about a shh session? Can you try to exit a hanged session as described [here](https://askubuntu.com/a/29952)?

**Comment by Sbozzolo** [comment]
Yes, ssh. I'll try what you suggested the next time I experience the problem.

**Comment by Sbozzolo** [comment]
The session is not killed with the combination indicated in the post.

**Comment by jixiuf** [comment]
https://github.com/akermu/emacs-libvterm/pull/108#issuecomment-517240435
try remove  your `vterm-set-title-hook` from `vterm-set-title-functions` and retry again 
maybe some bug in   `vterm-set-title-hook`  cause it hang.

**Comment by akermu** [comment]
I started an implementation of directory tracking here #110, so you might not have to use the `vterm-set-title-functions' workaround soon.

**Comment by Sbozzolo** [comment]
I'll checkout the PR and report back

**Comment by Sbozzolo** [comment]
How does #110 exactly work? Just updating my vterm installation didn't activate the directory tracking.

**Comment by akermu** [comment]
The PR doesn't work with tramp yet, so if it solves your issue, it is related to your `vterm-set-title-functions` hook.

**Comment by Sbozzolo** [comment]
The PR doesn't work in local either on my machine.
`zsh` complains with `command not found` if I add the following to my `.zshrc`:
```
function chpwd () {
    ￼	    echo -e "\e]51;$(pwd)\e\\"
    ￼	}
```
I am using `oh-my-zsh`.

**Comment by akermu** [comment]
> ```
> function chpwd () {
>     ￼	    echo -e "\e]51;$(pwd)\e\\"
>     ￼	}
> ```

There are some weird unicode characters in there, could they be the issue?

And could you try using a function hook, instead of overwriting the command like:
```zsh
autoload -U add-zsh-hook
add-zsh-hook -Uz chpwd (){ ls -a; }
```

**Comment by Sbozzolo** [comment]
It was the additional characters (which I don't see!) and I must have introduced when I copied the text from the browser. Now the error has gone, and directories are successfully tracked. I am looking forward to TRAMP support.

**Comment by akermu** [comment]
Is your vterm hang issue also gone?

**Comment by Sbozzolo** [comment]
It's difficult to say, I don't have a reliable way to trigger the bug. I'll
let you know.

**Comment by Sbozzolo** [comment]
The problem seems to have disappeared after removing the `set-title` workaround. If it happens again, I'll reopen the issue.
