### ISSUE TITLE
Terminal hangs. 

### ISSUE THREAD

**Issue by mbrumlow** [akermu/emacs-libvterm#114]
First off, this is amazing and thanks. 

You can reliable get a terminal to hang by opening two terminals, and in one run something like "find /" or top with update speed of 0. The second terminal will stop responding until you kill the command in the other or let it finish.

**Comment by mbrumlow** [comment]
Correction, top does not show this behavior. Running find / does though.

**Comment by akermu** [comment]
This also happens if the update speed is not nil for me. I think it has to do with how emacs handles process I/O. But I'll have to investigate further.

**Comment by akermu** [comment]
Okay it's happening because of our hook for `window-size-change-functions`.

**Comment by Sbozzolo** [comment]
#129 seems to solve this, and I cannot reproduce the bug on master. I am closing this issue. Feel free to re-open if the problem appears again.
