### ISSUE TITLE
make[2]: *** No rule to make target 'libvterm-prefix/src/libvterm/.libs/libvterm.a', needed by '../vterm-module.so'.

### ISSUE THREAD

**Issue by kingyakshaver** [akermu/emacs-libvterm#115]
```
[ 25%] No patch step for 'libvterm'
[ 33%] Performing update step for 'libvterm'
[ 41%] No configure step for 'libvterm'
[ 50%] Performing build step for 'libvterm'
TBL src/encoding/DECdrawing.tbl
TBL src/encoding/uk.tbl
CC src/encoding.c
CC src/keyboard.c
CC src/mouse.c
CC src/parser.c
CC src/pen.c
CC src/screen.c
CC src/state.c
CC src/unicode.c
src/unicode.c:306:12: warning: ‘mk_wcswidth_cjk’ defined but not used [-Wunused-function]
 static int mk_wcswidth_cjk(const uint32_t *pwcs, size_t n)
            ^~~~~~~~~~~~~~~
src/unicode.c:215:12: warning: ‘mk_wcswidth’ defined but not used [-Wunused-function]
 static int mk_wcswidth(const uint32_t *pwcs, size_t n)
            ^~~~~~~~~~~
CC src/vterm.c
LINK libvterm.la
CC bin/unterm.c
CC bin/vterm-ctrl.c
CC bin/vterm-dump.c
[ 58%] No install step for 'libvterm'
[ 66%] Completed 'libvterm'
[ 66%] Built target libvterm
Scanning dependencies of target vterm-module
[ 75%] Building C object CMakeFiles/vterm-module.dir/vterm-module.c.o
[ 83%] Building C object CMakeFiles/vterm-module.dir/utf8.c.o
[ 91%] Building C object CMakeFiles/vterm-module.dir/elisp.c.o
make[2]: *** No rule to make target 'libvterm-prefix/src/libvterm/.libs/libvterm.a', needed by '../vterm-module.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/vterm-module.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by akermu** [comment]
Could this be the same as in #78? In any case does this also happen with the latest master and a clean build folder?

**Comment by matthew-piziak** [comment]
My Emacs was built with modules support (I checked by noting that my `module-file-suffix` is `".so"`), and I can reproduce this failure as of 9951102.

**Comment by akermu** [comment]
On which operating system are you? And is there anything in `build/libvterm-prefix/src/.libs`?

**Comment by matthew-piziak** [comment]
Thanks @akermu I am using NixOS.

No, there is no `build/libvterm-prefix/.libs` directory, only `src` and `tmp`.

**Comment by matthew-piziak** [comment]
Here is the full tree of my build directory. As you can see there are files in `.lib` directories at a lower level. 
```
build
├── CMakeCache.txt
├── CMakeFiles
│   ├── 3.13.4
│   │   ├── CMakeCCompiler.cmake
│   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   ├── CMakeSystem.cmake
│   │   └── CompilerIdC
│   │       ├── a.out
│   │       ├── CMakeCCompilerId.c
│   │       └── tmp
│   ├── cmake.check_cache
│   ├── CMakeDirectoryInformation.cmake
│   ├── CMakeOutput.log
│   ├── CMakeRuleHashes.txt
│   ├── CMakeTmp
│   ├── feature_tests.bin
│   ├── feature_tests.c
│   ├── libvterm-complete
│   ├── libvterm.dir
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── DependInfo.cmake
│   │   ├── depend.internal
│   │   ├── depend.make
│   │   ├── Labels.json
│   │   ├── Labels.txt
│   │   └── progress.make
│   ├── Makefile2
│   ├── Makefile.cmake
│   ├── Progress
│   │   ├── 1
│   │   ├── 10
│   │   ├── 11
│   │   ├── 2
│   │   ├── 3
│   │   ├── 4
│   │   ├── 5
│   │   ├── 6
│   │   ├── 7
│   │   ├── 8
│   │   ├── 9
│   │   └── count.txt
│   ├── progress.marks
│   ├── run.dir
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── DependInfo.cmake
│   │   └── progress.make
│   ├── TargetDirectories.txt
│   └── vterm-module.dir
│       ├── build.make
│       ├── C.includecache
│       ├── cmake_clean.cmake
│       ├── DependInfo.cmake
│       ├── depend.internal
│       ├── depend.make
│       ├── elisp.c.o
│       ├── flags.make
│       ├── link.txt
│       ├── progress.make
│       ├── utf8.c.o
│       └── vterm-module.c.o
├── cmake_install.cmake
├── libvterm-prefix
│   ├── src
│   │   ├── libvterm
│   │   │   ├── bin
│   │   │   │   ├── .libs
│   │   │   │   │   ├── unterm
│   │   │   │   │   ├── vterm-ctrl
│   │   │   │   │   └── vterm-dump
│   │   │   │   ├── unterm
│   │   │   │   ├── unterm.c
│   │   │   │   ├── vterm-ctrl
│   │   │   │   ├── vterm-ctrl.c
│   │   │   │   ├── vterm-dump
│   │   │   │   └── vterm-dump.c
│   │   │   ├── .bzrignore
│   │   │   ├── doc
│   │   │   │   ├── seqs.txt
│   │   │   │   └── URLs
│   │   │   ├── find-wide-chars.pl
│   │   │   ├── .git
│   │   │   │   ├── branches
│   │   │   │   ├── config
│   │   │   │   ├── description
│   │   │   │   ├── HEAD
│   │   │   │   ├── hooks
│   │   │   │   │   ├── applypatch-msg.sample
│   │   │   │   │   ├── commit-msg.sample
│   │   │   │   │   ├── fsmonitor-watchman.sample
│   │   │   │   │   ├── post-update.sample
│   │   │   │   │   ├── pre-applypatch.sample
│   │   │   │   │   ├── pre-commit.sample
│   │   │   │   │   ├── prepare-commit-msg.sample
│   │   │   │   │   ├── pre-push.sample
│   │   │   │   │   ├── pre-rebase.sample
│   │   │   │   │   ├── pre-receive.sample
│   │   │   │   │   └── update.sample
│   │   │   │   ├── index
│   │   │   │   ├── info
│   │   │   │   │   └── exclude
│   │   │   │   ├── logs
│   │   │   │   │   ├── HEAD
│   │   │   │   │   └── refs
│   │   │   │   │       ├── heads
│   │   │   │   │       │   └── master
│   │   │   │   │       └── remotes
│   │   │   │   │           └── origin
│   │   │   │   │               └── HEAD
│   │   │   │   ├── objects
│   │   │   │   │   ├── info
│   │   │   │   │   └── pack
│   │   │   │   │       ├── pack-76ac964215c5b480b065722d81a74edf9a67d555.idx
│   │   │   │   │       └── pack-76ac964215c5b480b065722d81a74edf9a67d555.pack
│   │   │   │   ├── packed-refs
│   │   │   │   └── refs
│   │   │   │       ├── heads
│   │   │   │       │   └── master
│   │   │   │       ├── remotes
│   │   │   │       │   └── origin
│   │   │   │       │       └── HEAD
│   │   │   │       └── tags
│   │   │   ├── include
│   │   │   │   ├── vterm.h
│   │   │   │   └── vterm_keycodes.h
│   │   │   ├── .libs
│   │   │   │   ├── libvterm.la -> ../libvterm.la
│   │   │   │   ├── libvterm.lai
│   │   │   │   ├── libvterm.so -> libvterm.so.0.0.0
│   │   │   │   ├── libvterm.so.0 -> libvterm.so.0.0.0
│   │   │   │   └── libvterm.so.0.0.0
│   │   │   ├── libvterm.la
│   │   │   ├── LICENSE
│   │   │   ├── Makefile
│   │   │   ├── src
│   │   │   │   ├── encoding
│   │   │   │   │   ├── DECdrawing.inc
│   │   │   │   │   ├── DECdrawing.tbl
│   │   │   │   │   ├── uk.inc
│   │   │   │   │   └── uk.tbl
│   │   │   │   ├── encoding.c
│   │   │   │   ├── encoding.lo
│   │   │   │   ├── fullwidth.inc
│   │   │   │   ├── keyboard.c
│   │   │   │   ├── keyboard.lo
│   │   │   │   ├── .libs
│   │   │   │   │   ├── encoding.o
│   │   │   │   │   ├── keyboard.o
│   │   │   │   │   ├── mouse.o
│   │   │   │   │   ├── parser.o
│   │   │   │   │   ├── pen.o
│   │   │   │   │   ├── screen.o
│   │   │   │   │   ├── state.o
│   │   │   │   │   ├── unicode.o
│   │   │   │   │   └── vterm.o
│   │   │   │   ├── mouse.c
│   │   │   │   ├── mouse.lo
│   │   │   │   ├── parser.c
│   │   │   │   ├── parser.lo
│   │   │   │   ├── pen.c
│   │   │   │   ├── pen.lo
│   │   │   │   ├── rect.h
│   │   │   │   ├── screen.c
│   │   │   │   ├── screen.lo
│   │   │   │   ├── state.c
│   │   │   │   ├── state.lo
│   │   │   │   ├── unicode.c
│   │   │   │   ├── unicode.lo
│   │   │   │   ├── utf8.h
│   │   │   │   ├── vterm.c
│   │   │   │   ├── vterm_internal.h
│   │   │   │   └── vterm.lo
│   │   │   ├── t
│   │   │   │   ├── 02parser.test
│   │   │   │   ├── 03encoding_utf8.test
│   │   │   │   ├── 10state_putglyph.test
│   │   │   │   ├── 11state_movecursor.test
│   │   │   │   ├── 12state_scroll.test
│   │   │   │   ├── 13state_edit.test
│   │   │   │   ├── 14state_encoding.test
│   │   │   │   ├── 15state_mode.test
│   │   │   │   ├── 16state_resize.test
│   │   │   │   ├── 17state_mouse.test
│   │   │   │   ├── 18state_termprops.test
│   │   │   │   ├── 20state_wrapping.test
│   │   │   │   ├── 21state_tabstops.test
│   │   │   │   ├── 22state_save.test
│   │   │   │   ├── 25state_input.test
│   │   │   │   ├── 26state_query.test
│   │   │   │   ├── 27state_reset.test
│   │   │   │   ├── 28state_dbl_wh.test
│   │   │   │   ├── 29state_fallback.test
│   │   │   │   ├── 30state_pen.test
│   │   │   │   ├── 31state_rep.test
│   │   │   │   ├── 60screen_ascii.test
│   │   │   │   ├── 61screen_unicode.test
│   │   │   │   ├── 62screen_damage.test
│   │   │   │   ├── 63screen_resize.test
│   │   │   │   ├── 64screen_pen.test
│   │   │   │   ├── 65screen_protect.test
│   │   │   │   ├── 66screen_extent.test
│   │   │   │   ├── 67screen_dbl_wh.test
│   │   │   │   ├── 68screen_termprops.test
│   │   │   │   ├── 90vttest_01-movement-1.test
│   │   │   │   ├── 90vttest_01-movement-2.test
│   │   │   │   ├── 90vttest_01-movement-3.test
│   │   │   │   ├── 90vttest_01-movement-4.test
│   │   │   │   ├── 90vttest_02-screen-1.test
│   │   │   │   ├── 90vttest_02-screen-2.test
│   │   │   │   ├── 90vttest_02-screen-3.test
│   │   │   │   ├── 90vttest_02-screen-4.test
│   │   │   │   ├── 92lp1640917.test
│   │   │   │   ├── harness.c
│   │   │   │   └── run-test.pl
│   │   │   ├── tbl2inc_c.pl
│   │   │   └── vterm.pc.in
│   │   └── libvterm-stamp
│   │       ├── libvterm-build
│   │       ├── libvterm-configure
│   │       ├── libvterm-done
│   │       ├── libvterm-download
│   │       ├── libvterm-gitclone-lastrun.txt
│   │       ├── libvterm-gitinfo.txt
│   │       ├── libvterm-install
│   │       ├── libvterm-mkdir
│   │       └── libvterm-patch
│   └── tmp
│       ├── libvterm-cfgcmd.txt
│       ├── libvterm-cfgcmd.txt.in
│       ├── libvterm-gitclone.cmake
│       └── libvterm-gitupdate.cmake
└── Makefile
```

**Comment by jasonmj** [comment]
I have this same issue on NixOS.

**Comment by adisbladis** [comment]
I'm the maintainer of this package in nixpkgs. 

@jasonmj Are you using the Nix package or are you trying to build outside of Nix?

I looked into @matthew-piziak`s problem over on the nixpkgs issue tracker https://github.com/NixOS/nixpkgs/issues/66295 and could not reproduce the issue which I think has something to do with the strange combination of stable/unstable channels.

**Comment by matthew-piziak** [comment]
@adisbladis Unfortunately I get this particular error even when I am building it manually, independent of my strange Emacs installation.

**Comment by jasonmj** [comment]
For what it's worth, I have installed both emacs and libvterm packages from the stable channels for NixOS 19.03. I made sure to install cmake, gcc, and libtool before trying to run M-x vterm from inside emacs.

**Comment by akermu** [comment]
I played a little around with NixOS and it seems the default gcc installed with `nix-env -iA nixos.gcc` has no `ar` command installed, which is necessary to create a static library. I hadn't had the time to investigate further.

**Comment by adisbladis** [comment]
@jasonmj: The Nix vterm package already compiles a binary. You don't need any build tools at runtime.

@akermu `ar` is part of the binutils package. Also installing build tools with `nix-env` is not the recommended approach.
Use `nix-shell` to create a build environment.

**Comment by matthew-piziak** [comment]
I tried again today after installing only `unstable.libvterm` and the following:
```
(use-package vterm
  :straight (vterm :type git :host github :repo "akermu/emacs-libvterm"))
```

I was able to run `(require 'vterm)` this time but running `vterm` failed like this:
```
Debugger entered--Lisp error: (void-function vterm--face-color-hex)
  vterm--new(52 118 1000)
  vterm-mode()
  vterm()
  funcall-interactively(vterm)
  call-interactively(vterm record nil)
  command-execute(vterm record)
  #f(compiled-function (cmd) #<bytecode 0x1325db5>)("vterm")
```

**Comment by adisbladis** [comment]
`unstable.libvterm` is not the package you are looking for, it's `unstable.libvterm-neovim`.

**Comment by matthew-piziak** [comment]
@adisbladis Okay, I did that and I still got `(void function vterm--face-color-hex)`.

**Comment by akermu** [comment]
@matthew-piziak I think the module and your .el or .elc files are out of sync. Please recompile `vterm.el` and try again.

**Comment by adisbladis** [comment]
@akermu I think it would be worth adding a note to the README stating that this is depending on https://github.com/neovim/libvterm and not http://www.leonerd.org.uk/code/libvterm/ (which is a far older lib of the same name).

**Comment by adisbladis** [comment]
Also, to any NixOS users finding this thread: We have this project packaged as `emacsPackagesNg.vterm` or `emacsPackagesNg.emacs-libvterm` (on recent unstable the latter is an alias for the former).
Please use the package.

**Comment by matthew-piziak** [comment]
Yeah, `emacsPackagesNg.vterm` crashes on my NixOS. I'm waiting for 19.09 to come out.

**Comment by matthew-piziak** [comment]
@akermu I delete my `vterm` source files, then I restart Emacs and execute this code cleanly:
```
(use-package vterm
  :straight (vterm :type git :host github :repo "akermu/emacs-libvterm"))
(require 'vterm)
(vterm)
```
This results in `vterm-mode: Symbol’s function definition is void: vterm--face-color-hex`.

**Comment by akermu** [comment]
@matthew-piziak  This function was removed here 46f222eee, which tells me your `vterm.el` or your `vterm-module.so` is outdated. They definitely don't fit together.

**Comment by matthew-piziak** [comment]
Point taken! I also could not find the function in my repository, nor its call site. It must be my `vterm-module.so` that's outdated.

**Comment by alexanderbarbosa** [comment]
@matthew-piziak 

git clone, m-x package-install ....

**Comment by matthew-piziak** [comment]
@alexanderbarbosa I meant declaratively through a `.nix` configuration file in the standard methodology of NixOS installations.

**Comment by matthew-piziak** [comment]
The package in my `/nix/store` is at `/nix/store/rcims40yq3kydccch39ywq8sp06nb4ad-libvterm-neovim-2018-11-26`. I tried checking out and rebuilding `emacs-libvterm` at `d4e326a`, the corresponding date, but I still get the same void definition mismatch.

**Comment by intractable** [comment]
I was having this exact issue on NixOS 19.03 (pinned nixpkgs `9ef3cb9b`) until I read the comment from @adisbladis above that pointed out the `vterm` package was available via `emacsWithPackages`, which pretty much fixed everything. Thanks!

Note that I did see the `(void function vterm--face-color-hex)` error mentioned above until I deleted the previously-installed MELPA package altogether.

@matthew-piziak You've probably already been down this road, but you might try first removing the `vterm` package you've been trying to get to work, and then seeing if you have any luck with the `emacs` you get in the `nix-shell --packages 'emacsWithPackages [emacsPackagesNg.emacs-libvterm]'` environment. I was able to `(require 'vterm)` and `M-x vterm` successfully using _that_ `emacs`, and then I put it into my `configuration.nix` and switched.

**Comment by matthew-piziak** [comment]
Thank you so much @intractable! I tried out your `nix-shell` and was surprised to find that `vterm` worked perfectly. I realized that I must have been adding packages incorrectly somehow.

I ended up rewriting my config to say:
```
  pdf-tools-rev = "9a63f3909e5a331b6974deb03abd2c4bad42c2d9";
  pdf-tools-src = pkgs.fetchFromGitHub {
    owner = "politza";
    repo = "pdf-tools";
    rev = pdf-tools-rev;
    sha256 = "11i4kbwclwyvznyd9q69fq36fjasvs72ziz0555hl3fjbbq0n71q";
  };
  custom-emacs = pkgs.unstable.emacsWithPackages (with pkgs.unstable.emacsPackagesNg; [
    emacs-libvterm
    proof-general
    (pdf-tools.overrideAttrs (attrs: { src = pdf-tools-src; }))
  ]);
```

This works! I believe that might be because `vterm` was not properly being installed previously.

Unfortunately this means that I lost my other customizations, to whit,
```
  emacs-custom = (pkgs.stable1903.emacs.override {
    imagemagick = pkgs.unstable.imagemagickBig;
    srcRepo = true;
    withXwidgets = true;
  }).overrideAttrs (old: rec {
    name = "emacs-${version}${versionModifier}";
    version = "27.0.50";
    versionModifier = "-git";
    src = pkgs.fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "0a5212b99666b9ba0543a62cdbb12ee0685820f3";
      sha256 = "038kasdll0332vdpyc29xlkdj801sivz3ssnyz0dqr3gcavpk5yv";
    };
    patches = [ ];
  });
```

If anyone knows how I can use `emacsWithPackages` on NixOS with a custom compilation of Emacs, let me know. I tried a half-dozen override strategies but never managed to get everything to stick.

**Comment by adisbladis** [comment]
@matthew-piziak 
```
with import <nixpkgs> {};

let
  # Decide which emacs package we want to use
  package = emacs26;
  # Get the emacs packages attribute sets
  emacsPackages = emacsPackagesNgGen package;
  # Assign the function that we will use to create our env
  emacsWithPackages = emacsPackages.emacsWithPackages;
# Finally, create the environment
in emacsWithPackages (epkgs: [ epkgs.magit ])
```

**Comment by matthew-piziak** [comment]
@adisbladis Outstanding!

Thank you very much to everyone who was patient with my issues here.

I have also narrowed down the `vterm` crash to Emacsen compiled with `imagemagickBig`: https://github.com/NixOS/nixpkgs/issues/66295.

**Comment by akermu** [comment]
@kingyakshaver  @matthew-piziak Can this be closed? And the nix related follow up discussed at https://github.com/NixOS/nixpkgs/issues/66295?

**Comment by matthew-piziak** [comment]
@akermu Resolved from my perspective, thank you! I don't know what environment @kingyakshaver is running and if his build issue is still relevant.

**Comment by chriselrod** [comment]
I'm on Clear Linux. Trying to build libvterm:
```sh
build> make clean
build> make
[  8%] Creating directories for 'libvterm'
[ 16%] Performing download step (git clone) for 'libvterm'
-- Avoiding repeated git clone, stamp file is up to date: '/home/chriselrod/.emacs.d/elpa/vterm-20210209.356/build/libvterm-prefix/src/libvterm-stamp/libvterm-gitclone-lastrun.txt'
[ 25%] Performing update step for 'libvterm'
[ 33%] No patch step for 'libvterm'
[ 41%] No configure step for 'libvterm'
[ 50%] Performing build step for 'libvterm'
[ 58%] No install step for 'libvterm'
[ 66%] Completed 'libvterm'
[ 66%] Built target libvterm
[ 75%] Building C object CMakeFiles/vterm-module.dir/vterm-module.c.o
[ 83%] Building C object CMakeFiles/vterm-module.dir/utf8.c.o
[ 91%] Building C object CMakeFiles/vterm-module.dir/elisp.c.o
make[2]: *** No rule to make target 'libvterm-prefix/src/libvterm/.libs/libvterm.a', needed by '../vterm-module.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:152: CMakeFiles/vterm-module.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
build [2]> ls libvterm-prefix/src/libvterm/.libs/
libvterm.la@  libvterm.lai  libvterm.so@  libvterm.so.0@  libvterm.so.0.0.0*
```

It wants a static `.a` library, but builds a shared `.so` library.

**Comment by blablablerg** [comment]
I have this strange behaviour on NixOS 21.05 with the emacs-libvterm package installed: when I start emacs, vterm works, but when I do a emacs-restart, it wants to compile vterm-module, which of course fails.

I am using spacemacs.

**Comment by michzappa** [comment]
> Editing the cmake file to say "vterm.so" and replacing the "STATIC" with "SHARED" let it build successfully.
Worked for me on nixos 21.05 too, now to figure out how to make that change consistent.

**Comment by ndland** [comment]
> Editing the cmake file to say "vterm.so" and replacing the "STATIC" with "SHARED" let it build successfully.

To be clear, which file? Looking through the code, it's not entirely clear which changes need to be made. I'm on Debian, and running into same issue.

**Comment by winny-** [comment]
Anyone able to get emacs vterm compiled on nixos 22.05?

**Comment by michzappa** [comment]
For a long time now I've been using the `emacsWithPackages` approach on nix to add the vterm package, so it uses the actual nixpkgs libvterm. I haven't actually switched to 22.05 yet but I have built my system without any issues.

**Comment by a-sebi** [comment]
> Anyone able to get emacs vterm compiled on nixos 22.05?

Currently on NixOS 23.05 and ran into this issue but successfully compiled it by editing the `cmake` file. Not sure what caused it but it may have coincided with deleting my `.emacs.d/.local/straight` directory to fix a separate issue.

For reference to anyone else having this issue, the `cmake` file is `CMakeLists.txt` in the Emacs build directory for `vterm`. 

Parts to change were:
- `libvterm.a` changed to `libvterm.so`
- `vterm STATIC IMPORTED` changed to `vterm SHARED IMPORTED`

I'm not sure why this occurs but seems to be related to NixOS. Obviously this only applies if you have `libvterm.so` available. You can run `ls /nix/store | grep libvterm` to look for it.

Oddly enough, other solutions to install `vterm` as a separate package with Emacs didn't work for me.
