### ISSUE TITLE
How to custom vterm theme

### ISSUE THREAD

**Issue by vHtQ18W** [akermu/emacs-libvterm#116]
_EMACS VERSION_: 26.2
I read the README, set following configuration, but it not active.
```emacs-lisp
(defconst dracula-background "#282a36")
(defconst dracula-curren-line "#44475a")
(defconst dracula-selection "#44475a")
(defconst dracula-foreground "#f8f8f2")
(defconst dracula-comment "#6272a4")
(defconst dracula-white "#bfbfbf")
(defconst dracula-black "#000000")
(defconst dracula-cyan "#8be9fd")
(defconst dracula-blue "#caa9fa")
(defconst dracula-green "#50fa7b")
(defconst dracula-orange "#ffb86c")
(defconst dracula-pink "#ff79c6")
(defconst dracula-purple "#bd93f9")
(defconst dracula-red "#ff5555")
(defconst dracula-yellow "#f1fa8c")
(defconst dracula-magenta "#ff79c6")

(setq vterm-default-fg 'dracula-foreground
      vterm-default-bg 'dracula-background
      vterm-black-fg 'dracula-black
      vterm-red-fg 'dracula-red
      vterm-green-fg 'dracula-green
      vterm-yellow-fg 'dracula-yellow
      vterm-blue-fg 'dracula-blue
      vterm-magenta-fg 'dracula-magenta
      vterm-cyan-fg 'dracula-cyan
      vterm-white-fg 'dracula-white)
```
And then, I notice #58 maybe help me, I copy [this](https://github.com/akermu/emacs-libvterm/issues/58#issuecomment-459010374) config, but it also not active.

What should I do?

**Comment by jixiuf** [comment]
https://github.com/purcell/color-theme-sanityinc-solarized/pull/27
I am trying to custom term theme for /color-theme-sanityinc-solarized
hope this is helpful

**Comment by vHtQ18W** [comment]
I use dracula-theme, it's color definitions like as [it](https://github.com/dracula/emacs/blob/66e429f4d576346661ae3a111bafaa06febc1d94/dracula-theme.el#L20). It different with color-theme-sanityinc-solarized. I try add some code:
```emacs-lisp
(term-color-black :foreground ,bg3 :background ,bg3)
(...)
```
It not activate.
So `ansi-color-names-vector' is necessary?

**Comment by vHtQ18W** [comment]
I use dracula-theme, it's color definitions like as [it](https://github.com/dracula/emacs/blob/66e429f4d576346661ae3a111bafaa06febc1d94/dracula-theme.el#L20). It different with color-theme-sanityinc-solarized. I try add some code:
```emacs-lisp
(vterm-color-black :foreground ,bg3 :background ,bg3)
(...)
```
It not activate.
So `ansi-color-names-vector' is necessary?

**Comment by jixiuf** [comment]
`ansi-color-names-vector` is not necessary ,
may be you need restart your emacs after you custom the theme

**Comment by vuquangtam** [comment]
For those using theme [bbatsov/solarized-emacs](https://github.com/bbatsov/solarized-emacs)
```
(solarized-with-color-variables 'dark
          (custom-set-faces
           `(vterm-color-default ((t (:foreground nil :background nil :inherit default))))
           `(vterm-color-black   ((t (:foreground ,base02 :background ,base03))))
           `(vterm-color-blue    ((t (:foreground ,blue :background ,base0))))
           `(vterm-color-cyan    ((t (:foreground ,cyan :background ,base1))))
           `(vterm-color-green   ((t (:foreground ,green :background ,base01))))
           `(vterm-color-magenta ((t (:foreground ,magenta :background ,violet))))
           `(vterm-color-red     ((t (:foreground ,red :background ,orange))))
           `(vterm-color-white   ((t (:foreground ,base2 :background ,base3))))
           `(vterm-color-yellow  ((t (:foreground ,yellow :background ,base00))))
           )
          )
```

**Comment by vHtQ18W** [comment]
Thx. Now I use [doom-dracula](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el), I copy it's color definition, this work fine.

color define in [this line](https://github.com/hlissner/emacs-doom-themes/blob/ae18b84e01496c4ebd572cad00a89516af089a94/themes/doom-dracula-theme.el#L38).
vterm face define in [this line](https://github.com/hlissner/emacs-doom-themes/blob/ae18b84e01496c4ebd572cad00a89516af089a94/doom-themes-base.el#L234).
