### ISSUE TITLE
Cursor position does not update properly.

### ISSUE THREAD

**Issue by mbrumlow** [akermu/emacs-libvterm#121]
If the terminal updates and the term is not visible -- at least on EXWM -- the cursor will not be in the correct place when returning to the window/buffer. 

Running 

``` sleep 3 && echo "test"```

And moving to a different virtual desktop for more than 3 seconds and coming back to view the terminal show the cursor at the start of the next line vs being a the end of the last line (after the new prompt)

**Comment by xendk** [comment]
Seems to me that it's whether the buffers frame is active, not visibility.

`tail -f` in one frame stops scrolling the buffer if moving to another frame, but not if moving to another window in the same frame.

Experimenting a bit with command with output, it seems it just doesn't stop scrolling, but scrolls about a page back.

My C-fu is very weak, but it seems to me that, here: https://github.com/akermu/emacs-libvterm/blob/cc670d74851db9ec975aef7c3ada61236bfc174f/vterm-module.c#L304-L319 it will use the recenter function to follow the output, if the current window is the terminal window, or just move point if the current-window is not nil. But this https://github.com/akermu/emacs-libvterm/blob/cc670d74851db9ec975aef7c3ada61236bfc174f/vterm-module.c#L317 looks like it's actually setting the point to the current value of point. But I could be entirely barking up the wrong tree here.

**Comment by jixiuf** [comment]
could you try #127 @mbrumlow @xendk

**Comment by xendk** [comment]
@jixiuf 
Certainly seems to fix it for me (I don't run EXVM). Running a command in one frame that produces a lot of output and switching to another frame keeps the shell tracking the output.

There's an edge case if having the same process visible in two frames, only the last active scrolls. But I'd call that a minor issue not worth worrying about.

**Comment by jixiuf** [comment]
@xendk  should be fixed .

**Comment by xendk** [comment]
@jixiuf Indeed it is.

Not to sound ungrateful, but I just remembered another case. Sometimes you have a load of output from some command and you spot something, and scroll back to inspect it. Most sane terminals will stay at the point scrolled back to while appending new output below (at least for as long as their scrollback buffer will hold). With the latest fixes vterm will jump to the end on new output.

Could that easily be fixed? I would think it's a bit tricky as it introduces a state where the vterm cusor and emacs point isn't at the same place (I believe that emacs always keeps the point in the visible part of the buffer), but I'm obviously a bit clueless in this case.

**Comment by jixiuf** [comment]
I known this case,  it's not easy to fix it now. I will try ,but ...
in current situation I suggest you enable `vterm-copy-mode` then scroll back,
it won't  jump to the end on new output when `vterm-copy-mode` is enabled

**Comment by xendk** [comment]
@jixiuf Oh, right. I'll need to be in `vterm-copy-mode` anyway to scroll back using the keyboard, wont I?

I could rebind the mousewheel in `vterm-mode` to switch to `vterm-copy-mode`, to support my habit of just mousewhelling back.

`vterm-copy-mode` does seem to block the process, but that doesn't have anything to do with this issue. Thanks for your effort. :smiley:
