### ISSUE TITLE
Insert command on hook

### ISSUE THREAD

**Issue by krahser** [akermu/emacs-libvterm#128]
Hi!
nice package.
I'm trying to migrate to vterm from ansi-term, and I'm using some hooks to insert a command after the shell has loaded.
```
(defun my-command-hook ()
  "exec my command"
  (insert "echo thanks for this package")
  (term-send-input)
  )
(add-hook 'term-exec-hook 'my-command-hook)
```
I've been trying to do the same with vterm. 
```
(add-hook 'vterm-exec-hook 'my-command-hook)
(add-hook 'vterm-mode-hook 'my-command-hook)
```
I understood  with the documentation that the function should be attach to `vterm-mode-hook`, but since it doesn't work I've tried with both. Any ideas about what I'm doing wrong?

Thanks in advance.

**Comment by jixiuf** [comment]
```
(defun my-command-hook ()
  "exec my command"
  (vterm-send-string "echo hello")
  (vterm-send-return)
  )
(add-hook 'vterm-mode-hook 'my-command-hook)

```
