### ISSUE TITLE
CMake 3.11 or higher is required.  You are running version 3.8.0

### ISSUE THREAD

**Issue by 717g301github** [akermu/emacs-libvterm#133]
> [~/Programming/git/emacs-libvterm/build]
> admin-> cmake ..
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>   CMake 3.11 or higher is required.  You are running version 3.8.0
> 
> 
> -- Configuring incomplete, errors occurred!
> 

You could make it usable for 3.8.0 isn't it? It is hard to install too many other dependencies.

**Comment by akermu** [comment]
I currently need it for this feature: https://gitlab.kitware.com/cmake/cmake/issues/15689, but I definitly could work around it. Just out of interest, which OS are you on? Debian stable and ubuntu bionic all package a more recent version.

**Comment by 717g301github** [comment]
https://www.hyperbola.info/ -- long term support is not moving much forward with new versions. But I have now uninstalled bunch of it, and doing `make` on `cmake`, I hope to make it happen. `ansi-term` is not as nice, I have no idea how libveterm looks like, I hope I get better terminal option within GNU Emacs.

And I hope I will be able to launch any command. As function `shell`  does not really allow me to launch complex commands. Neither `ansi-term`.

**Comment by 717g301github** [comment]
No need to change, if it is only me complaining. I am installing new `cmake` now. I am using GNU Stow to keep packages separate from distribution, so no problem.

**Comment by akermu** [comment]
Okay, I'll leave it for now. If more persons are complaining, I'll reduce the minimum required version.

**Comment by PuercoPop** [comment]
I'm on Ubuntu 18.04 (LTS) and the cmake version provided is 3.10.2 so this issue also affects me.

**Comment by phil-s** [comment]
I think not supporting even the very latest LTS release of perhaps the most popular GNU/Linux distribution does constitute a problem.

Even if the next LTS (this coming April) will work by default, many users will keep their LTS release for 4-5 years. Postponing the need for OS upgrades as long as possible is a large part of the attraction of the LTS releases in the first place, after all.

If you could find the time to make this work with cmake 3.10, that would be fantastic.
