### ISSUE TITLE
C-g not working

### ISSUE THREAD

**Issue by 717g301github** [akermu/emacs-libvterm#135]
I cannot interrupt with C-g in same manner how I can within `ansi-term`. If `C-g` is not sent to terminal, then is not usable. I have so many uses for it in `mutt`

**Comment by akermu** [comment]
Please remove `C-g` from `vterm-keyboard-exceptions` before loading vterm.el. Or bind `C-g` to `vterm--self-insert`:
```elisp
(define-key vterm-mode-map (kbd "C-g") #'vterm--self-insert)
```
