### ISSUE TITLE
TERM definition with eterm-color

### ISSUE THREAD

**Issue by krahser** [akermu/emacs-libvterm#136]
Hi!

is there any restriction to use `TERM=eterm-color`?

https://github.com/akermu/emacs-libvterm/blob/fad40c1436afcf73fe39ea2ec535628866c72b23/vterm.el#L227

Thanks.

**Comment by akermu** [comment]
Hello! I don't understand your question. Do you want the `TERM` environment value to be configurable? I have choosen the value above, because libvterm is mostly compatible with xterm and most shells will behave accordingly.

**Comment by krahser** [comment]
Sorry for not being clear, being configurable could be an option.
I was thinking to being default as `eterm-color` because it was rendering better in my experience.

For example, using tmux with `xterm-256color`
![xterm-256color](https://user-images.githubusercontent.com/232739/62977062-11a0c500-be2f-11e9-8f02-29c5d4ef2f33.png)

`eterm-color`:
![eterm-color](https://user-images.githubusercontent.com/232739/62977320-b4f1da00-be2f-11e9-9097-5a97dcfc640c.png)

I haven't been found cases where the render using `eterm-color` is ugly, but it might.
I don't know if it's worth it of try it. Do you think it's better to make it customizable? I can help with that.

Thanks in advance.

**Comment by akermu** [comment]
I'm happy to accept a PR to make this customizable :)
