### ISSUE TITLE
Remote directory tracking without `cd`

### ISSUE THREAD

**Issue by Sbozzolo** [akermu/emacs-libvterm#137]
At the moment, at least for `zsh`, the suggested way to let `vterm` know which directory we are visiting is with the `chpwd` hook. As a result, when logging in into a remote machine, the directory-tracking doesn't work immediately, but it starts working only after the first `cd`. Clearly, this is a minor problem, but it is still an annoyance. 

Is there any reason why the current solution is preferable to the following, in which the problem doesn't appear?
``` sh
HOSTNAME="$(hostname)" # or whatever is needed to connect to the machine
USER="$(whoami)"
sync_dir() {
    print -Pn "\e]51;A${USER}@${HOSTNAME}:$(pwd)\e\\"
}
precmd_functions=($precmd_functions sync_dir)
```

As a side remark, the current suggestion assumes that hostname provides the correct way to connect to the machine. However, this is not necessarily the case. The lines above, while more verbose, are clearer in this respect.

**Comment by akermu** [comment]
Hi I'm happy to accept an PR for this. The other solution is to put it in the prompt as suggested here: https://github.com/akermu/emacs-libvterm/pull/126

**Comment by jixiuf** [comment]
this should be fixed
