### ISSUE TITLE
Completion of partially input commands

### ISSUE THREAD

**Issue by Sbozzolo** [akermu/emacs-libvterm#138]
In `ansi-term`, if I type something like `ls /hom`, `zsh` provides a suggestion for completing the command, I can press `M-p` or the up arrow for the command to be completed. In `vterm` only the up arrow does the job and not `M-p`..

**Comment by akermu** [comment]
For me both work, can you provide me with a minimal `init.el` and `.zshrc` to reproduce it with `emacs -Q`?

**Comment by Sbozzolo** [comment]
The following are the steps to reproduce the difference in behavior between `ansi-term` and `vterm`. I noticed that this happens only with `on-my-zsh`, so the `.zshrc` can be simply the line 
``` sh
source $ZSH/oh-my-zsh.sh
```
No `vterm` configuration is needed (tested with `make run`).

1. Open a new terminal
2. Type `ls /home` + return
3. Type `ls -la` + return
4. Type `ls /hom` + M-p
Here is where `vterm` and `ansi-term` differ: in the former the command is completed with `ls -la`, in the latter with `ls /home`. 

If you repeat the steps with arrowup, the two terminals have the same behavior (which is to complete to `ls /home`).

**Comment by Sbozzolo** [comment]
I don't know what changed, but I cannot reproduce anymore this problem with the steps in the previous message.
