### ISSUE TITLE
Comparison to term and ansi-term

### ISSUE THREAD

**Issue by Compro-Prasad** [akermu/emacs-libvterm#14]

**Comment by watkinsr** [comment]
+1

**Comment by QiangF** [comment]
Fzf in ansi-term is supper slow. This project is the last missing piece of an Emacs OS. The other pieces are a Window Manager (https://github.com/ch11ng/exwm), an input method (https://github.com/tumashu/pyim)...

**Comment by deb0ch** [comment]
term and ansi-term not only are super slow but also don't support most of the terminal capabilities, making them unable to run programs such as `less`, `top` or `htop` to name a few.

As soon as you have a few thousands or even hundred lines of output the buffer becomes so slow that it is unusable.

Here the terminal is emulated in C leveraging the `libvterm`, a fully-featured terminal emulation library that already proved its value being used to emulate Vim's terminals (or maybe only Neovim).
