### ISSUE TITLE
ICRNL is not being detected

### ISSUE THREAD

**Issue by adrianparvino** [akermu/emacs-libvterm#151]
RET seems to be translated to C-j when every other terminal emulator uses C-m.

I reverted the fix for #77, and made ICRNL accessible by Elisp. termios however doesn't seem to be returning the correct ICRNL values, even though stty detects it properly.

**Comment by adrianparvino** [comment]
I opened #152 for discussion with code. The root problem seems to specifically be `i_cflag & ICRNL` does not work as expected. My PR might be a non-solution.

**Comment by xendk** [comment]
Could this be the reason why jest interactive mode seems to not get return? I better watch this issue.

**Comment by adrianparvino** [comment]
Most likely, yes. My PR(#152) will probably work for you.

**Comment by martinbaillie** [comment]
Have been running @adrianparvino's fork since around the same time this was reported (🥇) . Can confirm my RET was restored to normal behaviour. Eagerly awaiting revert of #77 in master.

**Comment by xendk** [comment]
I too can confirm that it works nicely.

**Comment by jixiuf** [comment]
this should be fixed
