### ISSUE TITLE
Term height /  scrolling not working right. 

### ISSUE THREAD

**Issue by mbrumlow** [akermu/emacs-libvterm#154]
I have not had time to look in to this much closer, but the screen shot shows what happens in what I think is a combination of drawing a line at the bottom line and then scrolling a region above that excludes the last line from the scroll. 

When I get more time I will try to reproduce in a isolated manner. 

![image](https://user-images.githubusercontent.com/1245807/63621271-214fa480-c5b9-11e9-863b-e9d6817a3954.png)

**Comment by Sbozzolo** [comment]
Do you have specific steps to reproduce this problem?

**Comment by mbrumlow** [comment]
I have not seen this in some time, I think it might be fixed.
