### ISSUE TITLE
Send Elisp Command to Emacs Buffer?

### ISSUE THREAD

**Issue by jasonmj** [akermu/emacs-libvterm#161]
Is it possible to send an elisp command from vterm to the buffer it is running in?

**Comment by FelipeLema** [comment]
you can use `emacsclient` for this, but only if you're running Emacs as server

**Comment by jixiuf** [comment]
after #168 is merged you can send Elisp command like this 
```
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    function vi(){
        echo -n  "\e]51;E(find-file \"$@\")\e\\"
    }
fi
```
