### ISSUE TITLE
Font resizing not rendered properly

### ISSUE THREAD

**Issue by jhacksworth** [akermu/emacs-libvterm#162]
The vterm buffer does not reflect changes in font size properly.

For example, starting with the following screenshot--default font size, running `ls` in a directory. No problems, so far so good:

<img width="853" alt="original-size" src="https://user-images.githubusercontent.com/286057/64825472-6305b680-d58b-11e9-81b1-0fb2a0fcd957.png">

Then, I decrease the font size using the Emacs [command](https://www.gnu.org/software/emacs/manual/html_node/emacs/Text-Scale.html) `text-scale-decrease` and type `ls` again. The output does not reflect the change in font size. There should be more columns in the output of `ls` and the output should continue lower in the window.

<img width="853" alt="resize-font" src="https://user-images.githubusercontent.com/286057/64825503-82044880-d58b-11e9-8ee0-83249df210f6.png">

If I further resize the window and run `ls`, there is more confusion:

<img width="880" alt="resize-window" src="https://user-images.githubusercontent.com/286057/64825599-d90a1d80-d58b-11e9-9e33-11fa5b28023c.png">

This is on MacOS Mojave and Emacs 27.

It would be great to be able to have the vterm font size smaller than the default font sometimes, but even so, vterm is still awesome. Thanks to everyone who has contributed to this package. :)

**Comment by Sbozzolo** [comment]
#230 should (partially) fix this. If you follow the steps you described, you should see that the number of columns of `ls` changes (for new instances of `ls`). The number of columns of past `ls` instances does not change, but the size of the font is properly increased/decreased. Can you check that you find the same behavior? Does this close the issue?

**Comment by hexmode** [comment]
My default font is a proportional font, but I change it for certain modes by using the following code:
``` emacs
(defun mah/set-current-buffer-fixed ()
  "Set the current buffer to use fixed pitch."
  (interactive)
  (set (make-local-variable 'buffer-face-mode-face) 'fixed-pitch)
  (buffer-face-mode t))

;; Fix up these modes for some of the global settings I have
(defvar mah/fixed-width-modes
  '("prog" "org-agenda" "shell" "term" "diff" "dired" "calendar"
    "ssh-tunnels" "magit-popup" "help" "magit-log" "apache" "sql"
    "picture" "ibuffer" "calc-keypad" "proced" "yaml" "makefile"
    "makefile-gmake" " *transient*" "conf" "vterm"))
(dolist (mode mah/fixed-width-modes)
  (add-hook (intern (concat mode "-mode-hook")) 'mah/set-current-buffer-fixed))
```
The above did not work with vterm.  Luckily I found a this bug, though.

I haven't looked closer at this yet, but it would be nice if this worked with the above code as `shell-mode` does.

**Comment by hexmode** [comment]
The small diff above works for my case and seems to work for the issue described here as well.

**Comment by jhacksworth** [comment]
@Sbozzolo Yes, I can confirm, it's working great. Thank you! 🍻
