### ISSUE TITLE
Underscores in promt when using Powerline

### ISSUE THREAD

**Issue by chrbirks** [akermu/emacs-libvterm#163]
Hi

I have a problem with spaces in the prompt being shown as cyan underscores (see screenshot below). Appereantly it's only in the prompt and not in the standard output of the commands. Has anyone seen anything similar? It might be the Powerline wrapper for Bash that inserts some special character that just looks like spaces.

I'm running the latest development version of Emacs 27, Bash 4.4.20 and Powerline for Bash.

![vterm](https://user-images.githubusercontent.com/12070287/65881908-6e7f1d00-e394-11e9-9234-388febec7140.png)

**Comment by mattiasb** [comment]
I had this problem as well. Apparently the issue is with non breaking spaces and Emacs highlighting them.

I added the following to `~/.config/powerline/themes/shell/default_leftonly.json`:
```json
{
    "use_non_breaking_spaces": false
}
```

I also have this in `.config/powerline/config.json`:
```json
{
    "ext": {
	"shell": {
	    "theme": "default_leftonly"
	}
    }
}
```
And then got rid of the cyan underscores.

**Comment by chrbirks** [comment]
Thanks for the info. That does nothing for me unfortunately.

**Comment by mattiasb** [comment]
> Thanks for the info. That does nothing for me unfortunately.

Did you restart the powerline daemon? Also my snippets depends on using the `default_leftonly` theme for the shell extension (yeah, powerline is weird). Maybe you just need to put 
```
{
    "use_non_breaking_spaces": false
}
```
inside `~/.config/powerline/themes/shell/<something>.json` where `something` is whatever the default powerline shell theme is called.

**Comment by chrbirks** [comment]
That was it, I just forgot to restart the powerline daemon. I didn't have a `default_leftonly` theme so I just added the `use_non_breaking_spaces` flag to default.json
