### ISSUE TITLE
byte-code: VTerm needs module support. Please compile your Emacs with the --with-modules option!

### ISSUE THREAD

**Issue by alinbxSorcerer** [akermu/emacs-libvterm#170]
Test with `make run`, it prompt 
```
[$ make run
[  8%] Performing update step for 'libvterm'
[ 16%] No configure step for 'libvterm'
[ 25%] Performing build step for 'libvterm'
[ 33%] No install step for 'libvterm'
[ 41%] Completed 'libvterm'
[ 66%] Built target libvterm
[100%] Built target vterm-module
```
and a fresh emacs window with message 

`byte-code: VTerm needs module support. Please compile your Emacs with the --with-modules option!`

$ emacs --version
GNU Emacs 26.3 on kubuntu 19.10

**Comment by Sbozzolo** [comment]
`vterm` requires Emacs to be compiled with support with the ability to load external modules. Form your error message, it seems that the version of Emacs distributed by Ubuntu does not have such capability. You can double-check that by pasting the following in your scratch buffer
``` emacs-lisp
(message module-file-suffix)
```
and evaluate if with `C-x C-e`. If the result is `nil` (as read in the minibuffer), then you don't meet a requirement.

Maybe someone using Ubuntu can comment on whether this is the case and what is a possible solution. Then, we should add this to the readme.

**Comment by alinbxSorcerer** [comment]
Run `(message module-file-suffix)` , return `nil`

**Comment by Sbozzolo** [comment]
> Run `(message module-file-suffix)` , return `nil`

It means the Emacs executable you are using is not compatible with `vterm`. 

I don't know if there is a place that distributes a pre-built binary for Ubuntu.
A possible solution is to compile Emacs from sources enabling the option `--with-modules` at compile time.

**Comment by alinbxSorcerer** [comment]
ty,  but --with-modules solution is expensive. things are fine now with multi-term. try vterm months later.

**Comment by jixiuf** [comment]
I think this can be closed now .
