### ISSUE TITLE
Something broke interactive tools recently

### ISSUE THREAD

**Issue by dangom** [akermu/emacs-libvterm#175]
Last commit I was in was [from July](https://github.com/akermu/emacs-libvterm/commit/44570d15d220f5d41aa1ce20e84644bd7f891d54).

I recently updated to the latest commit and noticed that tools like `fzf` stopped working properly inside vterm because it's keys (such as Enter), no longer work as in an external terminal.
I don't have the time to investigate this further at the moment, but perhaps somebody else noticed similar issues and can chip in.

**Comment by Sbozzolo** [comment]
I just tested with `nmtui` and found the same behavior.

Given that you have a latest known working configuration, are you
willing to bisect and find the offending commit? You can use `git
bisect` to speed up the process.

If not, I can do it at some point in the near future (maybe in the
weekend).

Daniel Gomez writes:

> Last commit I was in was [from July](https://github.com/akermu/emacs-libvterm/commit/44570d15d220f5d41aa1ce20e84644bd7f891d54).
>
> I recently updated to the latest commit and noticed that tools like `fzf` stopped working properly inside vterm because it's keys (such as Enter), no longer work as in an external terminal.
> I don't have the time to investigate this further at the moment, but perhaps somebody else noticed similar issues and can chip in.

**Comment by dangom** [comment]
Ok, good to know that it's not only at my end.

Unfortunately I won't have any time to look into that until mid Nov the earliest. 
I just reverted to the commit I was in which works just fine.

**Comment by Sbozzolo** [comment]
I bisected the tree and found the offending commit: 7765a7e03e62c954c7ac0a606d513c7e2f59611d. 

I don't know how to fix it, though.

**Comment by AlexLewandowski** [comment]
The same occurs if you set vterm-shell to zsh.

**Comment by Sbozzolo** [comment]
On my system, it makes no difference whether you have `vterm-shell` set to `zsh` or `bash`

**Comment by mpsq** [comment]
Same issue here, the workaround is to do something like:

```bash
export FZF_DEFAULT_OPTS=--bind=ctrl-l:accept
```

Which allows to to use `C-l` instead of `ENTER`.

You also have to do something like:

```elsip
(evil-define-key 'insert vterm-mode-map (kbd "C-l") #'vterm--self-insert)
```

In your emacs config, so `C-l` is sent to the `vterm`. (I use `evil-define-key` but this should for non evil users when using the corresponding function).

**Comment by Sbozzolo** [comment]
PR #152, which addresses this problem, has just been merged

**Comment by mpsq** [comment]
Thanks for the notification @Sbozzolo. I tried it and it seems to work for me now :)

**Comment by olessavluk** [comment]
Just pulled `master` and enter (in `fzf`, `jest`, `htop`) works fine, thanks!
