### ISSUE TITLE
eval unsanitized input unsafe

### ISSUE THREAD

**Issue by herbertjones** [akermu/emacs-libvterm#182]
First, thanks for all the work you've done!

While I do love the ability to trigger events based on escape codes from the terminal, giving any server I log into the ability to execute code on my local system is dangerous.

All that's needed is to output the escape code to the terminal.  This could happen by viewing a file or logging into a server I don't have complete control over.
```
$ printf "\e]51;E(append-to-file \"\\\\necho what is yours is mine\\\\n\" nil (expand-file-name
 \"~/.bashrc\"))\e\\" > ~/read.me
```

Still safe...
```
$ bash
$ exit
```

Then I view the file...
```
$ cat ~/read.me
$ bash
what is yours is mine
$ exit
```

Instead of permitting any code to be evaluated as is, perhaps instead `vterm--eval` could parse the input and run approved commands.

**Comment by herbertjones** [comment]
Something like this could work.

```elisp
(defcustom vterm-eval-cmds
  #s(hash-table test equal
                data ("find-file" find-file
                      "message" message
                      "clear" vterm-clear-scrollback))
  "Map of commands to functions."
  :type 'hash-table
  :group 'vterm)

(defun vterm--eval(str)
  "Parse STR and pass to functions defined in vterm-eval-cmds."
  (let* ((parts (split-string-and-unquote str))
         (command (car parts))
         (args (cdr parts))
         (f (gethash command vterm-eval-cmds)))
    (if f
        (apply f args)
      (message "Failed to find command: %s" command))))
```

```bash
ff() {
  local p=$(realpath "$@")
  printf "\e]51;Efind-file \"$p\"\e\\"
}

clear() {
  printf "\e]51;Eclear\e\\"
}
```

**Comment by jixiuf** [comment]
Can you open a pull request.

I can't change the value of `vterm-eval-cmds` by `customize-variable` ,
so can you change it to alist.
