### ISSUE TITLE
vterm zsh dir tracking

### ISSUE THREAD

**Issue by casouri** [akermu/emacs-libvterm#188]
I think the PROMPT var should be set as `PROMPT=$PROMPT"%{$(vterm_prompt_end)%}"` (double quote)

**Comment by jixiuf** [comment]
I try to change to ``` PROMPT=$PROMPT"%{$(vterm_prompt_end)%}"```. but it does not work for me .

**Comment by casouri** [comment]
My bad, indeed it doesn't work. However, the current code on README appends the `%{$(vterm_prompt_end)%}` part literally to my prompt, which doesn't seem to work either.

I know there is a hook function `chpwd` in zsh that runs after the directory is changed. But adding `printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\"` to that function doesn't update `default-directory` either. Could you tell me what is the `\e]51;A ... \e\\`? It seems like an escape sequence but I don't know where is it from.

**Comment by casouri** [comment]
I see, that escape sequence is voters specific. Let me play around with it a bit.

**Comment by casouri** [comment]
I tried `printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\"` on zsh and nothing happened. It works for bash though. Thoughts?

**Comment by mgsb** [comment]
How did you get tracking working with bash? My same shell settings worked with ansi-term, but not vterm. Neither shell-dirtrack-mode nor dirtrack-mode work for me. Emacs 26.3 on Linux.

**Comment by casouri** [comment]
FWIW, the escape sequence is working, i.e., `printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\"` changes `default-directory` to pwd, but I didn't try adding it to `PROMPT` in bash.

**Comment by jixiuf** [comment]
@casouri  can you try this in zsh 
```
print -Pn  "\e]51;A$(whoami)@$(hostname):/tmp/\e\\";
```
```
printf  "\e]51;A/tmp/\e\\";
```

**Comment by casouri** [comment]
No, neither works for me.

**Comment by MorganJamesSmith** [comment]
so zsh actually has builtin support for stuff like this through the chpwd function (look at the zshmisc manpage). This is probably more robust than the prompt method too. Let me know if it works for you guys!

```
    function chpwd() {
        printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\";
    }
```

**Comment by femtogram** [comment]
Try this:

```
setopt PROMPT_SUBST
PROMPT=$PROMPT'$(vterm_prompt_end)'
```

if you use "$(vterm_prompt_end)" it will set it when you set the prompt. Instead, you want to use `setopt PROMPT_SUBST` and single quotes:

```
If the PROMPT_SUBST option is set, the prompt string is first subjected to parameter expansion, command substitution and arithmetic expansion.
```

**Comment by casouri** [comment]
Fantastic! This works. 😄
