### ISSUE TITLE
Directory head in prompt  has the same color as background.

### ISSUE THREAD

**Issue by rickysaurav** [akermu/emacs-libvterm#190]
First of all, thanks for all the great work. It feels great to not to have to switch to a terminal-emulator for the smallest of commands. 
I am not able to see the directory head for long directories in the prompt.
My emacs theme is spacemacs-dark and my zsh-prompt is powerlevel10k-pure. 
I am attaching the relevant screenshot. The right half is what it looks like on alacritty or any other terminal emulator. The top is what it looks like in vterm , and a highlighted region in the bottom displaying what text is actually present. 
![2019-12-01-00-11-04_2560x1440](https://user-images.githubusercontent.com/13986039/69904785-e7204b00-13d0-11ea-965b-6ced9bd5e6c9.png)

**Comment by jixiuf** [comment]
can not reproduced ,can you share your `~/.p10k.zsh` if you got your  powerlevel10k-pure from https://github.com/romkatv/powerlevel10k.git

**Comment by rickysaurav** [comment]
Hey, It seems that my prompt is a modified version p10k-lean(not p10k-pure) . Here's my p10k config.  
[p10k-config.zsh](https://gist.github.com/rickysaurav/ac2f42ee69a306a64fb2838ef507a4a4)

**Comment by jixiuf** [comment]
I download p10k-config.zsh from https://gist.github.com/rickysaurav/ac2f42ee69a306a64fb2838ef507a4a4
and 
```
source ~/powerlevel10k/powerlevel10k.zsh-theme
source your/p10k-config.zsh
``` 
still cannot reproduced .

**Comment by rickysaurav** [comment]
I think you should be able to reproduce the issue with the following steps. 
1.) zsh -f (i.e. start without any rc)
2.) source ~/powerlevel10k/powerlevel10k.zsh-theme
3.) Will ask to configure powerlevel10k , quit by pressing q 
4.) source your/p10k-config.zsh
5.) Enter a really long directory, everything apart from the directory tail will be invisible.

**Comment by rickysaurav** [comment]
Unable to reproduce on emacs -Q. Must have something to do with my emacs config. Any idea on what emacs configuration could cause this issue?

**Comment by rickysaurav** [comment]
It seems that spacemacs-theme is what's causing issues. I found a minimal set for reproduction of the issue. 
[init file and p10k-config](https://gist.github.com/rickysaurav/ac2f42ee69a306a64fb2838ef507a4a4)
```
emacs -Q -l minimal_init.el 
vterm 
zsh -f 
source ~/powerlevel10k/powerlevel10k.zsh-theme
source your/p10k-config.zsh
```

**Comment by jixiuf** [comment]
try forked https://github.com/jixiuf/spacemacs-theme

**Comment by rickysaurav** [comment]
Tried it out. The change seems to fix the issue.

**Comment by jixiuf** [comment]
you can custom `vterm-color-blue`

**Comment by rickysaurav** [comment]
Thanks, works fine.
