### ISSUE TITLE
Super slow emacs

### ISSUE THREAD

**Issue by BlueFlo0d** [akermu/emacs-libvterm#192]
I'm still experimenting to find a minimal and reliable way to reproduce this issue, just brought it up here to see if anyone else is also encountering this (and if they know the exact cause).
When running emacs-libvterm, occasionally my emacs become super slow and not responsive to inputs, with 100% CPU occupation. It's not doing GC so it can't be a GC stop. I tried run profiler but it didn't report anything suspicious, I think probably it cannot profile ffi library reliably.
I was running an SSH session within vterm and I wonder if that's the cause. I'm currently testing my emacs without running SSH in vterm. I think within a few days I can give a conclusion wether SSH is the cause.

**Comment by BlueFlo0d** [comment]
I seems that without an SSH running this doesn't happen.

**Comment by Sbozzolo** [comment]
Have you experienced this recently?

**Comment by BlueFlo0d** [comment]
Seems that it's working fine now, at least for 24 hours. I'm not sure if some commit resolved the bug because it's probabilistic. I'm closing this however since there's a high chance it got fixed.
