### ISSUE TITLE
directory tracking for bash move cursor to the beginning

### ISSUE THREAD

**Issue by BlueFlo0d** [akermu/emacs-libvterm#197]
I >> those lines into my .bashrc

vterm_prompt_end(){
    printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\"
}
PS1=$PS1'$(vterm_prompt_end)'

then the directory tracking works, but the cursor is moved to the beginning of the prompt line instead
of after the prompt.

bash --version:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by jixiuf** [comment]
can you reproduce this with `make run ` in `emacs-libvterm/build`

**Comment by BlueFlo0d** [comment]
It seems that it's just the problem with the provided PS1 variable.
A bash even outside the emacs experiences this issue. You can just try add this line and run a bash from terminal (I'm on a Mac, not sure about other platforms)

**Comment by jixiuf** [comment]
can't reproduce on my macOS with bash version 3.2.57 
so maybe the reason is   something in your .bashrc
so can you remove some unrelated configuration from your .bashrc

**Comment by BlueFlo0d** [comment]
my .bashrc is kind of empty, that's all of it:
```
export CC="/usr/local/Cellar/llvm/8.0.0/bin/clang"
export PS1='$(hostname):$(pwd) $(whoami)\$ ' # comment out this it becomes normal
export CXX="/usr/local/Cellar/llvm/8.0.0/bin/clang++"
export PATH="/usr/local/bin:/usr/local/opt/llvm/bin:$PATH"
export C_INCLUDE_PATH="/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include"
export PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
vterm_prompt_end(){
    printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\"
}
PS1=$PS1'$(vterm_prompt_end)'
```
Look like I didn't make any mistake copy&pasting the PS1 variable from the readme.
If I comment out the export PS1 line then everything is fine, but seems that any non-trivial PS1 breaks it.

**Comment by jixiuf** [comment]
I reproduced with your .bashrc, but don't  know what caused it .
And if the width of terminal/emacs is big enough ,then the bug will disappear.

**Comment by jixiuf** [comment]
try change 
```
PS1=$PS1'$(vterm_prompt_end)'
```
to 
```
PS1=$PS1'\[$(vterm_prompt_end)\]'
```
