### ISSUE TITLE
bottom line jumps while scrolling

### ISSUE THREAD

**Issue by andreyorst** [akermu/emacs-libvterm#198]
I'm using screen, and I have hardstatus at bottom. When scrolling the satus line jumps between two rows like so:
![image](https://user-images.githubusercontent.com/19470159/70238466-5b187580-177a-11ea-9bd1-b0c5c726b553.png)
![image](https://user-images.githubusercontent.com/19470159/70238448-5358d100-177a-11ea-8f8f-6050c957edfc.png)

**Comment by deadtrickster** [comment]
yep, I see the same

**Comment by andreyorst** [comment]
actually at some point I've stopped seeing this issue. Perhaps it was fixed
