### ISSUE TITLE
Very slow on Emacs 25.2/OSX

### ISSUE THREAD

**Issue by atomontage** [akermu/emacs-libvterm#2]
More than 3 times slower than ansi-term (same TERM setting on both).

I'm using `cd /dev && time ls -la` as a benchmark.

ansi-term with TERM=xterm:
`real    0m1.766s`

vterm with TERM=xterm:
`real    0m5.341s`

As a comparison (no terminal emulation done here):
M-x shell:
`real 0m0.750s`

M-x shell with [xterm-color.el](https://github.com/atomontage/xterm-color) loaded (emulates the ANSI color handling parts):
`real 0m0.854s`

**Comment by atomontage** [comment]
If my reading of the code in vterm-module.c is correct and you're redrawing the entire buffer
on every change, then I guess slowness is to be expected. Ideally, you'd implement some sort
of dirty-rectangle-based rendering that keeps track of parts of the buffer that need to be redrawn.

I don't see any other way that you'd get good performance out of this (maybe tightly integrating vterm with
Emacs core, but that would be something else entirely).

**Comment by jojojames** [comment]
If I modify the hardcoded timer, I get a different conclusion.

ZSH -> time find .

```
;; neovim -> libvterm
find .  0.26s user 1.98s system 32% cpu 6.776 total

;; terminal.app
find .  0.26s user 2.73s system 42% cpu 6.986 total

;; iterm.app
find .  0.26s user 2.76s system 37% cpu 8.116 total

;; (setq vterm-timer (run-with-timer 0 .0001 #'vterm-run-timer buffer))
find .  0.34s user 2.48s system 11% cpu 23.675 total

;; (setq vterm-timer (run-with-timer 0 .001 #'vterm-run-timer buffer))
find .  0.60s user 4.00s system 3% cpu 2:12.94 total

;; (setq vterm-timer (run-with-timer 0 .01 #'vterm-run-timer buffer))
find .  0.63s user 4.88s system 2% cpu 4:27.60 total

;; ansi-term
find . 0.79s user 5.02s system 0% cpu 35:08:35 total
```

Still twice as slow as iterm but an order of magnitude faster than ansi-term (which took 35 minutes).

At .0001, Emacs is probably unusable though.

**Comment by akermu** [comment]
Thanks for the bug report! I'm planning to incrementally update the buffer (also to support scrolling) and make the communication between libvterm and emacs asynchronous via signals, which should improve latency..
I leave this issue open for now.

**Comment by akermu** [comment]
@atomontage Have you run your benchmarks with `emacs -Q` or with customizations?

**Comment by atomontage** [comment]
emacs -Q for everything

**Comment by akermu** [comment]
@atomontage Could you please try out the `async` branch and tell me if performance improves for you? Thanks!

**Comment by jojojames** [comment]
@akermu Works faster for me but there does seem to be some pauses when refreshing the display.

**Comment by atomontage** [comment]
No overall difference but it doesn't slow down as much anymore when there's significant backlog.

Also, key input events can be lost  when one types fast which is annoying.

**Comment by akermu** [comment]
> Also, key input events can be lost when one types fast which is annoying.

@atomontage Could you open a separate issue for that?

**Comment by akermu** [comment]
I updated the code and the performance characteristics for a `find ~` are now similar to rxvt on my laptop. 

@atomontage Could you test it again? Thank you very much!

**Comment by atomontage** [comment]
Last release performs much better. Still slow compared to things like xterm or rxvt, but hey
I can run midnight commander now.

**Comment by fuxialexander** [comment]
@akermu Thanks for the performance optimization! I wonder whether there is any room for further optimization like flush the output to emacs buffer in bunch? I ran a test of `find ~` using uxvrt, neovim's terminal and emacs-vterm. It seems that the first two have block-wise flush and finished very quickly while in emacs-vterm the redraw seems to be the limiting factor of speed.

**Comment by akermu** [comment]
@fuxialexander Currently we don't have much control over the I/O, because it's handled by emacs itself, but @jixiuf did some further work on performance in #39, which should improve the performance of something like `find ~`.
