### ISSUE TITLE
Emacs freezes on vterm start

### ISSUE THREAD

**Issue by tsoernes** [akermu/emacs-libvterm#200]
`M-x vterm` freezes emacs. GNU Emacs 26.3 has `MODULES` feature. libvterm-0-0.8.bzr681.fc30.src.rpm. vterm failed compilation inside of Emacs so it was compiled by hand, removing the Anaconda path variables, then it succeeded.

**Comment by jixiuf** [comment]
can you build a docker image for me  to reproduce this bug

https://github.com/akermu/emacs-libvterm/issues/185#issuecomment-562237077

**Comment by tsoernes** [comment]
I'm not sure how. I can paste my configuration files if that helps. Also `toggle-debug-on-error` does not work as the whole of Emacs is frozen

**Comment by Sbozzolo** [comment]
Can you clean your `vterm` installation and try again from scratch? If you have problems during the compilation stage, let's try to fix that first.

**Comment by tsoernes** [comment]
@Sbozzolo your comment prompted me to pull and build again. This time it works, no changes I think on my end. Thanks!
