### ISSUE TITLE
Cannot insert keypad numbers

### ISSUE THREAD

**Issue by paulbdavis** [akermu/emacs-libvterm#202]
I cannot use the keypad to type numbers, only the number row keys work

According to `describe-key`, the `<kp-[n]>` keys call `vterm--self-insert` but nothing is making it to the terminal it seems

This happens in my default shell (zsh) as well as when using bash

**Comment by jixiuf** [comment]
Does #203 fix your problem?
I do not have a keypad, so could you try #203 and report.

**Comment by paulbdavis** [comment]
I don't have a keypad on this machine, but I'll test this out tomorrow

**Comment by paulbdavis** [comment]
Just tested it out and the patch in #203 works for me
