### ISSUE TITLE
How to build emacs with modules on ubuntu?

### ISSUE THREAD

**Issue by Cumol** [akermu/emacs-libvterm#216]
Maybe a little off-topic, but I am struggling to find out how to install emacs on ubuntu with the modules options.

Can this be done using apt-get or do I have to build emacs from source with the `--with-modules `option?

**Comment by ddoherty03** [comment]
On ubuntu, I recommend adding Kevin Kelley's PPA and installing his emacs 26 package:

    sudo add-apt-repository ppa:kelleyk/emacs
    sudo apt update
    sudo apt-get install emacs26

You may want to do a purge of the ubuntu emacs package before you start.

Also, after you get it installed, I found that ubuntu's use of /bin/dash as the link to /bin/sh causes the compile to choke.  I re-linked /bin/sh to /bin/bash and finally got a compile to work.

**Comment by Cumol** [comment]
Do you think installing it using linuxbrew would also do the trick?

`brew install --with-modules emacs`

**Comment by Cumol** [comment]
Used your suggestion and installed emacs from the ppa. Didn't have to re-link /bin/sh just needed to install libtool and cmake > 3.11 (using brew install cmake).

**Comment by Sbozzolo** [comment]
Is any of you guys interested in writing up something in the README regarding using `emacs-libvterm` on Ubuntu? I suspect that this is a very common problem that would be useful to address for other present and future users

**Comment by Cumol** [comment]
@Sbozzolo I can do this, but how? Do I simply fork the file?

**Comment by Sbozzolo** [comment]
If you are familiar with the process of contributing, you can 
1. Fork the repo
2. Create a new branch
3. Edit the readme (maybe under the section installation, put a subsection regarding ubuntu users)
4. Make a pull request

If you are not, or don't want to go through the trouble, you can just write something here and I will take the aforementioned steps. However, this will mark the contribution as mine, which is unfair towards you, if you care about these things.

**Comment by Cumol** [comment]
I will try this. Since it is my first time, please have patience (but I will manage!) :)
