### ISSUE TITLE
vterm-clear-scrollback not working

### ISSUE THREAD

**Issue by CSRaghunandan** [akermu/emacs-libvterm#218]
`vterm-clear-scrollback` does nothing when  I run `C-c C-l`. I've followed the instructions as specified in the documentation and the alias for `clear` has been set correctly when inside the `vterm` buffer.

**Comment by Sbozzolo** [comment]
This feature was introduced in bc6c07f29d00719812635138dd1f81f9b5eb8fdd

Could you please check if that commit is working as expected? In that case, could you bisect to find the offending commit?

**Comment by Sbozzolo** [comment]
@CSRaghunandan can you check that, with #233 (in master), `vterm` behaves as intended?

**Comment by CSRaghunandan** [comment]
@Sbozzolo Its working as expected.

I'll close this issue
