### ISSUE TITLE
ZSH completion not scrolling

### ISSUE THREAD

**Issue by paulbdavis** [akermu/emacs-libvterm#222]
When the cursor is at the bottom of the buffer and zsh completion is initiated, the buffer does not scroll unless you hit tab for a second time (selecting the next completion in zsh)

Here is the display after typing `git` and hitting `<tab>` once

![zsh-comp-1](https://user-images.githubusercontent.com/2730634/73486004-701c1a00-4361-11ea-8534-bb9623b94a81.png)

Then after hitting `<tab>` again the full list of completions show (large here, but it also presents when the list of completions is all on one line)

![zsh-comp-2](https://user-images.githubusercontent.com/2730634/73486035-832eea00-4361-11ea-8159-36121f626561.png)

**Comment by jixiuf** [comment]
can you try #225

**Comment by paulbdavis** [comment]
@jixiuf @akermu Yup, that fixes the issue (aside, straight.el really showing it's usefulness here!)
