### ISSUE TITLE
Recursive load when loading from file named term.el

### ISSUE THREAD

**Issue by petercheng00** [akermu/emacs-libvterm#235]
This is a strange problem, and perhaps a bug outside of vterm, but I can't figure out what's going on. I recently reorganized my init files and put vterm in a file called 'term.el', and am now hitting a strange crash due to "recursive load" on startup

A minimal case that reproduces for me:
init file:
```
(add-to-list 'load-path "~/emacs")
(load-library "term")
```
~/emacs/term.el:
```
(use-package vterm
  :ensure t)
```

I then get:
```
Error (use-package): vterm/:catch: Recursive load: "/home/pcheng/emacs/term.el", "/home/pcheng/.config/emacs/elpa/vterm-20200207.425/vterm.el", "/home/pcheng/emacs/term.el", "/home/pcheng/.config/emacs/elpa/vterm-20200207.425/vterm.el", "/home/pcheng/emacs/term.el", "/home/pcheng/.config/emacs/elpa/vterm-20200207.425/vterm.el", "/home/pcheng/emacs/term.el", "/home/pcheng/.config/emacs/elpa/vterm-20200207.425/vterm.el", "/home/pcheng/emacs/term.el", "/home/pcheng/.config/emacs/init.el"
Error (use-package): vterm/:catch: Loading file /home/pcheng/emacs/term.el failed to provide feature ‘term’ [3 times]
```
If I rename my term.el file to anything else (e.g. term2.el), vterm loads fine.
I don't understand how vterm.el could be loading my term.el, a look at the file doesn't reveal anything obvious, and deleting and re-installing from melpa doesn't help.

I see that there's a term.el in emacs source, could that be interfering somehow?

I'm on ubuntu, emacs 27.0.50 built off of master a few months ago. I also went on a different computer, and built emacs off of master yesterday, and reproduced the same problem.

**Comment by Sbozzolo** [comment]
I think what is happening is the following. `vterm` requires `term` (line 55 of `vterm.el`). This `term` sould be the one bundled with Emacs. You added `.emacs` to your `load-path`, so Emacs looks into that folder to find a `term.el`. Emacs finds `term.el` in the `load-path` and tries to load it. However, your file does not provide the `term` symbol (ie, you don't have the `(provide 'term)` line at the end of the file. Hence, you get this error
```
Loading file /home/pcheng/emacs/term.el failed to provide feature ‘term’
```
And, of course, you have that your `term` and `vterm` try to include each other.

This is not a problem with `vterm`, but with your setup. I suggest you rename your file with something like `my_term.el`. I will close this issue, feel free to re-open if there are additional problems.

**Comment by Sbozzolo** [comment]
I recommend reading the docstring for `require` for more information.
