### ISSUE TITLE
Automatically setting the title of the buffer

### ISSUE THREAD

**Issue by jethrokuan** [akermu/emacs-libvterm#236]
I see that there's a hook `vterm-set-title-functions` which supposedly contains an example of setting the buffer title.

However, later on I see that it's only called on `vterm--set-title`, which in turn is not called anywhere else, so that hook is not being used at all.

**Comment by jixiuf** [comment]
`vterm--set-title` is called in `vterm-module.c`.

I use zsh ,this is my config:
```
        autoload -U add-zsh-hook
        add-zsh-hook -Uz chpwd (){
            # https://www.xfree86.org/current/ctlseqs.html
            # https://www.iterm2.com/documentation-escape-codes.html
            # https://wiki.bash-hackers.org/scripting/terminalcodes
            # https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
            # print -Pn "\e]51;$(pwd)\e\\";
            print -Pn "\e]2;%2~\a" 
            # ESC]0;stringBEL — Set icon name and window title to string
            # ESC]1;stringBEL — Set icon name to string
            # ESC]2;stringBEL — Set window title to string
 
        }
```
See http://tldp.org/HOWTO/Xterm-Title-4.html about how to set
terminal title for different shell

**Comment by jethrokuan** [comment]
I see, thanks!
