### ISSUE TITLE
Close buffer and (optional) window when a vterm process is finished.

### ISSUE THREAD

**Issue by VanLaser** [akermu/emacs-libvterm#24]
Currently I'm using this, adapted from some code used with Emacs `shell` mode :

```elisp
(defun vterm--kill-vterm-buffer-and-window (process event)
  "Kill buffer and window on vterm process termination."
  (when (not (process-live-p process))
    (let ((buf (process-buffer process)))
      (when (buffer-live-p buf)
        (with-current-buffer buf
          (kill-buffer)
          (ignore-errors (delete-window))
          (message "VTerm closed."))))))

(add-hook 'vterm-mode-hook
          (lambda ()
            (set-process-sentinel (get-buffer-process (buffer-name))
                                  #'vterm--kill-vterm-buffer-and-window)))
```

First, is this ok (it seems to be working alright for me, even for multiple terminals), or can the code be made shorter/better? Also, would it be a good idea to have something similar to this functionality integrated into `vterm`, using a couple of variables/`defcustom`s (to automatically kill buffer when process exits, or to kill buffer *and* window when process exits) ?

(Also, feel free to close at any time)

**Comment by deb0ch** [comment]
Killing the buffer makes 100% sense to me, actually it annoys me that it stays alive.

I'm not so sure about killing the window automatically by default. It does not reflect the default behaviour of Emacs buffers and would be a surprising behaviour at best. I am sure it would break the workflow of many emacs users.

**Comment by deb0ch** [comment]
I just tried your code snippet and it does not work for me. The hook is set allright, but `vterm--kill-vterm-buffer-and-window` never gets called when I exit the shell (for instance by entering `exit` in the command line).

When I print `(buffer-name)` and `(get-buffer-process (buffer-name))` they give values that make sense though:

```elisp
      (add-hook 'vterm-mode-hook
                (lambda ()
                  (message "buffer-name = %s\nprocess = %s"
                           (buffer-name)
                           (get-buffer-process (buffer-name)))
                  (set-process-sentinel (get-buffer-process (buffer-name))
                                        'vterm--kill-vterm-buffer-and-window)))
```
outputs
```
buffer-name = vterm
process = vterm
```

**Comment by VanLaser** [comment]
Don't know what to say, it works here, and it's ... very heavily inspired from [this post](https://www.reddit.com/r/emacs/comments/8grxir/elisp_snippet_kill_buffer_and_window_on_shell/). Try to add a `(message "%s" event)` in the `vterm--kill-vterm-buffer-and-window` function - you should get a "finished" message the process exits.

**Comment by deb0ch** [comment]
I print `(message "Yolo")` as the very first line of `vterm--kill-vterm-buffer-and-window` but it never shows.

I just printed `(message "lol = %s" (process-sentinel (get-buffer-process (buffer-name))))` and it printed 
```
"lol = #[514 \\302\\303\\304\\305#)\\266\\203\\205\\306 \\203\\307	!\\207\\310 \\207 [inhibit-changing-match-data shell-pop-last-buffer \\(?:finished\\|exited\\) nil t string-match one-window-p switch-to-buffer delete-window] 9
```
which I guess has been set by `shell-pop` that I'm using (because that's how we use shells in Spacemacs).

So I guess you cannot set several sentinels to a process - at least this way. I will investigate more on this later today.

**Comment by deb0ch** [comment]
Just stumbled upon this line when looking up [process sentinels](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sentinels.html):
```
In case a process status changes need to be passed to several sentinels, you can use add-function to combine an existing sentinel with a new one. See Advising Functions.
```
Maybe it makes more sense to use `add-function` like they say, I don't know exactly how. Maybe sth like
```elisp
(set-process-sentinel (add-function
                       :after
                       (process-sentinel  (get-buffer-process (buffer-name)))
                       #'vterm--kill-vterm-buffer-and-window))
```

**Comment by akermu** [comment]
I added the hook `vterm-exit-hook` to customize the behaviour. If you want to kill the buffer, add this to your init file:

```elisp
(add-hook 'vterm-exit-hook (lambda ()
                             (kill-buffer)))
```

If you want to kill the buffer and delete the window

```elisp
(add-hook 'vterm-exit-hook (lambda ()
                             (let* ((buffer (current-buffer))
                                    (window (get-buffer-window buffer)))
                               (when window
                                 (delete-window window))
                               (kill-buffer buffer))))
```

**Comment by zed** [comment]
In case, google will send somebody else here: there is `vterm-kill-buffer-on-exit` custom variable now:

```emacs-lisp
(use-package vterm
  :commands (vterm vterm-other-window)
  :custom (vterm-kill-buffer-on-exit t))
```

**Comment by PureFunctor** [comment]
For anyone stumbling upon this issue from Google: `vterm-exit-hook` became `vterm-exit-functions`:
```elisp
(use-package vterm
  :ensure t
  :init
  (add-hook 'vterm-exit-functions
     (lambda (_ _)
       (let* ((buffer (current-buffer))
              (window (get-buffer-window buffer)))
         (when (not (one-window-p))
           (delete-window window))
         (kill-buffer buffer)))))
```
