### ISSUE TITLE
Background does not continue to end of line

### ISSUE THREAD

**Issue by Stebalien** [akermu/emacs-libvterm#241]
Background colors do not extend to the end of the line on emacs built from git:

> GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.3, Xaw3d scroll bars) of 2020-02-06

![2020-02-15-104733_2560x1440_scrot](https://user-images.githubusercontent.com/310393/74593496-950ac100-4fe0-11ea-914b-3c4532fa8d19.png)

I'm guessing this is related to the new `:extend` face property (https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774).

**Comment by Sbozzolo** [comment]
Thanks for the bug report. The new face property is most definitely the culprit. At the moment, I don't know how to fix this.
