### ISSUE TITLE
Incompatibility with implementations of stty that do not support utf8 (eg, FreeBSD)

### ISSUE THREAD

**Issue by BlueFlo0d** [akermu/emacs-libvterm#242]
I'm on FreeBSD 12.1-RELEASE r354233.
The vterm buffer shows this message right after I `make` and `make run`.
Any ideas? Commit 58b4cc4 seems to show that there's effort making this package work on FreeBSD.
Have anyone successfully run it on BSD?

**Comment by BlueFlo0d** [comment]
After some debugging, I found the problem is in line 277 vterm.el
```
:command `("/bin/sh" "-c"
                      ,(format "stty -nl sane iutf8 erase ^? rows %d columns %d >/dev/null && exec %s"
                               (window-body-height)
                               width vterm-shell))
```
The FreeBSD version of stty does not have iutf8 option. changing it to
```
:command `("/bin/sh" "-c"
                      ,(format "stty -nl sane erase ^? rows %d columns %d >/dev/null && exec %s"
                               (window-body-height)
                               width vterm-shell))
```
make it work for me.

Not sure if this is the best way. Dropping iutf8 might have some unexpected effect I think?

**Comment by Sbozzolo** [comment]
More info is here https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220009

It would be best if the bug was fixed upstream. Given that the bug report was opened 3 years ago, the hopes for a quick solution are not high. If other FreeBSD users want to chime in and share their experience, that would be helpful.

**Comment by ercdude** [comment]
First, thanks for this issue and @BlueFlo0d for the debugging, saved me some time.

I had the same issue here on my FreeBSD. Changing that line 277 as @BlueFlo0d said solved my problem. Everything seems works just fine, except that the default color of my `fish`is black and I dont know why lol, but I guess it's unrelated to this thread.

**Comment by aramirez** [comment]
Thanks BlueFlo0d. For reporting this and the workaround.
Thanks Sbozzolo for the link to the bug. It is a very old bug.

**Comment by jixiuf** [comment]
#422 is ,merged
