### ISSUE TITLE
When I type fi quickly, it insert ii

### ISSUE THREAD

**Issue by Linuus** [akermu/emacs-libvterm#247]
When I type the characters `fi` quickly in a vterm buffer, it inserts `ii`. I have no idea if this is actually a bug in this project or some other plugin that clashes with vterm somehow, but I haven't found this issue anywhere else.

Does anyone else have the same issue?

**Comment by kamoii** [comment]
I'm using vterm heavly recently, but don't have this issue. Tried inputing `fi` as fast as I can, but it just inserts `fi`.

**Comment by Linuus** [comment]
Hehe ok, thanks for testing :D Yeah it's really weird... Probably some package that causes it.

**Comment by Linuus** [comment]
Hm, it's `evil-escape` that causes it. It sends escape when `fd` is pressed quickly so somehow it screws things up I guess 😢

**Comment by Linuus** [comment]
I guess this is more of an issue with evil-escape 🤔 Closing.
