### ISSUE TITLE
Get current directory

### ISSUE THREAD

**Issue by Linuus** [akermu/emacs-libvterm#248]
Hi

Is it possible to get the current directory we are in? I mean, if I open a vterm buffer and cd into the dir `/Foo/bar/baz`, can I get that directory path somehow?

**Comment by kamoii** [comment]
@Linuus If you set up [directory-tracking](https://github.com/akermu/emacs-libvterm#directory-tracking), you can access current directory with `default-directory` buffer local variable.

**Comment by Sbozzolo** [comment]
If directory tracking is enabled, you can use `vterm--get-pwd`. Is this what you are looking for?

**Comment by twagtwig** [comment]
Seems like this issue can be closed.
