### ISSUE TITLE
No way to change default shell

### ISSUE THREAD

**Issue by IFcoltransG** [akermu/emacs-libvterm#249]
Does not seem to read ESHELL or SHELL environment variable, the explicit-shell-file-name or shell-file-name. (I wanted to use zsh rather than bash, so my workaround was to check in .bashrc if IN_EMACS was set to vterm and exec zsh if so.)

**Comment by kamoii** [comment]
@IFcoltransG Did you try [`vterm-shell` variable?](https://github.com/akermu/emacs-libvterm#vterm-shell)

**Comment by Sbozzolo** [comment]
`vterm-shell` defaults to `shell-file-name`. In my system, I don't explicitly set it, but I still have that `vterm-shell` is `/bin/zsh`, which is read from `SHELL`.

**Comment by IFcoltransG** [comment]
@kamoii Looks like I missed that entire section. `vterm-shell` behaves as expected.
