### ISSUE TITLE
how to interrupt a process in vterm

### ISSUE THREAD

**Issue by sunwayforever** [akermu/emacs-libvterm#25]
`C-c C-c` or `C-c C-k` just don' t work.

**Comment by deb0ch** [comment]
If you test using the `make run` command you will see that it actually works there.

I was facing the same issue, what I think is happening is that whenever another mode defines a binding with `C-c` as a prefix, `vterm` cannot grab `C-c` anymore to send it to the terminal.

It might be what this docstring is referring to: `If you use a keybinding with a prefix-key that prefix-key cannot be send to the terminal.` (https://github.com/akermu/emacs-libvterm/blob/master/vterm.el#L51)

For now defining a binding yourself should do the work:
```elisp
(define-key vterm-mode-map (kbd "C-c C-c") 'vterm--self-insert)
```
this will make `C-c C-c` send `C-c` to your terminal.

I believe something similar should end up in this package eventually (hopefully shortly).

**Comment by akermu** [comment]
You can now bind the keyboard interrupt to whatever you like, with:
```
(define-key vterm-mode-map (kbd "C-c C-c") 'vterm--self-ctrl-c)
```
The above is also the fault now.

**Comment by deadtrickster** [comment]
Just for history - I had to disable flycheck and yasnippet for the vterm to get C-c C-c.
