### ISSUE TITLE
C-<backspace> self insert not bound to 'kill' in stty

### ISSUE THREAD

**Issue by IFcoltransG** [akermu/emacs-libvterm#250]
When set to `vterm--self-insert`, <C-backspace> appears as `7;5u` rather than functioning correctly. It could either be changed to something like C-u (^U) within vterm (which stty should recognise as `kill`), or stty could be set to interpret `7;5u` as kill, in the same way `erase` is `^?`.
(For reference, I'm using Ubuntu 18.04.4 LTS on WSL, running emacs through an X Server which should be irrelevant, using zsh inside vterm. Emacs version "GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-17", and zsh version "zsh 5.4.2 (x86_64-ubuntu-linux-gnu)".)

**Comment by Sbozzolo** [comment]
Why should `C-<backspace>` be bound to `kill`? The terminals I have installed on my system don't do that. For example, `xterm`.

**Comment by IFcoltransG** [comment]
My perspective is of wanting to bring vterm in line with the rest of emacs. `C-<backspace>` as a key needn't be rebound in vterm, in the same way `C-<arrows>` aren't rebound. But if I configure `C-<left>` to pass through emacs to the terminal, then it behaves as expected, a `left-word` equivalent from within the terminal. The same cannot be said for `C-<backspace>`; getting a `backward-kill-word` for vterm requires fiddling in the terminal layer, which should be configurable from the emacs layer.
The simplest way to fix that is to make the terminal automatically understand the `C-<backspace>` sequence, in the same way emacs would understand it. Currently it doesn't understand the key as anything at all.

**Comment by Sbozzolo** [comment]
While I think about what you say:
In my configuration I have:
```emacs-lisp
(define-key vterm-mode-map (kbd "<C-backspace>") 
           '(lambda () (interactive) (vterm-send-key (kbd "C-w"))))
```
With this, `C-<backspace>` kills the previous word.

**Comment by IFcoltransG** [comment]
Thank you for the alternative workaround.

**Comment by runekaagaard** [comment]
This makes ctrl+arrow skip words back and forward:

```
(define-key vterm-mode-map (kbd "<C-left>") 'vterm-send-M-b)
(define-key vterm-mode-map (kbd "<C-right>") 'vterm-send-M-f)
```

**Comment by IFcoltransG** [comment]
My current config simply sets them to `'vterm--self-insert`.
