### ISSUE TITLE
function definition file not found 

### ISSUE THREAD

**Issue by taigacute** [akermu/emacs-libvterm#255]
when open vterm i got these error. my zshrc work fine on iterm2
![image](https://user-images.githubusercontent.com/41671631/75237459-5522b580-57fa-11ea-9cea-8ce4fbbdd40a.png)

**Comment by Sbozzolo** [comment]
The first line indicates that the variable `FPATH` is not correctly set. This may be due to some broken installation of `zsh`. There might some something improperly configured on your system, maybe you have two different versions of zsh installed?

**Comment by taigacute** [comment]
@Sbozzolo  yes the catalina had install zsh .brew installed one .
