### ISSUE TITLE
forward esc to vterm

### ISSUE THREAD

**Issue by zhengyangfeng00** [akermu/emacs-libvterm#256]
Hi, I wonder if it's possible to forward ESC to vterm. This is useful when I do git commit from vterm, which opens vim inside vterm and I need to enter the normal state then do a `:x`.

I tried something like this(I'm using evil mode): 
```
    (evil-define-key 'insert vterm-mode-map (kbd "<escape>") #'vterm--self-insert)
    (evil-define-key 'normal vterm-mode-map (kbd "<escape>") #'vterm--self-insert)
```
but after pressing ESC in vterm it's waiting for the next input instead of forwarding the ESC to vterm.

**Comment by jixiuf** [comment]
I think you should bind these keys in `vterm-mode-hook`

**Comment by zhengyangfeng00** [comment]
hmm I tried adding:

```
(add-hook 'vterm-mode-hook
            (lambda () (local-set-key [escape] #'vterm--self-insert)))
```

and it doesn't seem to work, probably because ESC is a special key in emacs, according to [this](https://emacs.stackexchange.com/questions/14755/how-to-remove-bindings-to-the-esc-prefix-key) SO question.

Also tried:

```
(add-hook 'vterm-mode-hook
            (lambda () (define-key key-translation-map (kbd "ESC") #'vterm--self-insert)))
```

Then if I press ESC in vterm mode, this error happens:

```
Wrong number of arguments: ((vterm-mode-abbrev-table vterm-mode-syntax-table t) nil "Sends invoking key to
libvterm." (interactive) (if vterm--term (progn (let* ((modifiers (event-modifiers last-input-event)) (shift (memq
(quote shift) modifiers)) (meta (memq (quote meta) modifiers)) (ctrl (memq (quote control) modifiers))) (let*
((key (and t (key-description (vector ...))))) (if key (vterm-send-key key shift meta ctrl) nil)))))), 1
```

**Comment by ercdude** [comment]
I don't know if it's just me (and my lack of knowledge) but ESC is a tricky thing in emacs. I recommend you to use magit instead, or avoid opening vim inside emacs... since you are already in a editor there is no need to open another.

**Comment by jixiuf** [comment]
try this 
```
(add-hook 'vterm-mode-hook
          (lambda ()
            (evil-define-key 'insert 'local [escape] 'vterm--self-insert)))
```

**Comment by zhengyangfeng00** [comment]
> try this
> 
> ```
> (add-hook 'vterm-mode-hook
>           (lambda ()
>             (evil-define-key 'insert 'local [escape] 'vterm--self-insert)))
> ```

It still doesn't work for me. The way I tested this was:
- open a vterm buffer
- M-shift-: to eval lisp, and type in `(evil-define-key 'insert 'local [escape] 'vterm--self-insert)`
- press ESC key and see if it's waiting for next key, and if so, the test fails

**Comment by zhengyangfeng00** [comment]
> I don't know if it's just me (and my lack of knowledge) but ESC is a tricky thing in emacs. I recommend you to use magit instead, or avoid opening vim inside emacs... since you are already in a editor there is no need to open another.

Yeah I love magit! but in certain cases using command line is more efficient. Another use case is I need to create code reviews with the `arc` command, which opens an editor for you to input diff details. Usually I split a temporary panel in tmux for this(or run git commands that uses editor), but it would be more efficient to complete this in vterm

**Comment by jpkotta** [comment]
Does this work?

```
  (defun vterm-send-escape ()
    "Sends `ESC` to the libvterm."
    (vterm-send-key "[" nil t nil))
```

**Comment by pRot0ta1p** [comment]
The [evil-collection](https://github.com/emacs-evil/evil-collection/blob/master/modes/vterm/evil-collection-vterm.el)  seems to have a solution to this.

This might be irrelevant, but you can try set $EDITOR to something like` emacsclient -na', and run a emacs daemon, then commit should pull up a emacs window rather than vim.

**Comment by jeffyql** [comment]
> Does this work?
> 
> ```
>   (defun vterm-send-escape ()
>     "Sends `ESC` to the libvterm."
>     (vterm-send-key "[" nil t nil))
> ```

It doesn't work for me, nor does (vterm-send-key "[" t, nil, nil), but I found this does work in my case:
(defun vterm-send-escape ()
 (vterm-send-key "<escape>")
 )

**Comment by jpkotta** [comment]
> > Does this work?
> > ```
> >   (defun vterm-send-escape ()
> >     "Sends `ESC` to the libvterm."
> >     (vterm-send-key "[" nil t nil))
> > ```
> 
> It doesn't work for me, nor does (vterm-send-key "[" t, nil, nil), but I found this does work in my case:
> (defun vterm-send-escape ()
> (vterm-send-key "<escape>")
> )

This works for me too, and is easier to understand.

**Comment by zhengyangfeng00** [comment]
Thanks for all the help!
