### ISSUE TITLE
cmake failed to build on Catalina

### ISSUE THREAD

**Issue by casouri** [akermu/emacs-libvterm#259]
Although not related to libvterm. I think it is good to post since there are people using Catelina and libvterm. When I build with cmake I get this error:

```
-- The C compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CMake Error: Generator: execution of make failed. Make command was: /usr/local/bin/gmake cmTC_b126a/fast &&
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- broken
CMake Error at /opt/local/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/yuan/attic/emacs-libvterm/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/local/bin/gmake cmTC_b126a/fast && No such file or directory
    Generator: execution of make failed. Make command was: /usr/local/bin/gmake cmTC_b126a/fast &&




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/yuan/attic/emacs-libvterm/build/CMakeFiles/CMakeOutput.log".
See also "/Users/yuan/attic/emacs-libvterm/build/CMakeFiles/CMakeError.log".
```

The problem is that cmake cannot find make. By default it's in `/user/bin/make`. I tried
```
export CMAKE_MAKE_PROGRAM="/usr/bin/make"
```
but it didn't work. The cmake file didn't mention anything about make location either. Any thoughts?

**Comment by Sbozzolo** [comment]
What are the outputs of `which gmake` and `which make`?

**Comment by casouri** [comment]
`/opt/local/bin/gmake` and `/usr/bin/make`. That's the mistery... I have installed homebrew before but I'm not anymore, there's nothing in `/usrl/local/bin`.

**Comment by Sbozzolo** [comment]
I am not sure what is going on. Can you try a clean build with 
`cmake -DCMAKE_MAKE_PROGRAM="$(which make)" ..` and then `cmake --build .` instead of `make`?

**Comment by casouri** [comment]
Thanks, the `-D` flag worked. Seems that CMake picks up all sorts of environment variables from a mysterious place. Do you have any guess why?

**Comment by Sbozzolo** [comment]
To me, CMake is like a box of chocolates: you never know what you are going to find when you open it.
