### ISSUE TITLE
zsh: command not found: vterm_prompt_end

### ISSUE THREAD

**Issue by casouri** [akermu/emacs-libvterm#262]
On vanilla Emacs 27.0.6, commit 570f3d5e6ea6bb87f72c333f975b07243fa1b5bb when I start `vterm` and enter zsh, zsh complains about `zsh: command not found: vterm_prompt_end`.

zshrc:
```
# Emacs vterm sync cwd
if [ "$INSIDE_EMACS" = "vterm" ]
   then setopt PROMPT_SUBST
        PROMPT=$PROMPT'$(vterm_prompt_end)'
fi
```

This start to happen after I pulled the latest commit.

**Comment by Sbozzolo** [comment]
You should add
```sh
function vterm_printf(){
    if [ -n "$TMUX" ]; then
        # tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}
```
somewhere in your `zshrc` file.

I agree, it is not clear from the readme. The readme has to be updated
to be more informative regarding these functions.


Yuan Fu writes:

> On vanilla Emacs 27.0.6, commit 570f3d5e6ea6bb87f72c333f975b07243fa1b5bb when I start `vterm` and enter zsh, zsh complains about `zsh: command not found: vterm_prompt_end`.
>
> zshrc:
> ```
> # Emacs vterm sync cwd
> if [ "$INSIDE_EMACS" = "vterm" ]
>    then setopt PROMPT_SUBST
>         PROMPT=$PROMPT'$(vterm_prompt_end)'
> fi
> ```
>
> This start to happen after I pulled the latest commit.

**Comment by casouri** [comment]
Sorry! It's a long time since I used vterm because of the directory tracking issue. I should've reread the readme.

But I agree the reade me can use some relayout. It was no easy to follow when I was reading it the first time. Maybe move some of the content to a wiki.
