### ISSUE TITLE
vterm-copy-mode not binding its mode-map

### ISSUE THREAD

**Issue by ercdude** [akermu/emacs-libvterm#263]
I've been using the libvterm for a while and could not find a way to bind the `vterm-copy-mode` to exit the copy mode, because it removes any mode when it's enabled. To avoid the issue, I had to make a change in the line 419 of vterm.el:

```
(define-minor-mode vterm-copy-mode
  "Toggle vterm copy mode."
  :group 'vterm
  :lighter " VTermCopy"
  :keymap vterm-copy-mode-map
  (if vterm-copy-mode
      (progn                            ;enable vterm-copy-mode
        ;; it removes the map, so can't disable the mode with keybinds
        ;;(use-local-map nil)
        (use-local-map vterm-copy-mode-map) ;; set the right map
        (vterm-send-stop))
    (vterm-reset-cursor-point)
    (use-local-map vterm-mode-map)
    (vterm-send-start)))
```

maybe I'm missing something? I'm not using use-package, so maybe the hint :keymap has been ignored? I've tried both with nothing (just add to `load-path`) and with `cask`, which I think that just adds it as well.

**Comment by Sbozzolo** [comment]
Do you want to bind a key to exit `vterm-copy-mode`?
I expect that something like this 
```emacs-lisp
(define-key vterm-copy-mode-map (kbd "C-c C-k") 'vterm-copy-mode)
```
would work (not tested).

**Comment by ercdude** [comment]
That's the point, the `vterm-copy-mode-map` is never assigned, because it's set to nil.

**Comment by Sbozzolo** [comment]
> ```emacs-lisp
> ```emacs-lisp
> (define-key vterm-copy-mode-map (kbd "C-c C-k") 'vterm-copy-mode)
> ```
> ```

I tried this on a clean Emacs (`emacs -Q`) and it works. I can bind any function:
```emacs-lisp
 (define-key vterm-copy-mode-map (kbd "C-c C-k") 
                   '(lambda () (interactive) (message "HI")))
```

Or, I don't understand the problem.

**Comment by ercdude** [comment]
which package manager are you using? I'll try a fresh install

**Comment by Sbozzolo** [comment]
> > ```emacs-lisp
> > (define-key vterm-copy-mode-map (kbd "C-c C-k") 'vterm-copy-mode)
> > ```
> 
> I tried this on a clean Emacs (`emacs -Q`) and it works. I can bind any function:
> 
> ```emacs-lisp
>  (define-key vterm-copy-mode-map (kbd "C-c C-k") 
>                    '(lambda () (interactive) (message "HI")))
> ```
> 
> Or, I don't understand the problem.

This was with no package managers and Emacs with no configurations.

**Comment by ercdude** [comment]
ok, my bad!! I was cleaning the minor mode keymaps lol it works good, no problem at all.
