### ISSUE TITLE
vterm--get-prompt-point-internal always returns nil

### ISSUE THREAD

**Issue by jjzmajic** [akermu/emacs-libvterm#265]
Is there a way to fix this so that `vterm--at-prompt-p` does not rely on hacky `term-skip-char` regex magic?

Currently running Emacs 26.3 with zsh and all the helper functions pasted into my `.zshrc`.

**Comment by jixiuf** [comment]
see https://github.com/akermu/emacs-libvterm#directory-tracking
put this in your .zshrc
```
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
```

or put this in your .zshrc
```
vterm_prompt_end(){
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}
PS1=$PS1'\[$(vterm_prompt_end)\]'
```

**Comment by jjzmajic** [comment]
Hmmm, I had the zsh version in already. Let me try the bash version

**Comment by jjzmajic** [comment]
Oh, double quotes. There's a typo in the readme. The function is not getting evaluated.

**Comment by jjzmajic** [comment]
This works:
```zsh
vterm-printf() {
    if [[ -n "$TMUX" ]]; then
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [[ "${TERM%%-*}" = "screen" ]]; then
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    alias clear='vterm-printf "51;Evterm-clear-scrollback";tput clear'
fi
vterm-prompt-end() { vterm-printf "51;A$(whoami)@$(hostname):$(pwd)"; }
PROMPT=$PROMPT"%{$(vterm-prompt-end)%}"
```

**Comment by Sbozzolo** [comment]
Thanks, @jjzmajic, I found the same behavior and found that the problem is indeed the quotes. I updated the readme

**Comment by jjzmajic** [comment]
Thanks!

**Comment by jixiuf** [comment]
it should be 
```
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}
setopt PROMPT_SUBST
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
``` 

if you change 
```
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
``` 
to 
```
PROMPT=$PROMPT"%{$(vterm_prompt_end)%}"
```
 directory tracking won't work.
#269 
#188

**Comment by jjzmajic** [comment]
Copy pasted into my config exactly as I posted it (with double quotes), and the function returns the correct point value

**Comment by jixiuf** [comment]
Yes it return the correct point value, But  the `directory tracking`  does not work.
try 
```
cd /tmp/
```
and   `C-xC-f`  
the `default-directory` do not changed to `/tmp/` (with double quotes)

**Comment by jjzmajic** [comment]
It is for me

**Comment by jixiuf** [comment]
Wired.  it doesn' work for me 

```
zsh 5.3 (x86_64-apple-darwin18.0)
```
does the single quotes version work for you with `setopt prompt_subst`
```
function vterm_printf(){
    if [ -n "$TMUX" ]; then
        # tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}
setopt prompt_subst
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'

```

**Comment by jjzmajic** [comment]
Strange. It does, but only the directory tracking. I'll have to sit down and properly debug this with an empty zshrc.  What I have is working for me, but I'd rather find a generic solution that works for everyone

**Comment by jjzmajic** [comment]
Ok, just checked this with a vanilla zshrc. @jixiuf was right, this is the only snippet that works reagardless of what i throw at it (except starship prompt):
```zsh
vterm-printf() {
    if [[ -n "$TMUX" ]]; then
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [[ "${TERM%%-*}" = "screen" ]]; then
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    alias clear='vterm-printf "51;Evterm-clear-scrollback";tput clear'
fi
setopt promptsubst
vterm-prompt-end() { vterm-printf "51;A$(whoami)@$(hostname):$(pwd)"; }
PROMPT=$PROMPT'%{$(vterm-prompt-end)%}'
```
For starship prompt, my original snippet works, but only sometimes. I'll read through it's code later, but for now the original code should be restored **with** the addition of `setopt promptsubst`.

**Comment by zallison** [comment]
A lot of the internals of vterm--get-prompt-point and friends have been rewritten with #281 

Do you still experience these problems on the latest master?

**Comment by jjzmajic** [comment]
Just checked. Only the starship problem persists, but I suspect that's an issue on their side of things. I think this can be closed.

**Comment by zallison** [comment]
I understand, I have a problem with my prompt package and directory tracking to.

Maybe the regex version will work with starship? (adjust the regexp as needed)  That's what I'm using until I can patch my prompt package to work and send it upstream.

      (setq vterm-use-vterm-prompt nil
               term-prompt-regexp "[#$] ")

**Comment by c4710n** [comment]
Up to 2022, starship supports [custom pre-prompt and pre-execution commands](https://starship.rs/advanced-config/#custom-pre-prompt-and-pre-execution-commands-in-bash).

For Bash, you can use following line to make directory tracking work:
```
starship_precmd_user_func="vterm_prompt_end"
```
