### ISSUE TITLE
M-> binding

### ISSUE THREAD

**Issue by gahag** [akermu/emacs-libvterm#272]
I would like to be able to use M-> just like in bash. It goes to the end of the history. How can I bind that in vterm?

**Comment by jixiuf** [comment]
```
(define-key vterm-mode-map (kbd "M-<")             #'vterm--self-insert)
(define-key vterm-mode-map (kbd "M->")             #'vterm--self-insert)
```
Does this work for you .

**Comment by gahag** [comment]
Worked like a charm.

**Comment by jixiuf** [comment]
d93e1e8cb305f49865af6922e51e739d7eddef20  should fix this .
