### ISSUE TITLE
Yanking from counsel-yank-pop doesn't work

### ISSUE THREAD

**Issue by patrickt** [akermu/emacs-libvterm#277]
Firstly, _thank you_ for this package: it's the only Emacs terminal package that performs well enough with fish-shell, and it's really changed how I work. I owe you a great debt of thanks.

On the whole, the package works well, but I've noticed that, when using `ivy` + `counsel`, pasting text via `counsel-yank-pop` doesn't work: the selection dialog comes up as normal, but no action is performed when hitting Enter.

I'm planning to dig into this myself, but I wanted to leave this issue in case anyone else is encountering this.

**Comment by Sbozzolo** [comment]
The problem is that counsel-yank uses yank-pop instead of vterm-yank-pop. A possible solution is to define a new yank-pop function that knows what to do in vterm buffers. Pseudocode would be:
```emacs-lisp
(defun my-yank-pop ()
  (if (equal major-mode 'vterm-mode)
      (vterm-yank-pop)
    (yank-pop)))
``` 
Then `(setq 'yank-pop 'my-yank-pop)`. This is untested, pseudocode, but it may lead to a working workaround.

**Comment by jixiuf** [comment]
try 
```
(defun vterm-counsel-yank-pop-action (orig-fun &rest args)
  (if (equal major-mode 'vterm-mode)
      (let ((inhibit-read-only t)
            (yank-undo-function #'(lambda(_start _end) (vterm-undo))))
        (cl-letf (((symbol-function 'insert-for-yank)
               #'(lambda(str) (vterm-send-string str t))))
            (apply orig-fun args)))
    (apply orig-fun args)))

(advice-add 'counsel-yank-pop-action :around #'vterm-counsel-yank-pop-action)

```

**Comment by patrickt** [comment]
Thank you, @jixiuf! This works perfectly.
