### ISSUE TITLE
Autoloading file .../vterm.elc failed to define function vterm

### ISSUE THREAD

**Issue by vozhyk-** [akermu/emacs-libvterm#291]
I've installed `libvterm` on my Gentoo system:
```
% equery l libvterm
 * Searching for libvterm ...
[IP-] [  ] dev-libs/libvterm-0.1.2:0
```

I then installed `vterm` from `melpa`.
When I try to run it with `M-x vterm`, compilation succeeds, but an error is returned:
```
helm-M-x: Autoloading file /home/vozhyk/.emacs.d/elpa/vterm-20200407.1519/vterm.elc failed to define function vterm
```

I run an Emacs built from a fork with Wayland support, commit https://github.com/masm11/emacs/commit/4450385787d2686ca3a93bc81337b4315993e2e5 .
```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-04-10
```

**Comment by condy0919** [comment]
Same issue.

Deleting the `vterm.elc` solved

**Comment by vozhyk-** [comment]
Thanks, deleting `vterm.elc` worked around this.

I've noticed that there's a new `20200411.259` release on `melpa`. If I upgrade to it, it works fine, but, if I uninstall it and then install the new version, I get the same error:
```
helm-M-x: Autoloading file /home/vozhyk/.emacs.d/elpa/vterm-20200411.259/vterm.elc failed to define function vterm
```
Running `M-x byte-recompile-file` on `~/.emacs.d/elpa/vterm-20200411.259/vterm.el` doesn't help; I have to remove the compiled file for it to work.

**Comment by condy0919** [comment]
Changing `byte-recompile-file` to `byte-force-recompile` may help.

**Comment by Sbozzolo** [comment]
I have the same problem when I use the MELPA version. If you inspect the `vterm.elc`, you'll see that it is truncated:
``` emacs-lisp
;ELC\0\0\0
;;; Compiled
;;; in Emacs version 26.3
;;; with all optimizations.

;;; This file uses dynamic docstrings, first added in Emacs 19.29.

;;; This file does not contain utf-8 non-ASCII characters,
;;; and so can be loaded in Emacs versions earlier than 23.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(byte-code "\204\0\301\302!\210\303\304\305\306#\204\0\303\307!\210\310 \210\303\304!\210\305\207" [module-file-suffix error "VTerm needs module support. Please compile your Emacs\n  with the --with-modules option!" require vterm-module nil t vterm-module-make vterm-module-compile] 4)

I think something goes wrong with:
```emacs-lisp
(eval-and-compile
  (unless (require 'vterm-module nil t)
    (require 'vterm-module-make)
    (vterm-module-compile)
    (require 'vterm-module)))
```
Not sure exactly what/how to fix yet.

**Comment by bqv** [comment]
Same issue. Hard to recompile because nixos. What caused this?

**Comment by Sbozzolo** [comment]
There is some issue with the byte-compilation. With #295, I implemented a workaround that fixes the problem by moving the compilation of vterm after the byte-compilation of `vterm.el`. In the meantime, I also merged `vterm-module-make` with `vterm`. There is no real reason to have two files, and merging them silence some byte-compiler warnings.
