### ISSUE TITLE
Just stop working after updating

### ISSUE THREAD

**Issue by ram535** [akermu/emacs-libvterm#297]
Vterm just stop working after update.
I use `straight`. So after `straight-pull-all` like I normally do to update my packages, it stop working.
When I do `M-x vterm`, I get this:
![image](https://user-images.githubusercontent.com/9011002/79278590-d55fb180-7e60-11ea-9a62-0d7f404d56d8.png)

**Comment by Sbozzolo** [comment]
Try deleting the package and reinstalling it? We just changed something to improve the compatibility with straight.

**Comment by ram535** [comment]
I delete everything. And when I installed it again. There is a `vterm` directory in `~/.emacs.d/straight/build/vterm/` but there is not `vterm` directory in `~/.emacs.d/straight/repos/`.

**Comment by Sbozzolo** [comment]
Thanks. Unfortunately, I am not familiar with `straight.el`. We will need help on their side to fix this.

**Comment by drot** [comment]
Keep in mind the repository name is `emacs-libvterm` so you will find your directory in `~/.emacs.d/straight/repos/emacs-libvterm`, also make sure you're testing with the `straight` development branch.

**Comment by raxod502** [comment]
@ram535 If it's not working for you, you should check:

* the Git revision of `repos/straight.el`
* the Git revision of `repos/emacs-libvterm`
* the Git revision of `repos/melpa`
* what happens if you delete the entire `build` directory and `build-cache.el` and restart Emacs, forcing a clean compilation of everything

**Comment by ram535** [comment]
It works now. Thanks.
As suggested I:

- deleted `~/.emacs.d/straight/build-cache.el`
- deleted `~/.emacs.d/straight/repos/emacs-libvterm`
- deleted `~/.emacs.d/straight/build/vterm`
- added `(setq straight-repository-branch "develop")` to  `~/.emacs.d/init.el`

Final configuration.
```
(defvar bootstrap-version)
(setq straight-repository-branch "develop")
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)

(use-package vterm)
```
