### ISSUE TITLE
The sequence 'M-x vterm M-x vterm-mode M-x vterm' causes emacs to crash with SIGSEGV

### ISSUE THREAD

**Issue by iwpiv** [akermu/emacs-libvterm#298]
Confirmed to crash with vanilla Emacs, Version: 26.3, fedora 30

**Comment by Sbozzolo** [comment]
Interesting. You can crash (vanilla) Emacs just by opening a new vterm buffer and switching to fundamental mode.

We need to fix this.

**Comment by Sbozzolo** [comment]
#299 will prevent users from changing major-mode, so this problem should be fixed.
