### ISSUE TITLE
Syntax error in vterm--at-prompt-p

### ISSUE THREAD

**Issue by laurynas-biveinis** [akermu/emacs-libvterm#309]
Today's MELPA update produces

vterm.el:1117:3:Warning: value returned from (= (point) (or
    (vterm--get-prompt-point) 0)) is unused
vterm.el:1117:47:Error: Invalid read syntax: ")"

The defun looks like it has copy-paste error in it:
```
(defun vterm--at-prompt-p ()
  (= (point) (vterm--get-prompt-point)))
  "Return t if the cursor position is at shell prompt."
  (= (point) (or (vterm--get-prompt-point) 0)))
```

**Comment by Sbozzolo** [comment]
Ops, that slipped in. Will fix in a second.

**Comment by Sbozzolo** [comment]
Thanks, this should be fixed as soon as MELPA rebuilds `vterm`.
