### ISSUE TITLE
Quickly pressing f and then other key causes double press of second key

### ISSUE THREAD

**Issue by RubioJr9** [akermu/emacs-libvterm#311]
When I press the f key, and then immediately press another key, instead of an f, it is replaced by the second key.

If I press 'fe' and the time between f and e is very small, it prints 'ee'.

I've had this issue on all 3 of my machines which are running Arch Linux. I have tried this with Spacemacs on Emacs 26.3, 27, and 28.

**Comment by Sbozzolo** [comment]
Is this with evil mode? Is it only the the key f?

I tested with Spacemacs, Emacs 27.0.90, `holy-mode` and I have no problems.

**Comment by RubioJr9** [comment]
Yes, I'm using evil mode

**Comment by RubioJr9** [comment]
It looks like there was already an issue(#247) for it but it didn't come up in my first search. Sorry for the trouble.
