### ISSUE TITLE
Problem when using vterm_cmd to open a file with long file name.

### ISSUE THREAD

**Issue by BlindingDark** [akermu/emacs-libvterm#314]
![Peek 2020-05-02 13-34](https://user-images.githubusercontent.com/13600799/80856473-f0159100-8c7c-11ea-8200-0f97d7df00a6.gif)

```
Error running timer ‘vterm--delayed-redraw’: (end-of-file)
```
If set delay time to nil, it will open normally.

Maybe #283 it ’s a related issue

**Comment by Sbozzolo** [comment]
Thanks. The internals of the `vterm-module` work fine. If you try with
```
vterm_printf "51;Emessage ""HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"
```
The string is correctly printed. The bug lies in `vterm_cmd`, I am not entirely sure what is the reason, but this is a working version:
```bash
vterm_cmd() {
    s=$(while [ $# -gt 0 ]; do
            printf '"%s" ' "$(printf "%s" "$1" | sed -e 's|\\|\\\\|g' -e 's|"|\\"|g')"
            shift
        done)
    vterm_printf "51;E$s"
}
```

I will polish and update the readme with a fixed and tested version.

**Comment by Sbozzolo** [comment]
Can you please check the new suggested code in #335?

**Comment by BlindingDark** [comment]
> Can you please check the new suggested code in #335?

🤒 I was hospitalized and I will reply to you in a few days.

**Comment by BlindingDark** [comment]
> Can you please check the new suggested code in #335?

Works fine after using the new code
