### ISSUE TITLE
vterm-mode: Wrong number of arguments: #<module function Fvterm_new from /home/r/.emacs.d/elpa/vterm-20191218.202/vterm-module.so>, 6

### ISSUE THREAD

**Issue by runekaagaard** [akermu/emacs-libvterm#315]
Hi

Thx for this package. After installing the latest version of vterm on Ubuntu 19.10. I get the following error when invoking M-x vterm:

```
vterm-mode: Wrong number of arguments: #<module function Fvterm_new from /home/r/.emacs.d/elpa/vterm-20191218.202/vterm-module.so>, 6
```

Help!?

**Comment by Sbozzolo** [comment]
It looks like you are using an old version of vterm, or your Emacs is loading an old version of vterm. I recommend cleaning all the vterm stray installations and install the package again from scratch.

**Comment by runekaagaard** [comment]
Hi. Even though I deleted the folder, ran package-refresh-contents and reinstalled, I still got the old version. Now weirdly after upgrading all packages on the package-list I got the latest, and it works super. THX!
