### ISSUE TITLE
Can't build on Fedora 32

### ISSUE THREAD

**Issue by andreyorst** [akermu/emacs-libvterm#317]
I have [toolbox](https://github.com/containers/toolbox) container with Fedora 31 and latest master successfully builds, but on Fedora 32 I get many errors. [log.txt](https://github.com/akermu/emacs-libvterm/files/4585644/log.txt). It seems it happens on linking phase, and in Fedora 31 `ld -v` shows me `GNU ld version 2.32-31.fc31` and in Fedora 32 it is `GNU ld version 2.34-2.fc32`. If I can provide any other info feel free to ask

**Comment by aldoridhoni** [comment]
Follow this https://github.com/akermu/emacs-libvterm/issues/296#issuecomment-623412656

**Comment by andreyorst** [comment]
Thanks. Closing as duplicate
