### ISSUE TITLE
Mimic vi mode in bash?

### ISSUE THREAD

**Issue by pRot0ta1p** [akermu/emacs-libvterm#324]
This is probably the last missing feature for evil-mode user....

Let me explain what I mean:

Put `set -o vi` in `~/.bashrc`, or put ` set editing-mode vi` in `~/.inputrc` will enable vi mode in bash, 
which means:
1. user can have a "vim-like normal mode" and use vim-keys to edit the command input
2. user can re-bind keys for example: `j/k` to `history-search-backward/forward` to use `j/k` instead of 
    arrow key to navigate bash history. 

Now emacs-libvterm already have 2. because you can bind keys in evil-normal-state to send arrow 
keys to the terminal, for example bind `J/K` to `vterm-send-up/down`.

Currently, vterm buffer is read-only in evil-normal-state, which is inconvenient for editing long command input, so maybe a minor mode for editing the current active command input in evil-normal state? 
Also, in vterm buffer it will ignore the cursor position in evil-normal-state, if I switch back to insert-state from normal-state then start to typing, the cursor will jump back to where I left intert-mode.

**Comment by Sbozzolo** [comment]
> Currently, vterm buffer is read-only in evil-normal-state, which is inconvenient for editing long command input, so maybe a minor mode for editing the current active command input in evil-normal state?

I wrote something along these lines in https://github.com/Sbozzolo/vterm-extra. There is a command to edit the current command in another temporary buffer, which you can freely edit in any way you want. I agree, It would be nice to a minor more to enable evil editing directly in vterm buffers. but at the moment best we can do is defer this to the shell. 

> Also, in vterm buffer it will ignore the cursor position in evil-normal-state, if I switch back to insert-state from normal-state then start to typing, the cursor will jump back to where I left intert-mode.

You can configure you system to automatically switch to vterm-copy-mode when you are not in insert-mode.

**Comment by pRot0ta1p** [comment]
That is not way I exactly want, but it get the job done. Thanks!
