### ISSUE TITLE
`f` doubles the following key I input

### ISSUE THREAD

**Issue by kenkangxgwe** [akermu/emacs-libvterm#330]
I've experienced this on two machines when using vterm. When I input `f` quickly followed by another character, say `i`, it will show up as `ii` instead of `fi` in the console. I didn't reproduce this in other modes or terms. It seems only to occur in vterm.

**Comment by Sbozzolo** [comment]
See #247

**Comment by kenkangxgwe** [comment]
Thanks for redirecting the issue
