### ISSUE TITLE
Directory and Prompt tracking + evil-mode

### ISSUE THREAD

**Issue by fbob** [akermu/emacs-libvterm#331]
I'm on Doom with Emacs 26.3.

It looks like there is a bug with the use of evil-mode regarding Directory and Prompt tracking.
When in evil normal-state the cursor changes its position and goes one char back (that's the right behavior).
But then the current directory and prompt tracking does not work correctly because the cursor is now next to the prompt string and a find-file will take this string as the path.

Screenshots below will explain this far better than me:

In evil insert state
![vterm_evil_insert_mode](https://user-images.githubusercontent.com/8211124/82153148-0e2ae600-9866-11ea-9aa6-912b6b92c1eb.png)

In evil normal state
![vterm_evil_normal_mode](https://user-images.githubusercontent.com/8211124/82153151-1551f400-9866-11ea-92d3-48652436a980.png)

Try to open a file
![vterm_find_file](https://user-images.githubusercontent.com/8211124/82153156-1a16a800-9866-11ea-8321-8cc9feef0ba4.png)

Note that Emacs is smart enough to try to send an email ... lovely Emacs :)

**Comment by leoalekseyev** [comment]
@fbob have you tried evil-collection (configured via (evil +everywhere) in doom init.el)? I believe it has a fix for exactly this.

**Comment by Sbozzolo** [comment]
Thanks, @leoalekseyev. It appears that the relevant function is
```emacs-lisp
(defun evil-collection-vterm-escape-stay ()
  "Go back to normal state but don't move cursor backwards.
Moving cursor backwards is the default vim behavior but
it is not appropriate in some cases like terminals."
  (setq-local evil-move-cursor-back nil))
```
And then
```emacs-lisp
  (add-hook 'vterm-mode-hook #'evil-collection-vterm-escape-stay)
```

**Comment by fbob** [comment]
Many thanks, I'll try it :)

**Comment by fbob** [comment]
Sorry for the late feedback, it looks like it doesn't work for me:
I've got evil-collection configured via (evil +everywhere) in my init.el but no effect at all.
I've tried to force the (add-hook 'vterm-mode-hook #'evil-collection-vterm-escape-stay) but same pb.
