### ISSUE TITLE
Error in PROMPT_COMMAND value for setting term title?

### ISSUE THREAD

**Issue by edgar-vincent** [akermu/emacs-libvterm#334]
Hello,

In the main README file's [vterm-buffer-name-string section](https://github.com/akermu/emacs-libvterm/blob/master/README.md#vterm-buffer-name-string), I think there is an error in the value PROMPT_COMMAND should be set to for bash. 
 Following the [Bash manual](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Controlling-the-Prompt), it seems that PROMPT_COMMAND should be set to an ordinary shell command while PS1 may contain special escapes characters such as \h.

On my Arch install (with bash), the special characters provided in the README weren't escaped However, this worked: `PROMPT_COMMAND='printf "\033]0;%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'`

Thanks a lot for your work!

**Comment by Sbozzolo** [comment]
I have a one-liner test `.bashrc`: `PROMPT_COMMAND='echo -ne "\033]0;\h:\w\007"'` and this works on two systems with bash 4 and 5 respectively. Can you try this too?

**Comment by edgar-vincent** [comment]
It doesn't work here. "%s" is displayed as `\h: \w` when I use your example .bashrc
I'm using bash 5.0.16 and emacs-git.

**Comment by Sbozzolo** [comment]
I accidentally found a server in which I could reproduce this problem. I am not sure what is going on exactly, but I think that avoiding to use \h and \w leads to a more robust configuration, so I will fix this.

**Comment by edgar-vincent** [comment]
Thanks a lot!
