### ISSUE TITLE
comint-input-ring usage

### ISSUE THREAD

**Issue by azzamsa** [akermu/emacs-libvterm#336]
Can we use comint in vterm buffer?

I tried `helm-comint-input-ring` in vterm buffer it doesn't work. But it works in other e/shell/ansi-term buffer.

Thank you for vterm.

**Comment by brotzeit** [comment]
vterm currently doesn't fill `helm-comint-input-ring`.

I'm using a custom helm source on a file and modified `vterm-send-return` so it appends the input to this file.

```elisp
(setq term-prompt-regexp "^[^#$%>\\n]*[#$%>] *")
(defvar vterm-history "path/to/vterm_history")

(defun vterm-send-return ()
  "Send `C-m' to the libvterm."
  (interactive)
  (when vterm--term
    (let* ((beg (vterm--get-prompt-point))
          (end (vterm--get-end-of-line))
          (string (buffer-substring-no-properties beg end))
          (file vterm-history))
      (write-region (concat string "\n") nil file t 0))
    (if (vterm--get-icrnl vterm--term)
        (process-send-string vterm--process "\C-j")
      (process-send-string vterm--process "\C-m"))))


(defun helm-vterm-history ()
  (interactive)
  (helm :sources (helm-build-in-file-source
                     "vterm history" vterm-history
                   :action (lambda (candidate)
                             (vterm-send-string candidate)))
        :buffer "*vterm history*"))
```

**Comment by azzamsa** [comment]
Great!. It works like a charm.

Thank you for vterm.

**Comment by azzamsa** [comment]
@brotzeit I've added the check to ignore empty string so that it doesn't get written into the history file.

![image](https://user-images.githubusercontent.com/17734314/83579527-af52b580-a563-11ea-9e96-fc45f78ce83a.png)

**Comment by azzamsa** [comment]
I've some problem with the code:

1. duplicate entries
2. appending empty string.

So here is my updated version:

*I'll updated the code here if I find a bug*

```emacs-lisp
  (setq term-prompt-regexp "^[^#$%>\\n]*[#$%>] *")
  (setq vterm-history '())
  (setq vterm-history-file
        (expand-file-name "vterm-history" aza-savefile-dir))

  (add-hook 'kill-emacs-hook
            (lambda ()
              (write-region (string-join vterm-history "\n") nil vterm-history-file)))

  (if (not vterm-history)
      (setq vterm-history (s-split "\n" (f-read vterm-history-file))))

  (defun vterm-send-return ()
    "Send `C-m' to the libvterm."
    (interactive)
    (when vterm--term
      (let* ((beg (vterm--get-prompt-point))
             (end (vterm--get-end-of-line))
             (history (buffer-substring-no-properties beg end)))
        (if (not (string= history ""))
            (add-to-list 'vterm-history history)))

      ;; default part from vterm.el
      (if (vterm--get-icrnl vterm--term)
          (process-send-string vterm--process "\C-j")
        (process-send-string vterm--process "\C-m"))))

  (defun helm-vterm-history ()
    (interactive)
    (let ((histories vterm-history))
      (helm :sources `((name . "vterm history")
                       (candidates . histories)
                       (action . (lambda (candidate)
                                   (vterm-send-string candidate))))
            :candidate-number-limit 10000))))

```

**Comment by brotzeit** [comment]
Instead of checking if the string is empty, I don't append strings that are too long. For example when you use return on the output of systemctl status, you get the whole output appended to your history every time you press enter. 

Maybe somebody finds a better way to handle this. It's really convenient to have a global history.

**Comment by azzamsa** [comment]
> Instead of checking if the string is empty, I don't append strings that are too long. For example when you use return on the output of systemctl status, you get the whole output appended to your history every time you press enter.

I can't reproduce this behavior with the code above

**Comment by brotzeit** [comment]
Oh then I have to try it :+1:

**Comment by theottm** [comment]
I also looked for something like that. I'm using the completing-read ecosystem though. I implemented something this morning.

I am mostly interested in the history of zsh, so I ended up reading the zsh history directly. Duplicates are already handled by zsh so this is nice. Here is the code maybe it helps someone in the future:
```el
;; this function is from http://xahlee.info/emacs/emacs/elisp_read_file_content.html
(defun read-lines-from-files (filePath)
  "Return a list of lines of a file at filePath."
  (with-temp-buffer
    (insert-file-contents filePath)
    (split-string (buffer-string) "\n" t)))

(defun vterm-history (histfile)
  (vterm-send-string (completing-read "Commands: " (read-lines-from-files histfile)) t))

(defun vterm-history-zsh ()
  (interactive)
  (vterm-history "~/.config/zsh/.histfile"))

(define-key vterm-mode-map (kbd "C-c C-q") 'vterm-history-zsh)
```
As you see this can be easily adapted to read from any history file, even from a combination of history files if needed.

It probably also relates to https://github.com/minad/consult/issues/121
