### ISSUE TITLE
emacs-libvterm crashes emacs immediately

### ISSUE THREAD

**Issue by leoalekseyev** [akermu/emacs-libvterm#337]
emacs-libvterm that ships with the current version of doom emacs (422ffe0) crashes emacs when trying to run vterm e.g. via `(vterm)`.  From syslog I can see that it crashes here:
```
/home/leo/.emacs.d.doom/.local/straight/build/vterm/vterm-module.so(emacs_module_init+0x3a)[0x7f214a84ca4a]
```
Running under emacs 28.0.50, Ubuntu 18.04

**Comment by Sbozzolo** [comment]
This looks like #185. Have you tried compiling Emacs from sources?

**Comment by leoalekseyev** [comment]
Ugh, I completely missed that part of the README.  Here are instructions on how to compile from source under Ubuntu 18.04, if anyone is facing the same issue:
```
sudo apt-get install build-essential automake texinfo libjpeg-dev libncurses5-dev
sudo apt-get install libtiff5-dev libgif-dev libpng-dev libxpm-dev libgtk-3-dev libgnutls28-dev libasound2-dev
./autogen.sh
./configure --with-sound=alsa --without-gconf --with-mailutils --with-modules --prefix=/usr/local
make
sudo make install
```
