### ISSUE TITLE
How to get tmux like behaviour in vterm?

### ISSUE THREAD

**Issue by SreenivasVRao** [akermu/emacs-libvterm#339]
Hi, I'm trying to get tmux to work within vterm, but not sure if it is supported. An alternative solution I would like is to be able to open another vterm with the same directory (especially after ssh into a remote host).

For example:
ssh to host
open directory
<press shortcut> 
open another vterm with same host, and directory in adjacent pane.

**Comment by jixiuf** [comment]
try https://github.com/jixiuf/vterm-toggle
`vterm-toggle-cd`
With `C-u`   `vterm-toggle-cd` would open another vterm with same host, and directory. (not in adjacent pane)

```
(defun vterm-toggle-other-window()
  (interactive)
  (let ((vterm-toggle-fullscreen-p nil)
      (display-buffer-alist '((".*" (display-buffer-pop-up-window)))))
    (vterm-toggle-cd-show)))

```

`vterm-toggle-other-window` should opening another vterm with same host, and directory in adjacent pane.

**Comment by leoalekseyev** [comment]
@SreenivasVRao tmux is working fine within vterm for me just FYI

**Comment by SreenivasVRao** [comment]
Hi Leo,
That's great to hear. Thanks to you, I found I had to do two very simple
things to get this to work:
1. Switch tmux back to default "C-b" prefix instead of "C-x"
2. Restart tmux server.

This is incredible though! I've badly wanted an efficient workflow with
tmux behaviour in emacs. Thanks folks for this package!
Best,
Sreenivas

**Comment by boykov** [comment]
@betaprior Can you scroll up inside tmux inside vterm in your workflow?

**Comment by fakegermano** [comment]
@boykov just FYI, you prob know this, and for any other people that search for this in the future, you can scroll up inside tmux within vterm by using tmux's copy mode `prefix + [`
