### ISSUE TITLE
(vterm--get-pwd) segfaults emacs when run from a non-vterm buffer

### ISSUE THREAD

**Issue by exp2ipi** [akermu/emacs-libvterm#340]
When doing M-x eval `(vterm--get-pwd)` while visiting a non-vterm buffer, emacs segfaults inside `vterm-module.so(Fvterm_get_pwd+0x21)[0x7fddf9d110d1]`.  While this is probably not an intended usage, it is reasonable to expect a user to run this while debugging or setting up directory tracking, and having a segfault is undesirable.

**Comment by tpapp** [comment]
This may cause #316. See my comment for a workaround there.

**Comment by Sbozzolo** [comment]
Fixed with #356
