### ISSUE TITLE
feature request: support for OSC52 code for tmux copy integration

### ISSUE THREAD

**Issue by betaprior** [akermu/emacs-libvterm#343]
I find that when used with Tmux, copying text that does not fit inside the tmux window is impossible. However, this can be solved by introducing support for OSC52 code, which is how tmux is able to share its copy buffer with iTerm2.

**Comment by jixiuf** [comment]
after #402 is merged ,this feature should b supported .
with
`(setq vterm-module-cmake-args "-DUSE_SYSTEM_LIBVTERM=no")`
