### ISSUE TITLE
"1;5u" sent to vterm in evil-normal-state

### ISSUE THREAD

**Issue by kenkangxgwe** [akermu/emacs-libvterm#346]
After entered the normal state in evil-mode, pressing <kbd>Esc</kbd> results in printing `1;5u` in terminal.

**Comment by Sbozzolo** [comment]
I think [evil-collection](https://github.com/emacs-evil/evil-collection) has a fix for this.
If you don't want to use it, you have to bind `Esc` to `vterm-send-escape`, which you can find in #347

**Comment by kenkangxgwe** [comment]
Thanks, fixed.
