### ISSUE TITLE
Question about mode.

### ISSUE THREAD

**Issue by Ergus** [akermu/emacs-libvterm#348]
Hi: 
This is not actually an issue but a question. Why vterm-mode does not inherit from term-mode? I know it is completely independent, but I thought that for consistency there should be some relation between them and all the shell modes in emacs must inherit from that mode. Are there any functionality, issue in term-mode to create the derived mode for vterm from it?

**Comment by Sbozzolo** [comment]
vterm and term have very different inner workings. `term-mode` is derived from `fundamental-mode`, defines a bunch of local variables that we don't use in `vterm` and invokes functions that are not defined in `vterm`. Besides, I wouldn't say that `term-mode` is the generic terminal mode in Emacs. A more conceptually appropriate mode would be `comint-mode`, if you want.
