### ISSUE TITLE
combining accents do not show in vterm buffer

### ISSUE THREAD

**Issue by tpapp** [akermu/emacs-libvterm#355]
How to replicate: 

1. open a new vterm buffer, 
2. eval `(vterm-send-string "k\u0302")`
3. only the character `k` will be shown.
4. when copying out the relevant portion with `vterm-copy-mode`, `k̂` ends up in the kill ring so it is in the buffer, just not shown.

Other buffers (eg `*scratch*` with `(insert "k\u0302")`) show the accent fine (with the same font, Iosevka).

Emacs 26.3, Ubuntu 20.04, latest emacs-libvterm from MELPA.

**Comment by dertuxmalwieder** [comment]
Potentially related: German umlauts don’t show either, like ü and ä. They work in all other buffers.

**Comment by jixiuf** [comment]
should be fixed after #473  is merged.

**Comment by dertuxmalwieder** [comment]
Confirmed!
