### ISSUE TITLE
unsigned vterm-module.so on macOS

### ISSUE THREAD

**Issue by fpatz** [akermu/emacs-libvterm#359]
macOS Catalina. Obviously, there are no provisions for the ```vterm-module.so``` to be code signed. This means, the module cannot be loaded:

```
Error (use-package): vterm/:catch: Module could not be opened: "~/.emacs.d/elpa/vterm-20200613.1457/vterm-module.so",
"dlopen(~/.emacs.d/elpa/vterm-20200613.1457/vterm-module.so, 1): no suitable image found.
Did find: /~/.emacs.d/elpa/vterm-20200613.1457/vterm-module.so: code signature in
(~/.emacs.d/elpa/vterm-20200613.1457/vterm-module.so) not valid for use in process
using Library Validation: mapped file has no cdhash, completely unsigned?
Code has to be at least ad-hoc signed."
```

Has someone found a workaround for this?

UPDATE: using an Emacs build from https://emacsformacosx.com/ it "just works" with an unsigned ```vterm-module.so```. So this seems to be a problem with the Homebrew cask from railwaycat I was using (https://github.com/railwaycat/homebrew-emacsmacport).

**Comment by fpatz** [comment]
SOLVED: it was simply that my railwaycat Emacs wasn't up to date. Just do ```brew cask upgrade emacs-mac``` to fix. Closing.

**Comment by ameliesc** [comment]
Hi I am running to a similar issue it seems but I have the " https://emacsformacosx.com/" build. 

This is the error I am getting:
`/emacs-libvterm/vterm-module.so' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))"`

Any ideas on what the issue is here? I upgraded brew, cmake and am using emacs 27.2

**Comment by fpatz** [comment]
Honestly, I don't know . My Emacs binary is signed, while `vterm-module.so` is not, and `vterm` just works. The error message comes from macOS' library validation feature. I am still using Yamamoto's `emacs-mac` port (meanwhile at 28.1.), which is pretty good. So you might want to give that a try ...
