### ISSUE TITLE
How to automatically execute term commands on new terminal?

### ISSUE THREAD

**Issue by jsigman** [akermu/emacs-libvterm#360]
For example, I want to automatically execute path-specific commands to activate a python `venv` when I start a terminal. Is there simple elisp code to, say, automatically execute `echo test` upon opening a vterm instance?

Thanks

**Comment by Sbozzolo** [comment]
You can try with 
``` elisp
(add-hook 'vterm-mode-hook (lambda () (vterm-send-string "echo test")))
```

**Comment by jsigman** [comment]
Thank!
