### ISSUE TITLE
Cannot find correct build directory in native-comp emacs

### ISSUE THREAD

**Issue by blahgeek** [akermu/emacs-libvterm#363]
I'm using `native-comp` branch of emacs (https://akrl.sdf.org/gccemacs.html) which offers greater elisp performance. It will compile all *.el files to *.eln files to a seperate directory.

Since `vterm-module-compile` will locate the source directory using `(locate-library "vterm")`, it cannot find the correct directory in native-comp emacs. Normally the return value is something like `~/.emacs.d/elpa/vterm-20200707.1655`, but with native-comp emacs, it's like `~/.emacs.d/elpa/vterm-20200707.1655/eln-x86_64-pc-linux-gnu-6d32bf10d46bb4cc`.

My current workaround is manually compiling in the correct directory.

**Comment by mnewt** [comment]
PR https://github.com/akermu/emacs-libvterm/pull/373 resolves the issue for me. Can anyone else confirm?

**Comment by blahgeek** [comment]
I can confirm #373 fixes this, thanks for you work

**Comment by Sbozzolo** [comment]
Fixed with #373
