### ISSUE TITLE
How to modify vterm-mode-map?

### ISSUE THREAD

**Issue by stugots** [akermu/emacs-libvterm#370]
Hi, I didn't see a venue listed for asking questions.  If there's a more appropriate place to ask this, I apologize, please let me know and I'll ask there.

I use [ace-window](https://github.com/abo-abo/ace-window), and my init file does a `(global-set-key (kbd "M-p") 'ace-window)`.

I want to be able to use `M-p` while in my vterm window.  So I tried doing this:

```
(define-key
  (lookup-key (symbol-value 'vterm-mode-map) (kbd "ESC"))
  (kbd "p")
  nil
  )
```
This leaves the `vterm-map-mode` entry thus:
```
     (113 . vterm-send-M-q)
     (112)
     (110 . vterm-send-M-n)
```

I thought setting a keymap entry to `nil` would delete it, but this entry remains.  And `M-p` still doesn't work.

I then tried defining `M-p` to be `'ace-window.`  The results looked correct, but typing `M-p`in the vterm window still doesn't call `ace-window.`

How do I tell vterm to not send the `M-p` to the terminal?

**Comment by Sbozzolo** [comment]
Have you tried
```emacs-lisp
(define-key vterm-mode-map (kbd "M-p") nil)
```
?

**Comment by stugots** [comment]
@Sbozzolo Well that's easier.

But, it leaves `vterm-mode-map in the same condition with a `(112)` entry, and using `M-p` in the vterm window still doesn't work.  It looks like `M-p` is still being sent to the terminal.

**Comment by Sbozzolo** [comment]
I am trying to see what's wrong, and I noticed that `ace-window` doesn't display the numbers in vterm buffers.

Can you try calling `M-x ace-window` in a vterm buffer? 

I suspect that `M-p` is correctly bound to `ace-window`, but the problem is elsewhere.

**Comment by stugots** [comment]
Sorry for being a noob at this...

I typed `M-x` in the vterm window, and it displays `execute: `.  I then type `ace-window<return>` and nothing happens.

**Comment by Sbozzolo** [comment]
On my machine, if I have two windows, one of which is a vterm buffer, and I execute `ace-window`, the number is printed on the top left on the window that is not vterm. 

Another way to see, if I execute `ace-window` and press any key that is not a number I get the error "No such candidate" from `ace-window`. I can still switch windows, the problem is that the number is not printed on vterm buffers. 

Do you find something similar?

**Comment by stugots** [comment]
Nope...  

I'm using `emacsforosx.`

I reduced my .emacs file to:
```
;;; Package management.
(require 'package)
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org./packages/") t)

;; Declare use-package.  This is only needed once, near the top of the file.
(eval-when-compile
  ;; Following line is not needed if use-package.el is in ~/.emacs.d
  ;; (add-to-list 'load-path "<path where use-package is installed>")
  (require 'use-package))

;;; Select a window to switch to.
(use-package ace-window
  :config
  (global-set-key (kbd "M-p") 'ace-window))

;; emacs-vterm, a terminal that's better than the other terminals.
(use-package vterm
  :ensure t
  :config
  (setq vterm-max-scrollback 20000)

  ;; We want to use M-p in the vterm window.
  (define-key vterm-mode-map (kbd "M-p") nil)

  (global-set-key "\M-\S-T" 'vterm)
  )
```
In the non-vterm windows, `M-p` and `M-x ace-window` work fine.

In the vterm window, `M-x ace-window` sits there.  No red window numbers are displayed in the other windows.

<img width="453" alt="Screen Shot 2020-07-16 at 3 47 53 PM" src="https://user-images.githubusercontent.com/231148/87730137-ce0bb500-c77b-11ea-94e1-056d476c603b.png">

**Comment by Sbozzolo** [comment]
I just tried on a clean Emacs and I still find the behavior I described above. It looks like your shell is somehow swallowing the `M-x`.  `M-x` should be sent to Emacs, not the shell. 

Can you try `C-k M-x` in a vterm buffer and report the output?

**Comment by stugots** [comment]
<img width="423" alt="Screen Shot 2020-07-16 at 4 07 33 PM" src="https://user-images.githubusercontent.com/231148/87731092-79b60480-c77e-11ea-8db5-32a1ca2bac33.png">

**Comment by Sbozzolo** [comment]
Sorry, I meant `C-h k M-x`.

**Comment by stugots** [comment]
My shell is zshell, if that matters.

**Comment by stugots** [comment]
With `C-h k`, I get the minibuffer `Describe the following key...` prompt.

With escape, the minibuffer prompt disappears.  Up comes a help window sayingL
```
<escape> runs the command vterm--self-insert (found in vterm-mode-map), which is an interactive compiled Lisp function
in ‘vterm.el’.

It is bound to C-_, C-SPC, M->, M-<, C-c C-y, and many ordinary text characters.

(vterm--self-insert)

Send invoking key to libvterm.

[back]
```

With `x`, the x is sent to the terminal.

**Comment by Sbozzolo** [comment]
I see. I think this has to do with how macOS handle the META key. You are using `<escape>` in place of the META key, and in this case it doesn't work because `<escape>` is sent to the terminal. 

I know next to nothing about macOS, but I think normally people bind META to cmd or alt.

**Comment by stugots** [comment]
OK, thanks for investigating!  My muscle memory has using the Escape key ingrained since 1980 so I'm keeping that.  

I love your package, btw!

**Comment by Sbozzolo** [comment]
You can try unbinding `<escape>` as described above for `M-p`. Not sure if it would work.

**Comment by stugots** [comment]
nope, no good.  

Thanks again.  I'll leave it alone for now.

**Comment by stugots** [comment]
wait wait I was wrong OMG that worked

**Comment by stugots** [comment]
YOU ARE A GOD
