### ISSUE TITLE
bindkey -e in zsh breaks return/C^m/(vterm-send-return)

### ISSUE THREAD

**Issue by jaza-syed** [akermu/emacs-libvterm#371]
Vterm doesn't respond to me pressing the return key on my keyboard,`(vterm-send-return)` also does nothing. All other special keys seem to work fine (e.g. `C-a`). I'm using Doom Emacs on Fedora 31, with vterm at `422ffe02`,

**Comment by jaza-syed** [comment]
I tried with bash and zsh and it works, so it's likely a configuration issue with zsh.

**Comment by jaza-syed** [comment]
I investigated further and the issue was due to `bindkey -e` in my zshrc. `C-o` works for accepting commands, and if I am using another program in the shell (for example if start searching my command history with fzf using `C-r`) the return key works in this case. It also works fine if I use `bindkey -v`, so there is an odd interaction between the zle emacs keymap and vterm.

**Comment by Sbozzolo** [comment]
Can you reproduce this with a clean `vterm` and `zsh`? 

I tried opening `zsh`, executing `bindkeys -e`, and everything seems to work fine.

**Comment by jaza-syed** [comment]
I just tried with `emacs -q` and installing vterm with no `.zshrc` and it works fine, so it must be an additional issue with my config that's not `bindkey -e`. Not sure why I missed that the first time round.

**Comment by knu** [comment]
I was hit by this problem too and found out what was going on when I read `vterm-send-return`.  When you input RET, emacs-vterm sends ^J to the terminal if icrnl is on.  So, you need to bind ^J to `accept-line` in that case.
