### ISSUE TITLE
insert-char in vterm buffer failed

### ISSUE THREAD

**Issue by wpchou** [akermu/emacs-libvterm#374]
Calling insert-char in the vterm buffer failed when I was about to insert a unicode.

Message: `Buffer is read-only: #<buffer vterm>`

**Comment by Sbozzolo** [comment]
Inserting unicode characters doesn't work at the moment. See also https://github.com/akermu/emacs-libvterm/issues/355

**Comment by Sbozzolo** [comment]
The correct way to send a character is with `vterm-send-string`.
