### ISSUE TITLE
Default shell

### ISSUE THREAD

**Issue by renard** [akermu/emacs-libvterm#376]
I use vterm on MacOS which has defined zsh as default shell. I updated my default shell to bash using `chsh` and it works like a sharm when I use iTerm.

However using vterm lands me to zsh. Is there a way to change it to bash?

Thanks

**Comment by Sbozzolo** [comment]
Yes, there's a variable vterm-shell that you can customize.

**Comment by renard** [comment]
Yes that is it thanks.

And it would be better to fix the root variable `shell-file-name`.

Thanks for the hint.

**Comment by Sbozzolo** [comment]
`shell-file-name` should be equivalent to what we have right now, that is, we look at the value of the environment variable `SHELL`.

**Comment by renard** [comment]
Yes since `vterm-shell`  is set to `shell-file-name`if the later is set before it works.

However the `SHELL` env also has to be set as well.

For the record here is my setup

```elisp

  (cl-loop for file in '("/usr/local/bin/bash" "/bin/bash")
	   when (file-exists-p file)
	   do (progn
		(setq shell-file-name file)
		(cl-return)))
  (setenv "SHELL" shell-file-name)
```

**Comment by rien333** [comment]
@Sbozzolo I can confirm that changing the value of `vterm-shell` to `"bash"` opens the bash shell in new vterm instances, even though the default shell for my user is `fish`. 

So far, so good. However, if I'm tramping into another machine and then run e.g. `vterm-other-window` vterm does not seem to use the value in `vterm-shell`.  Is that intended behavior? 

I can also see this as something that is ideally fixed, but is a little complicated.
