### ISSUE TITLE
Alternative to directory tracking (bash)

### ISSUE THREAD

**Issue by ration** [akermu/emacs-libvterm#379]
Hi, 

I had some issues with the default directory tracking system. I use [bash-git-prompt](https://github.com/magicmonty/bash-git-prompt) and it throws it off and I didn't really want to start to fiddle with the detection regexps (or the prompt look&feel).

So I went another route for it, maybe someone else finds this useful as well:

Shell side, I set bash `PROMPT_COMMAND`:
```bash
vterm_set_directory() {
    vterm_cmd update-pwd "$PWD/"
}
PROMPT_COMMAND="$PROMPT_COMMAND;vterm_set_directory"
```

Emacs side, add `update-pwd` into the eval `vterm-eval-cmds` list:
```emacs-lisp
(use-package vterm
  :config
  (require 'vterm)
  (add-to-list 'vterm-eval-cmds '("update-pwd" (lambda (path) (setq default-directory path)))))
```

This way the current directory is synced regardless how the prompt looks.

**Comment by Sbozzolo** [comment]
Thanks, I adapted extended your solution so that it can work also on remote hosts and added it to the FAQ.
