### ISSUE TITLE
(vterm-beginning-of-line) doesn't work

### ISSUE THREAD

**Issue by archiif** [akermu/emacs-libvterm#386]
`vterm-beginning-of-line` doesn't do anything for me with the bash shell. I tried to use `beginning-of-line` too and it also doesn't work. 
Strangely enough the 'Home' key does bring me to the beginning of the line.
This weird quirk makes vterm-extra commands unusable.
I'm using Doom Emacs with evil-mode and evil-collection.

**Comment by Sbozzolo** [comment]
I checked and it works on vanilla emacs. It doesn't work on Doom Emacs and Spacemacs. I'll try to understand why.

**Comment by Sbozzolo** [comment]
I did some tests on Doom Emacs. If you evaluate the following line:
```emacs-lisp
(define-key vterm-mode-map (kbd "C-a") #'vterm-beginning-of-line)
```
You should find that `vterm-beginning-of-line` does work. Same result if you evaluate with `M-:` the expression. Notice, if you use `vterm-beginning-of-line` and you start typing, the cursor will be moved back to the end of the line! Same if you have a blinking cursor. 

In the case of Doom Emacs, if I type `M-x vterm-beginning-of-line`, that doesn't work. I am not sure why, but I don't know much about Doom Emacs. I think this should be reported to Doom Emacs.

**Comment by archiif** [comment]
I see, I'll report this issue to Doom. But basically the core issue is with (beginning-of-line) right? Since the vterm function is just using that.

**Comment by Sbozzolo** [comment]
No, the main function is `(goto-char)` . In my experimentation with Doom Emacs, I couldn't get a function like
```emacs-lisp
(defun test-vterm-goto-char ()
(interactive)
 (goto-char 1))
```
to work in vterm buffers. There may be some hooks/settings that I don't see.

**Comment by Sbozzolo** [comment]
Thanks for reporting to Doom Emacs.
