### ISSUE TITLE
can not select kill ring item

### ISSUE THREAD

**Issue by yanglimingcn** [akermu/emacs-libvterm#387]
when i select an item in kill ring buffer i got error message below:
Error running timer: (buffer-read-only #<buffer vterm user@host:~>)

**Comment by Sbozzolo** [comment]
Are you using `counsel-yank-pop`? There's a FAQ for that in the readme.

If you are using `yank-pop`, that should work too, unless you are using the fish shell. In that case, you'd have a different error.

**Comment by yanglimingcn** [comment]
I use helm-show-kill-ring
![image](https://user-images.githubusercontent.com/7091130/91246945-b6b0e600-e783-11ea-8ce9-71280decb568.png)

when I select one item i got
![image](https://user-images.githubusercontent.com/7091130/91246985-c92b1f80-e783-11ea-9f05-dce749843375.png)

**Comment by yanglimingcn** [comment]
Debugger entered--returning value: [nil 24390 828 822644 nil #f(compiled-function (&optional before yank-pop) #<bytecode 0x1febef7b41f1>) nil nil 0]
  helm-internal(((name . "Kill Ring") (last-command . switch-to-buffer) (init . #f(compiled-function () #<bytecode 0x1febec9542e1>)) (candidates . helm-kill-ring-candidates) (keymap keymap (3 keymap \.\.\. \.\.\.) (29 . helm-kill-ring-toggle-truncated) (27 keymap \.\.\. \.\.\. \.\.\.) keymap \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. ...) (action . helm-kill-ring-actions) (persistent-action . ignore) (persistent-help . "DoNothing") (help-message . helm-kill-ring-help-message) (multiline . 400) (requires-pattern . 0) (filtered-candidate-transformer helm-kill-ring-transformer helm-fuzzy-highlight-matches helm-multiline-transformer) (match helm-mm-exact-match helm-mm-match helm-mm-3-migemo-match) (redisplay . identity) (header-line . "C-j: DoNothing (keeping session)") (multimatch . t) (group . helm-ring) (migemo . t)) nil nil noresume nil "*helm kill ring*" nil nil nil)
* apply(helm-internal (((name . "Kill Ring") (last-command . switch-to-buffer) (init . #f(compiled-function () #<bytecode 0x1febec9542e1>)) (candidates . helm-kill-ring-candidates) (keymap keymap (3 keymap \.\.\. \.\.\.) (29 . helm-kill-ring-toggle-truncated) (27 keymap \.\.\. \.\.\. \.\.\.) keymap \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. ...) (action . helm-kill-ring-actions) (persistent-action . ignore) (persistent-help . "DoNothing") (help-message . helm-kill-ring-help-message) (multiline . 400) (requires-pattern . 0) (filtered-candidate-transformer helm-kill-ring-transformer helm-fuzzy-highlight-matches helm-multiline-transformer) (match helm-mm-exact-match helm-mm-match helm-mm-3-migemo-match) (redisplay . identity) (header-line . "C-j: DoNothing (keeping session)") (multimatch . t) (group . helm-ring) (migemo . t)) nil nil noresume nil "*helm kill ring*" nil nil nil))
* helm(((name . "Kill Ring") (last-command . switch-to-buffer) (init . #f(compiled-function () #<bytecode 0x1febec9542e1>)) (candidates . helm-kill-ring-candidates) (keymap keymap (3 keymap \.\.\. \.\.\.) (29 . helm-kill-ring-toggle-truncated) (27 keymap \.\.\. \.\.\. \.\.\.) keymap \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. ...) (action . helm-kill-ring-actions) (persistent-action . ignore) (persistent-help . "DoNothing") (help-message . helm-kill-ring-help-message) (multiline . 400) (requires-pattern . 0) (filtered-candidate-transformer helm-kill-ring-transformer helm-fuzzy-highlight-matches helm-multiline-transformer) (match helm-mm-exact-match helm-mm-match helm-mm-3-migemo-match) (redisplay . identity) (header-line . "C-j: DoNothing (keeping session)") (multimatch . t) (group . helm-ring) (migemo . t)) nil nil noresume nil "*helm kill ring*" nil nil nil)
* apply(helm (((name . "Kill Ring") (last-command . switch-to-buffer) (init . #f(compiled-function () #<bytecode 0x1febec9542e1>)) (candidates . helm-kill-ring-candidates) (keymap keymap (3 keymap \.\.\. \.\.\.) (29 . helm-kill-ring-toggle-truncated) (27 keymap \.\.\. \.\.\. \.\.\.) keymap \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. ...) (action . helm-kill-ring-actions) (persistent-action . ignore) (persistent-help . "DoNothing") (help-message . helm-kill-ring-help-message) (multiline . 400) (requires-pattern . 0) (filtered-candidate-transformer helm-kill-ring-transformer helm-fuzzy-highlight-matches helm-multiline-transformer) (match helm-mm-exact-match helm-mm-match helm-mm-3-migemo-match) (redisplay . identity) (header-line . "C-j: DoNothing (keeping session)") (multimatch . t) (group . helm-ring) (migemo . t)) nil nil noresume nil "*helm kill ring*" nil nil nil))
* helm(:sources ((name . "Kill Ring") (last-command . switch-to-buffer) (init . #f(compiled-function () #<bytecode 0x1febec9542e1>)) (candidates . helm-kill-ring-candidates) (keymap keymap (3 keymap \.\.\. \.\.\.) (29 . helm-kill-ring-toggle-truncated) (27 keymap \.\.\. \.\.\. \.\.\.) keymap \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. \.\.\. ...) (action . helm-kill-ring-actions) (persistent-action . ignore) (persistent-help . "DoNothing") (help-message . helm-kill-ring-help-message) (multiline . 400) (requires-pattern . 0) (filtered-candidate-transformer helm-kill-ring-transformer helm-fuzzy-highlight-matches helm-multiline-transformer) (match helm-mm-exact-match helm-mm-match helm-mm-3-migemo-match) (redisplay . identity) (header-line . "C-j: DoNothing (keeping session)") (multimatch . t) (group . helm-ring) (migemo . t)) :buffer "*helm kill ring*" :resume noresume :allow-nest t)
* #f(compiled-function () (interactive nil) #<bytecode 0x1febef017e79>)()
* apply(#f(compiled-function () (interactive nil) #<bytecode 0x1febef017e79>) nil)
* helm-show-kill-ring()
  funcall-interactively(helm-show-kill-ring)
  call-interactively(helm-show-kill-ring nil nil)
  command-execute(helm-show-kill-ring)

**Comment by yanglimingcn** [comment]
I use emacs -Q startup
then use-package vterm, I just use browse-kill-ring select one item. can not input it to vterm buffer

**Comment by Sbozzolo** [comment]
Yes, a workaround similar to the one for `ivy` is needed. I'll get to this as soon as I can.

**Comment by yanglimingcn** [comment]
ok, great, thank you.

**Comment by Sbozzolo** [comment]
Sorry for the delay, it's more complicated than I thought (I don't know Helm), so it will take more time.

**Comment by yanglimingcn** [comment]
thanks for you reply. It does't matter.
