### ISSUE TITLE
Mojibake when output non-ASCII Unicode Characters on certain conditions

### ISSUE THREAD

**Issue by lululau** [akermu/emacs-libvterm#394]
If the 1024th(1-based index) byte of a process's output is any but the last byte of  of a Unicode Character(non-ASCII) bytes sequence, e.g.:

1. OK
```shell
ruby -e 'print "x"*1020+"😀"'
```

2. Mojibake
```shell
ruby -e 'print "x"*1021+"😀"'
```

3. Mojibake
```shell
ruby -e 'print "x"*1022+"😀"'
```

4. Mojibake
```shell
ruby -e 'print "x"*1023+"😀"'
```

5. OK
```shell
ruby -e 'print "x"*1024+"😀"'
```

ps: UTF-8 byte sequence of 😀 is of four bytes

**Comment by Sbozzolo** [comment]
What output do you find?

I find this:

**Comment by lululau** [comment]
Thanks for reply, and I've got this:

![Xnip2020-09-04_09-37-18](https://user-images.githubusercontent.com/440583/92189914-61b35500-ee92-11ea-8856-fc07d75cf39b.png)

**Comment by Sbozzolo** [comment]
I'll investigate. Can you please share some information on your setup (e.g., version of Emacs, libvterm, ...)?

**Comment by lululau** [comment]
Thanks, my env:

OS: macOS 10.15
Emacs: 27.1 (emacs-plus, spacemacs)
libvterm: 0.1.4

**Comment by jixiuf** [comment]
Maybe https://debbugs.gnu.org/cgi/bugreport.cgi?bug=1006 related. 
But I don't known how to fix it now.

**Comment by Sbozzolo** [comment]
@lululau can you test #405?

**Comment by lululau** [comment]
@Sbozzolo tested, it does work, Thanks.

**Comment by lululau** [comment]
@jixiuf Thanks

**Comment by Sbozzolo** [comment]
I will keep this open until the PR is merged (likely very soon).
