### ISSUE TITLE
Prevent auto scrolling

### ISSUE THREAD

**Issue by Silex** [akermu/emacs-libvterm#397]
Hello,

Awesome package :+1: 

Is there a way to prevent a buffer from scrolling to the bottom when content is added?

I ran some `./configure && make`  in a vterm terminal and I wanted to look at the configure detection, but because `make` was running I couldn't scroll back and it kept jumping back to what was outputed.

**Comment by Sbozzolo** [comment]
I personally use `vterm-copy-mode` for those cases. It freezes the terminal and let you use the buffer as a normal buffer, so you can search and move as usual in Emacs. Then, when you exit `vterm-copy-mode` will you find all the new output.

Would this work for you?

**Comment by Silex** [comment]
It should! Thanks, I'll reopen if needed.

**Comment by rbugajewski** [comment]
Is `vterm-copy-mode` the only way to stop the buffer from automatically scrolling? I’m an `evil` user, and ideally new output would be appended to the buffer, and when I press `G` while in normal mode it would scroll to the bottom and continue to automatically scroll on new output.

I think I could hack my way through it by adding a workaround which would map the key binding to a custom function which would disable `vterm-copy-mode` and scroll to the bottom, but this would for example prevent the use case where I want to search in the newly created output.

What do you think, any better ideas?

**Comment by Sbozzolo** [comment]
Unfortunately, I think that at the moment it is not easy to control how the points moves around while the terminal is running. So, if you don't want to use `vterm-copy-mode`, you can use `vterm-send-stop` and `vterm-send-start` to pause the output, but this will not solve your problem.

**Comment by rbugajewski** [comment]
Thanks, I think I’ll settle for a workaround with `vterm-copy-mode` for a while.

BTW thanks for this awesome package! vterm is dramatically better than the built-in alternatives, which I couldn’t even really use for my workflow due to their shortcomings. Thanks to this package I seldomly have to open a dedicated terminal emulator anymore.

**Comment by angrybacon** [comment]
Has anything relevant changed since the issue was first filed? My use case isn't too different from OP where I have a server running that keeps logging stuff periodically and looking at past logs proves difficult outside of the copy mode

**Comment by rbugajewski** [comment]
@angrybacon Three years later I’m still rocking the `vterm-copy-mode`.

**Comment by Sbozzolo** [comment]
This problem is not as trivial as it sounds like because a lot of the logic to keep the terminal in a valid state is tied to redrawing (and when you redraw, you also ensure that the cursor is in a valid state). 

I also find this problem particularly annoying.

**Comment by angrybacon** [comment]
This isn't very well tested but in theory this will behave like most users expect

```el
(advice-add 'set-window-vscroll :after
  (defun me/vterm-toggle-scroll (&rest _)
    (when (eq major-mode 'vterm-mode)
      (if (> (window-end) (buffer-size))
          (when vterm-copy-mode (vterm-copy-mode-done nil))
        (vterm-copy-mode 1)))))
```

Can you think of anything that might go wrong with this? Performance-wise? I don't really know how generic `set-window-vscroll` is or whether it is too closely tied to me using `pixel-scroll-precision`

**Comment by Sbozzolo** [comment]
> This isn't very well tested but in theory this will behave like most users expect
> 
> ```emacs-lisp
> (advice-add 'set-window-vscroll :after
>   (defun me/vterm-toggle-scroll (&rest _)
>     (when (eq major-mode 'vterm-mode)
>       (if (> (window-end) (buffer-size))
>           (when vterm-copy-mode (vterm-copy-mode-done nil))
>         (vterm-copy-mode 1)))))
> ```
> 
> Can you think of anything that might go wrong with this? Performance-wise? I don't really know how generic `set-window-vscroll` is or whether it is too closely tied to me using `pixel-scroll-precision`

I don't see anything immediately wrong with this. The only caveat is that this will only work with modern versions of Emacs.

**Comment by ekr-nttd-emeal** [comment]
> This isn't very well tested but in theory this will behave like most users expect
> 
> ```elisp
> (advice-add 'set-window-vscroll :after
>   (defun me/vterm-toggle-scroll (&rest _)
>     (when (eq major-mode 'vterm-mode)
>       (if (> (window-end) (buffer-size))
>           (when vterm-copy-mode (vterm-copy-mode-done nil))
>         (vterm-copy-mode 1)))))
> ```
>
> Can you think of anything that might go wrong with this? Performance-wise? I don't really know how generic `set-window-vscroll` is or whether it is too closely tied to me using `pixel-scroll-precision`

Awesome. This works for me in GNU Emacs 30.1 on MacOS.

That said, you do have to scroll up (with the mouse preferably) relatively quickly. Scrolling up with PageUp instead warps back down immediately (at least if you use the `pixel-scroll.el` package, I did not try without).

To get that to work, one can use this override. Note that `(pixel-scroll-interpolate-up)` is from `pixel-scroll.el`. If you want to use this code, you need to figure out what the correct function is for you (easily done with `C-h k` followed by your PageUp key) 

```elisp
  (defun my/vterm-page-up (n)
    "In vterm: enter copy-mode, then do normal PageUp."
    (interactive "P")
    (message "my/vterm-page-up")
    (unless vterm-copy-mode
      (vterm-copy-mode 1))
    (pixel-scroll-interpolate-up))

  (define-key vterm-mode-map [prior] #'my/vterm-page-up)
```

EDIT: I seem to have been confused; the above code does not seem to do anything. I also played around with `'vterm-keymap-exceptions'` and `'vterm--exclude-keys` but no bueno. I found no way to automatically enter copy-mode on PageUp unfortunately. It's still better than nothing - if I remember to initiate the scrolling with the mouse/touchpad, all is well.
