### ISSUE TITLE
Fatal error: 'emacs-module.h' file not found

### ISSUE THREAD

**Issue by sooheon** [akermu/emacs-libvterm#4]
Following the instructions, at the make step, I get the following error:

```
 l/emacs-libvterm $ make
gcc -ggdb3 -Wall -I/home/sooheon/Dropbox/code/emacs/emacs/src -I/ -fPIC -c vterm-module.c
In file included from vterm-module.c:1:
./vterm-module.h:1:10: fatal error: 'emacs-module.h' file not found
#include <emacs-module.h>
         ^
1 error generated.
make: *** [vterm-module.o] Error 1
```

I installed emacs with homebrew, but not knowing where the source files are kept, also cloned the github mirror of the source. In there, there is only `emacs-module.h.in`, not `emacs-module.h`, but I don't know enough c to know why.

**Comment by akermu** [comment]
Apparently in the Emacs master branch the header is generated, so you have build Emacs.

**Comment by akermu** [comment]
To clarify you just have to build the source, which you cloned from github. You still can use Emacs from homebrew.
