### ISSUE TITLE
enter/return does not always works

### ISSUE THREAD

**Issue by jixiuf** [akermu/emacs-libvterm#40]
should similar to https://github.com/vim/vim/issues/1998

in redis-cli or fzf enter/return behavior like Ctrl-j in iterm2

**Comment by QiangF** [comment]
I noticed that with the default setting for fzf, enter doesn't do accept like in xterm, so I have this setting:

    export FZF_DEFAULT_OPTS="--extended --cycle --bind=\
    ctrl-j:accept,ctrl-k:kill-line,tab:toggle-up,btab:toggle-down,\
    ctrl-y:execute('echo {} | xclip -selection clipboard')+abort"

**Comment by QiangF** [comment]
We need this to be solved to user marker. https://github.com/pindexis/marker

**Comment by deb0ch** [comment]
@QiangF You just made me discover Marker and it looks great 😺

**Comment by QiangF** [comment]
@deb0ch You may also like ralph, I am trying to make maker and ralph work together.
https://github.com/qw3rtman/ralph

**Comment by mattiasb** [comment]
> I noticed that with the default setting for fzf, enter doesn't do accept like in xterm, so I have this setting:
> 
> ```
> export FZF_DEFAULT_OPTS="--extended --cycle --bind=\
> ctrl-j:accept,ctrl-k:kill-line,tab:toggle-up,btab:toggle-down,\
> ctrl-y:execute('echo {} | xclip -selection clipboard')+abort"
> ```

For anyone else reading this, I *belive* all other settings above except `--bind=ctrl-j:accept` is noise and not needed to work around this specific issue. So add something like this to your environment and you should be good:
```
FZF_DEFAULT_OPTS=--bind=ctrl-j:accept
```
