### ISSUE TITLE
How to make ESC/Meta a key which reaches out of the terminal

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#400]
I am starting with libvterm and I noticed that Ctrl x reaches out of the vterm terminal. So far so good.

How can I make ESC/Meta reach out of the terminal as well?

**Comment by Sbozzolo** [comment]
You can use `vterm-send-M-x` and `vterm-send-escape` to send those keys to the terminal. These are Emacs commands, so you have to call them with `M-x`.

If you want Emacs to always capture ESC, you should set
`(define-key vterm-mode-map (kbd "<escape>") nil)`.

**Comment by Sbozzolo** [comment]
Does this answer your question?

**Comment by halloleo** [comment]
Yes, it did. Thanks a lot, @Sbozzolo.

`vterm` is pretty cool! :smile:
