### ISSUE TITLE
libvterm>0.1.3 VTermStringFragment breaks emacs-libvterm

### ISSUE THREAD

**Issue by Sbozzolo** [akermu/emacs-libvterm#403]
In 1d7d72b63b21eb0d5a66da3163bc2c2b59bc3908, the developers of libvterm introduced a new way to handle strings with a struct `VTermStringFragment`. We are still using the previous infrastructure with plain arrays of chars.

While most users are using libvterm<=0.1.3, it is important to keep up with libvterm, so that we can enjoy the improvements and bugfixes in the library. This change is not too big, but it is not simple to handle because we need to maintain backward compatibility. I don't know how to do this. (My only idea is to have a branch that supports libvterm>0.1.3, but this is not ideal.)

**Comment by wyuenho** [comment]
Maybe dropping support for system libvterm is a good idea. The vterm-module requires compilation and build essentials to exist anyway, why bother supporting old versions?

**Comment by condy0919** [comment]
vterm failed to start, is it related?

```
Debugger entered--Lisp error: (error "Memory exhausted--use C-x s then exit and restart ...")
  vterm--new(45 172 1000 nil nil nil)
  vterm-mode()
  vterm()
  funcall-interactively(vterm)
  call-interactively(vterm nil nil)
  command-execute(vterm)
```

**Comment by condy0919** [comment]
> vterm failed to start, is it related?
> 
> ```
> Debugger entered--Lisp error: (error "Memory exhausted--use C-x s then exit and restart ...")
>   vterm--new(45 172 1000 nil nil nil)
>   vterm-mode()
>   vterm()
>   funcall-interactively(vterm)
>   call-interactively(vterm nil nil)
>   command-execute(vterm)
> ```

Looks like an emacs bug, has been fixed now.
