### ISSUE TITLE
Compilation error on CentOS 6

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#411]
When building `vterm-module` through an initial `M-x vterm` I get on CentOS/RHEL 6 the following error:

```
.
.
.
[  8%] Performing update step for 'libvterm'
[ 16%] No patch step for 'libvterm'
[ 25%] No configure step for 'libvterm'
[ 33%] Performing build step for 'libvterm'
CC src/encoding.c
cc1: error: unrecognized command line option "-Wpedantic"
make[3]: *** [src/encoding.lo] Error 1
make[2]: *** [libvterm-prefix/src/libvterm-stamp/libvterm-build] Error 2
make[1]: *** [CMakeFiles/libvterm.dir/all] Error 2
make: *** [all] Error 2
```
So the problem seems to be the line *cc1: error: unrecognized command line option "-Wpedantic"*. 

Any idea how to fix this?

PS: On macOS 10.13.6 it compiles fine.

**Comment by halloleo** [comment]
I found a (crud) workaround: After the command fails, I edit the Makefile `[vterm-package-dir]/build/libvterm-prefix/src/libvterm/Makefile` by removing the `-Wpedantic`  option from the line

`override CFLAGS +=-Wall -Iinclude -std=c99 -Wpedantic` (line 11)


Then I issue in the terminal:

```
$ cd [vterm-package-dir]/build
$ make
```

This time the compiling succeeds - and afterwards `M-x vterm` magically works! :smile:

**Comment by halloleo** [comment]
I guess the Makefile containing  the offending `-Wpedantic` is part of the _neovim-libvterm_ project, right? So I should file an issue there?

**Comment by Sbozzolo** [comment]
Thanks, @halloleo, for your report and for providing a workaround. The issue is indeed with `libvterm`. What version of `gcc` are you using?

**Comment by halloleo** [comment]
`gcc` version: 6.2.0

`cc` version: 4.4.7

And I think the build script uses `cc` not `gcc`, or more precisely `libtool` not `glibtool`. (I'm not a big build expert, but I think the C compiler is not invoked directly: The `CFLAGS` variable is only used in command lines starting with `$(LIBTOOL)`.)

**Comment by halloleo** [comment]
@Sbozzolo Which one is the correct `libvterm` repo `emacs-libvterm uses?`

**Comment by Sbozzolo** [comment]
If you don't have it on your system, we obtain it from here: https://github.com/neovim/libvterm.git.

**Comment by halloleo** [comment]
Thanks @Sbozzolo. I was just asking, so that I can file the issue with them.

However I am just seeing that they don't accept issues:

![](https://i.imgur.com/E630dHjl.png)

Any idea whether they receive issue about libvterm anywhere else?

**Comment by Sbozzolo** [comment]
The homepage of the project is here: https://launchpad.net/libvterm.

The maintainer also accepts bug reports via email (see CONTRIBUTING file).

**Comment by halloleo** [comment]
Thanks. Will raise it there.

**Comment by halloleo** [comment]
Filed an upstream bug report: https://bugs.launchpad.net/libvterm/+bug/1898688
