### ISSUE TITLE
Arrow keys do not work in terminal vi session

### ISSUE THREAD

**Issue by greened** [akermu/emacs-libvterm#412]
When I start up vi in a vterm terminal, I am unable to use the arrow keys to navigate.  The arrow keys seem to work fine outside of vi, for example I can up-arrow to scroll through previous shell commands.

I am using vterm with eterm-256color.  Previously I used eterm-color with ansi-term and that seemed to be fine.  I verified that ansi-term works fine with eterm-256color.  So the problem does seem to be vterm-related.

**Comment by Sbozzolo** [comment]
I just checked with vim and with TERM set to its default value. Can you
please check if you can reproduce this problem with a clean configuration
(emacs -Q)?

Thanks

**Comment by greened** [comment]
It does not work with emacs -Q.  I did have to evaluate the bits of my startup that load use-package and vterm, but that's it.  I am on MacOS.

**Comment by greened** [comment]
Ok, it is definitely an eterm-256color issue.  I had one line remaining in my vterm setup that referred to it.  When I commented it out, things started working.  Sorry about the noise.

**Comment by greened** [comment]
It also fails with eterm-color.

**Comment by Sbozzolo** [comment]
Interesting, we should check if the suggestion of using eterm-256color is
still valid.
