### ISSUE TITLE
Position of point in vterm-copy-mode

### ISSUE THREAD

**Issue by xendk** [akermu/emacs-libvterm#413]
Point seems to be moved to end of the buffer when executing some command in vterm-copy-mode.

For instance, I used to be able to go into copy mode, move to a line that lists some filename and use `M-x ffap` to open the named file. That doesn't work  anymore as the point is moved to the end of buffer when typing `M-x`. Goes for other keyboard commands like `C-x C-f` too.

Interestingly, if I `local-set-key` the key `f` to `ffap`, it works, that apparently gets run before the point is moved.

But I either case, I don't think the point should move.

**Comment by Sbozzolo** [comment]
It would be tremendously useful if you could point me to a commit in which this used to work.

**Comment by jixiuf** [comment]
Maybe when M-x is called, the window size changed,  I think #278  is trying to solve this problem .

**Comment by Sbozzolo** [comment]
> Maybe when M-x is called, the window size changed, I think #278 is trying to solve this problem .

That's a good idea. I'll have a look.

**Comment by Sbozzolo** [comment]
I tested the PR, and it fixes this problem. I will test if there are unintended side effects, in case there are none, we can merge it.

**Comment by xendk** [comment]
Sorry been away.

Yeah, the window resize sounds like a prime suspect, and can confirm the code in #278 fixes the problem.

**Comment by Sbozzolo** [comment]
Thanks, merged to master.
