### ISSUE TITLE
vterm does not change "default-directory"

### ISSUE THREAD

**Issue by KaratasFurkan** [akermu/emacs-libvterm#414]
Hi, thanks for this great package first of all.

As far as I remember, vterm was changing `default-directory`, when I use `find-file`, the current directory ($PWD) in vterm was listing. It does not work for a while, how can I solve this?

**Comment by Sbozzolo** [comment]
Have a look at [the relevant section in the README](https://github.com/akermu/emacs-libvterm#directory-tracking-and-prompt-tracking), you may have to fix you shell side configuration.

**Comment by KaratasFurkan** [comment]
Thanks for quick reply, sorry for not reading readme, my apologies.

When I put the code block in my config.fish file, I got the error below every time I open fish shell:
```
~/.config/fish/config.fish (line 169): 
    vterm_printf '51;A'(whoami)'@'(hostname)':'(pwd)
    ^
in function 'vterm_prompt_end'
        called on line 177 of file ~/.config/fish/config.fish
in function 'fish_prompt'
in command substitution
```

**Comment by Sbozzolo** [comment]
It looks like `vterm_printf` is not available, which means that there is more code that you have to add to your `config.fish`. You can see an example of onfiguration for fish in `etc/emacs-vterm.fish`.

**Comment by KaratasFurkan** [comment]
I add the vterm_printf function too and it worked, thank you!
