### ISSUE TITLE
popup vterm on the right instead of the bottom

### ISSUE THREAD

**Issue by leosolid** [akermu/emacs-libvterm#415]
emacs noob here. How can I get vterm to popup on the right side instead of the bottom?

**Comment by Sbozzolo** [comment]
By default, when you invoke `vterm`, the terminal will open in the current buffer. Starter packs like Spacemacs or Doom define their own idea of popup and customize this behavior. If you are using one of those, it would be more appropriate to ask this question to the maintainers/communities of such projects (this is outside our control).

**Comment by halloleo** [comment]
You can use `M-x vterm-other-window` to open vterm in another than the current window. Where this window is, is - as Sbozzolo mentioned - determined by other parts of Emacs.

**Comment by leosolid** [comment]
Got it. I'm using doom, so I'll ask the folks over there. If I find out anything I'll link it here. `M-x vterm-other-window` seems to have the same behvior as `M-x vterm` (might be doom related)
