### ISSUE TITLE
How to send Shift-right to the shell?

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#416]
I know I can send the <Right> key to the shell in vterm (`vterm-send-right`), but how can I send Shift-<Right> to the shell? This would be good for in-shell text-highlighting.

**Comment by Sbozzolo** [comment]
If you want to send KEY with shift, use `(vterm-send-key KEY t)`.

**Comment by halloleo** [comment]
Cool. Thanks!

**Comment by halloleo** [comment]
For plain shift trhis works, but I want to send Contriol-Shift-Right as well. So I tried

```
  (vterm-send-key "<right>" t nil t)
```

But then I get garbage in my terminal window. (More precisely I get **`[1;6C`** in the terminal.)

**Comment by halloleo** [comment]
Sorry, the last issue seems to be a problem with key bindings in xonsh, not in vterm.
