### ISSUE TITLE
How to click and open files (or urls) in vterm?

### ISSUE THREAD

**Issue by folke** [akermu/emacs-libvterm#418]
Is there any way to make `links` in vterm clickable?

Suppose I run a `linter` and see some errors,  I would like to `ctrl-click` or press `RET` in normal mode, on the file links to open them in a new buffer.

How can I accomplish this?

![image](https://user-images.githubusercontent.com/292349/95299226-337ab980-0832-11eb-9e16-b724a409052d.png)

**Comment by jixiuf** [comment]
Does ffap work?

**Comment by folke** [comment]
Tried that, but it doesn't work. I'm assuming the ansi control characters mess it up.

**Comment by Sbozzolo** [comment]
I use `browse-url` for that:

```emacs-lisp
      (defun sbozzolo/browse-url (url)
        "Browse url starting with what is at the point"
        (interactive (list
                      (read-string (format "URL (%s): " (thing-at-point 'url))
                                   (thing-at-point 'url) nil (thing-at-point 'url))))
        (browse-url url))
```

But I agree, it would be nice to be able to just click on the link.

**Comment by folke** [comment]
@Sbozzolo thank you for the suggestion, but that also doesn't seem to work.

The ansi color sequences are messing up with the file detection regex.

When I run `npm run lint --no-color`, then ffap does work, but then of course I don't have any colors in the output  :)

I'm fairly new to Elisp, but will see if I can find a way to get the vterm buffer; strip all ansi control characters somehow; and then run `ffap-menu` on the result.

I understand this is out of scope for `libvterm`, so feel free to close this issue.

**Comment by Sbozzolo** [comment]
I forgot to mention that I run the command in `vterm-copy-mode`. Can you try with that?

**Comment by arnested** [comment]
How about using `goto-address-mode`?

I just enabled it myself and the first impression is good.

**Comment by lainor** [comment]
I am searching a solution on this issue as well, @folke have you found a workaround?

**Comment by aaronjensen** [comment]
ffap kind of works, but it doesn't work if a file name wraps. Is there a way to detect line continuation in vterm? i.e. differentiate it from an actual newline in the terminal?
