### ISSUE TITLE
Use font-lock-defaults?

### ISSUE THREAD

**Issue by xendk** [akermu/emacs-libvterm#425]
I discovered this by chance: https://github.com/akermu/emacs-libvterm/issues/46#issuecomment-451921161

Which was the fix I needed for my vterm-buffers-turning-green problem.

However this didn't work as expected:

```elisp
(use-package vterm
  ...
  :hook
  (vterm-mode . (lambda ()
                  (setq-local font-lock-keywords-only t))))
```
(`font-lock-keywords-only` would be nil when I checked)

After some digging about, I found out this worked:

```elisp
(use-package vterm
  ...
  :hook
  (vterm-mode . (lambda ()
                  (setq-local font-lock-defaults '('() t))))
```

`font-lock-keywords-only` is actually set from the value of `font-lock-defaults`. Which seems to happen on the first fontification, which clearly was run after the mode-hook in my case.

How about adding `(setq-local font-lock-defaults '('() t))` to the mode?

**Comment by heytings** [comment]
In fact `font-lock-defaults` is already buffer-local, so you can use `(setq font-lock-defaults '(nil t))`.
I agree with you, this should be added to `vterm-mode`.

**Comment by Sbozzolo** [comment]
I've never had any issue with fontification, but I agree that this should make things more robust.

**Comment by heytings** [comment]
It's not an strictly speaking an "issue", but strings get fontified differently without this.  For example you get `Use "logout" to leave the shell.` with `"logout"` in red without this.

**Comment by xendk** [comment]
> I've never had any issue with fontification, but I agree that this should make things more robust.

You don't get everything green if there's a hanging quote in some commands output?

![image](https://user-images.githubusercontent.com/229422/97140924-fd0fca80-175d-11eb-88db-4c828b93c03f.png)
