### ISSUE TITLE
How to avoid line wrapping/folding?

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#435]
In normal shell buffers I can avoid line folding with `M-x toggle-truncate-lines`. this obviously doesn't work in emacs-libterm.

Is there another way to tell emacs-libterm to output long unfolded lines?

I tried setting the terminal width _in the shell_ (like `stty size 1000` )but this doesn't seem to work.

**Comment by jixiuf** [comment]
you may try `(setq  vterm-min-window-width 1000)`

**Comment by halloleo** [comment]
Thanks heaps. That certainly does the trick. 😄 

It even enables line folding via `toggle-truncate-lines` (plus things like `find-file-at-point` in `vterm-copy-mode`).
