### ISSUE TITLE
Cannot bind `C-<left>` to move words

### ISSUE THREAD

**Issue by tobiasBora** [akermu/emacs-libvterm#436]
I use quite often the `C-<left>` and `C-<right>` shortcuts in Konsole and emacs to move word per word, unfortunately I can't find how to bind them to vterm. Indeed, if I do that, I do move one word back, but at the next keystroke, the cursor is back at his original position. I tried to define:

```
(define-key vterm-mode-map (kbd "C-<left>")
    (lambda () (interactive) (vterm-send-key (kbd "C-<left>"))))
```

but when I run it I get "Wrong type argument: stringp, [C-left]", while the documentation says that `vterm-send-key` should accept any input accepted by `kdb`.

**Comment by Sbozzolo** [comment]
Why don't you try this:
```emacs-lisp
(define-key vterm-mode-map (kbd "C-<left>") #'vterm-send-M-b)
```

The problem with your attempt is that you called `(kbd "C-<left>")` wheres it should be just `C-<left>` (`vterm-send-key` takes the same input as `kbd`, not `kbd` itself!).

**Comment by tobiasBora** [comment]
Oh, very good point, sorry for the noise, and thanks a lot (I also learnt a new keybinding)!
