### ISSUE TITLE
Suggestion about the environment

### ISSUE THREAD

**Issue by Ergus** [akermu/emacs-libvterm#439]
Hi:

After some time working with vterm I have some suggestions that are not very complex to implement and could be very useful IMO:

1) Could you add an vterm-environment variable? so the user could add extra environment variables to the vterm shell processes only.

So in the derived mode we just need to do something like:
```
(defcustom vterm-environment nil)
 ...

(let ((process-environment (append `(,(concat "TERM="
                                                vterm-term-environment-variable)
                                                "INSIDE_EMACS=vterm"
                                                "LINES"
                                                "COLUMNS")
                                                vterm-environment
                                                process-environment))
...
```

2) Export the vterm path.

This is related, but not dependent on the previous one.

I want to load the emacs-vterm-bash.sh but I install vterm from melpa where the path changes.

My current solution to that is:

```
(add-to-list 'process-environment (concat "EMACS_VTERM_PATH="
                                          (file-name-directory (find-library-name "vterm"))))
```

and then in the bash side I do:

```
source "${VTERM_PATH}/etc/emacs-vterm-bash.sh"
```

But up to now I have to export it globally to all the emacs subprocesses.

Does it make sense?

**Comment by jixiuf** [comment]
6c5b67574643849a32061f820a1e4e27627bcb31 
 add defcustom vterm-environment and  export EMACS_VTERM_PATH

**Comment by Ergus** [comment]
> [6c5b675](https://github.com/akermu/emacs-libvterm/commit/6c5b67574643849a32061f820a1e4e27627bcb31)
> add defcustom vterm-environment and export EMACS_VTERM_PATH

Hi @jixiuf :

Thanks for implementing this. The only missing thing now is to mention the new environment variable and the new custom in the Readme.

**Comment by jixiuf** [comment]
can you write some document , I am not good at write document for my bad english

**Comment by Ergus** [comment]
Something simple like:

When using vterm Emacs sets the environment variable `INSIDE_EMACS` in the subshell to ‘vterm’. Usually the programs check this variable to determine whether they are running inside emacs.

Vterm also sets an extra variable `EMACS_VTERM_PATH` to the place where the vterm library is installed. This is very useful because when vterm is installed from melpa the Shell-side configuration files are in the `EMACS_VTERM_PATH` inside the `/etc` sub-directory. After a package update, the directory name changes, so, a code like this in your bashrc could be enough to load always the latest version of the file from the right loation without coping any file manually.

```bash
if [[ "$INSIDE_EMACS" = 'vterm' ]] \
    && [[ -n ${EMACS_VTERM_PATH} ]] \
    && [[ -f ${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh ]]; then
	source ${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh
fi
```

The user can modify the environment of vterm sub-shells from lisp programs; to add more environment variables there is the custom `vterm-environment` which has a similar format than the internal emacs variable `process-environment`. You can check the documentation with `C-h v process-environment` for more details.
