### ISSUE TITLE
Shift-PageUp/PageDown for scrolling

### ISSUE THREAD

**Issue by dahtah** [akermu/emacs-libvterm#449]
I'm very used to Shift PageUp/PageDown for scrolling in the shell, which AFAICT doesn't work in emacs-libvterm. Is there any way to emulate this behaviour? I know I can go through copy mode, but that seems overly complicated.

**Comment by EnigmaCurry** [comment]
I rebound some keys to get it to behave like this:

https://github.com/EnigmaCurry/emacs/blob/master/spacemacs.el#L423-L426

```
  (define-key vterm-mode-map [prior] 'scroll-down-command)
  (define-key vterm-mode-map [S-prior] 'scroll-down-command)
  (define-key vterm-mode-map [next] 'scroll-up-command)
  (define-key vterm-mode-map [S-next] 'scroll-up-command)
```

I was surprised that prior means scroll down and next means scroll up, but it seems to be the case after I tested it.

**Comment by dahtah** [comment]
Very helpful, thanks. Perhaps this should be a default? It'd make vterm more consistent with other terminal emulators.

**Comment by jixiuf** [comment]
> Very helpful, thanks. Perhaps this should be a default? It'd make vterm more consistent with other terminal emulators.

2c4d2c9fc8e6e89746e6aa191aee2b8974c8eab9 done.

**Comment by dahtah** [comment]
Great, thanks!

**Comment by EnigmaCurry** [comment]
I realize now that I should not have mapped `prior` and `next`, but only `S-next` and `S-prior`, as it would break page-up page-down in a program like `less`.
