### ISSUE TITLE
Shell starts up before vterm completely finishes initialising

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#452]
I have noticed that the shells starts up _before_ emacs-libvterm completely finishes initialising.

My example: When in the rc file of the shell I test for the terminal width via `tput cols` the result might not reflect what I have set in the config via `(setq vterm-min-window-width 1000)`.

If I sleep in the rc file for a second or two everything is fine, but it would be clearly safer if the shell is not started before the full setup has finished.

**Comment by Sbozzolo** [comment]
I tried the test you suggest, and I find no inconsistency. 
However, there is one step that is performed after starting the shell, which is
```
(process-put vterm--process 'adjust-window-size-function
               #'vterm--window-adjust-process-window-size)
```
This makes vterm buffers behave in a special way when it comes to window size. This is where the problem may be.

**Comment by halloleo** [comment]
Aha! Interesting! Can the shell somehow find out whether  `vterm--window-adjust-process-window-size` has finished? (Then the shell's rc script can wait with its own `tput` and `stty` command until vterm has finished _all_ setting up.)

**Comment by Sbozzolo** [comment]
The only solutions I can come up with are hack-ish and I would not recommend them. 

What you are reporting is a bug: the shell should be initialized with the correct column and row numbers.

**Comment by halloleo** [comment]
Mmmmh, a bug in vterm or in the shell?

In any case a hackish solution might be better than none. (At the moment I am just sleeping in the shell's rc file for 3 seconds when Emacs is the direct parent of the shell. These 3 seconds make it quite certain that ` vterm--window-adjust-process-window-size` has finished but they create a  pretty bad user experience...)

**Comment by Sbozzolo** [comment]
> Mmmmh, a bug in vterm or in the shell?

In vterm. The bug is: we are not telling the correct window side to the shell at initialization. 

The hackish workaround I have in mind is nasty and I would much rather try to understand how to fix the bug instead.

**Comment by halloleo** [comment]
I can't reproduce this with the current version. So i close it.
