### ISSUE TITLE
shifted key binding pass through not working

### ISSUE THREAD

**Issue by divansantana** [akermu/emacs-libvterm#458]
In tmux I have this keybinding:

```
bind-key -T root M-h previous-window
bind-key -T root M-n next-window
bind-key -T root M-H swap-window -t -1 -d
bind-key -T root M-N swap-window -t +1 -d
```

The top two keybindings work fine in vterm.

The bottow two keybindings don't work in vterm, they simply still call the top two bindings. It seems because the shifted key is not being passed through correctly.

```
M-h (translated from M-H) runs the command vterm-send-M-h
```

Is this a bug?

**Comment by jixiuf** [comment]
93053f67268595e9a560fff4a635db51c4e9604f should fix this .
