### ISSUE TITLE
htop background issues

### ISSUE THREAD

**Issue by deadtrickster** [akermu/emacs-libvterm#46]
As requested, emacs -Q screenshot:

![screenshot_2018-12-13_09-29-48](https://user-images.githubusercontent.com/172311/49925655-da51d100-feb9-11e8-913e-88a204a39535.png)

**Comment by deadtrickster** [comment]
emacs is the HEAD of master

**Comment by deadtrickster** [comment]
maybe related (git diff): 

![screenshot_2019-01-02_15-27-01](https://user-images.githubusercontent.com/172311/50595984-ed493700-0ea2-11e9-977b-58ce320f3c71.png)

also interesting to note - emacs string face used. They should be white. Maybe this conflicts with escape codes. Ansi-term is ok.

**Comment by deb0ch** [comment]
One more info that would be useful: what version/commit of emacs-libvterm are you using?

**Comment by deadtrickster** [comment]
1b03e4e0071954646be1f50483244c23acfbd253

**Comment by deadtrickster** [comment]
strings highlighting can be turned of by `(setq-local font-lock-keywords-only t)` in the mode hook.

**Comment by akermu** [comment]
@deadtrickster Is it possible to give me a short elisp configuration loaded with `emacs -Q`, which reproduces the issue?

**Comment by deadtrickster** [comment]
I can reproduce it with `emacs -Q` and two lines:

```elisp
(add-to-list 'load-path "../emacs-libvterm") 
(require 'vterm)
```

**Comment by akermu** [comment]
I cannot reproduce this here, but I pushed a update regarding color handling in general. So can you reproduce this with the latest master? And which OS are you using, it might be related to the version of libvterm?

**Comment by deadtrickster** [comment]
I have latest ubuntu here.

htop inside xfce4-terminal:

![screenshot_2019-01-27_19-28-54](https://user-images.githubusercontent.com/172311/51805155-5c2f6b00-226a-11e9-82ba-fc35bac59b4a.png)

htop inside emacs:

![screenshot_2019-01-27_19-32-18](https://user-images.githubusercontent.com/172311/51805162-67829680-226a-11e9-91f2-33a1e239e694.png)

Same color schema. I would say black background handling is suspicious.

**Comment by deadtrickster** [comment]
I rebuilt emacs, libterm, now buffer background is always black, and still colors messed up in htop and scripts :-)
![screenshot_2019-01-29_13-32-02](https://user-images.githubusercontent.com/172311/51908497-4afd7000-23ca-11e9-938e-70db4aa49ab3.png)

**Comment by deadtrickster** [comment]
Actually black backgroun, not magenta though: 
![screenshot_2019-01-29_13-39-08](https://user-images.githubusercontent.com/172311/51908890-4b4a3b00-23cb-11e9-866c-3ddb249766b9.png)

**Comment by akermu** [comment]
Magenta is fixed with 622cde3. The htop background issue seems to be a different issue.

**Comment by akermu** [comment]
@deadtrickster Is this still reproduceable with the latest master, since #82 is merged?

**Comment by deadtrickster** [comment]
nope, thanks a lot!
