### ISSUE TITLE
Can't type into vterm with insert: buffer is read-only

### ISSUE THREAD

**Issue by veronikazaglotova** [akermu/emacs-libvterm#461]
I'm trying to make a shortcut that runs a command in vterm so that I could see the output and possibly interact with it. I just used "insert" function in my Emacs Lisp function, but apperently it does not work in emacs-libvterm. Luckily, I figured I can just use eshell, since the command I'm running is just plain text
What is the right way to type something into the terminal then?

**Comment by tsdh** [comment]
Use `vterm-send-string` followed by `vterm-send-return` to mimic keyboard input.  At least that's what I do and what seems to work just fine.

**Comment by veronikazaglotova** [comment]
Thx a lot m8!
