### ISSUE TITLE
[FR] Add option to make vterm windows non-dedicated?

### ISSUE THREAD

**Issue by edgar-vincent** [akermu/emacs-libvterm#463]
Hello,

First of all, thanks of all for your great work. I use vterm as my main terminal emulator and have been very happy with it.
I noticed that windows in which vterm buffers are open are dedicated - I might be wrong, but I neither think this has always been the case, nor that it has something to do with my configuration.

If this is indeed the case, would it be possible make this feature customisable? 
I don't seem to be able to kill vterm buffers (`attempt to kill minibuffer or sole ordinary window`) and buffers I open (with C-x C-f for example) when vterm is open are displayed in a split window.

Thanks a lot.

**Comment by Sbozzolo** [comment]
I didn't know that [dedicated windows](https://www.gnu.org/software/emacs/manual/html_node/elisp/Dedicated-Windows.html) were a thing. On my system, if I eval `(window-dedicated-p)` in a vterm buffer I get `nil`. Do you obtain the same result?

**Comment by edgar-vincent** [comment]
I'm very sorry about that, I just found out that this was caused by my [vterm-toggle](https://github.com/jixiuf/vterm-toggle) configuration.
Thanks for your reply, and sorry again.
