### ISSUE TITLE
PS1 and PROMPT_COMMAND configuration break prompt on shell mode buffers

### ISSUE THREAD

**Issue by gdindi** [akermu/emacs-libvterm#464]
Hi,
I have configured PS1 and PROMPT_COMMAND in my .bashrc to do directory tracking and it works fine. The problem now is that when I use `M-x shell` or `M-x shx`, my prompt shows this:

`^[]51;Agarjola@pc-117-162:/home/garjola^[\`

The prompt behaves perfect in vterm and outside emacs. Is there anything I can do?
Thanks!

**Comment by Sbozzolo** [comment]
You can check if `$INSIDE_EMACS == "vterm"` and change the prompt only if the equality is true.

**Comment by gdindi** [comment]
```
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    PS1=$PS1'\[$(vterm_prompt_end)\]'
    PROMPT_COMMAND='echo -ne "\033]0;${HOSTNAME}:${PWD}\007"'
fi
```

This solves the problem. Thank you.
