### ISSUE TITLE
How can an command from `vterm-eval-cmds` pass its results back to the shell

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#468]
I can execute the commands from `vterm-eval-cmds` in the shell and I can even pass parameters _to_ the Emacs command, but how can the Emacs command _pass information back_ to the shell?

**Comment by Sbozzolo** [comment]
Say you want to run the command `(+ 2 3)` and you want to store the output in a shell variable `OUT`. 
What you can do is:
```
(defun my-func ()
  (interactive)
  (let ((ret (+ 2 3)))
    (vterm-send-string (format "OUT=%s\n" ret))))
```
Then you add `my-func` to the list of allowed functions to be executed. Of course, you can everything you
want in `vterm-send-string` to do anything you want with the output of the function you called in the shell.

**Comment by halloleo** [comment]
Of course! That makes totally sense! Will try it. Thanks a lot.
