### ISSUE TITLE
holding enter is slow

### ISSUE THREAD

**Issue by kkonevets** [akermu/emacs-libvterm#476]
First of all let me thank the authors of this tool for their job. No matter what the job is awesome, unbelievable terminal experience in Emacs, natural C-terminal keys just work and it is faster than `term` and `eshell`, although much slower than OS native terminal.
Now, we all know it is still alpha, so I found that just holding `enter` key on an empty line is slow, if I open `term` and hold `enter` lines appear smoothly. It is strange because if I `cat file.txt` on a big file `term` just dies, but `vterm` does the job.

**Comment by Sbozzolo** [comment]
In `vterm` we do not refresh the screen as soon as new information is available. There is a delay that helps ensuring that data is correctly passed from vterm to Emacs with no problems. By default, this is 1/10 of a second, so you will never see anything faster than that. If you decrease that (with the variable `vterm-timer-delay`), holding enter will feel much faster. You can even set it to 0 if you want.

The default value is chosen as a good compromise between performance and perceived speed. If you significantly lower that, you may have a drop in performance for large outputs.

**Comment by kkonevets** [comment]
I see, thanks for quick reply. Will stick to default value.
