### ISSUE TITLE
vterm doesn't care about current input method

### ISSUE THREAD

**Issue by bit9tream** [akermu/emacs-libvterm#479]
When `current-input-method` is "russian-computer" and I'm trying to input some russian characters inside vterm's buffer it inputs related english characters (just like if my `current-input-method` was `nil` -> english)
That's not a behavior that I would like to see.

Also, for example, in `ansi-term` emacs's input method only inputs proper characters when I switch to line-mode

**Comment by Makima0** [comment]
I have a similar problem and cannot input chinese

**Comment by bit9tream** [comment]
@Makima0, I found that it's because vterm buffers are marked read-only, so just by changing `(setq buffer-read-only t)` to `(setq buffer-read-only nil)` in `vterm.el` on line 652 I made everything work.
But now I wonder why did devs made vterm buffers read-only.

**Comment by bit9tream** [comment]
@Makima0, PR with the fix was merged
