### ISSUE TITLE
VTerm only uses 8 colors of ANSI pallete

### ISSUE THREAD

**Issue by ioreshnikov** [akermu/emacs-libvterm#481]
Hi!

First of all, thank you very much for the enormous work that you've done. Dealing with terminal windows inside emacs has always been painful for me, but with `vterm` it finally simply works.

I've noticed color inconsistency between vterm and the terminal that I use outside of emacs. It looks like vterm uses only half of the ANSI palette when picking the rgb values (namely, colors indexed 8-15). The lower part of the palette is simply mapped to the upper part.  Please see the screenshot attached:

![Снимок экрана от 2021-01-15 09-54-13](https://user-images.githubusercontent.com/1098912/104704357-d936a200-5718-11eb-8409-45954b7bcbc5.png)

Terminal hovering over emacs displays the full ANSI palette. In the left window inside the emacs you can see that the vterm colors have been set up properly inside the theme. However, on the right the same color test running inside vterm shows only 8 colors out of 16. In both vterm and gnome-terminal `$TERM` is set to `xterm-256color`.

Is this a configuration issue, and if so, how do I fix it?

Best,
Ivan

**Comment by peterbecich** [comment]
I think one solution may be supporting https://github.com/atomontage/xterm-color , though I don't know if this is possible: https://github.com/akermu/emacs-libvterm/issues/557

**Comment by ioreshnikov** [comment]
@peterbecich Now I am more confused than before :) It clearly works for alect theme, but when I read the source here

https://github.com/alezost/alect-themes/blob/master/alect-themes.el

there are zero mentions for `vterm-` in theme itself. The same is true for Darktooth theme as well.

I don't think it's connected to the theme in my case. Granted, I am using my own version of solarized, but in the attached screenshot in the left-most window one can clearly see, that `vterm-get-color` correctly maps ansi color numbers to the hex defined in my theme, all 16 of them. The $TERM variables in both the terminals is the same. However, the output of `colortest.sh` is using only half the colors defined in the theme.

There's something weird going on with the color mapping.

**Comment by jixiuf** [comment]
https://github.com/alezost/alect-themes/blob/89560047934c236d05ea6b911c0c63702a8e06f3/alect-themes.el#L1666
https://github.com/akermu/emacs-libvterm/blob/2681120b770573044832ba8c22ccbac192e1a294/vterm.el#L414

```
(defface vterm-color-red
  `((t :inherit term-color-red))
  "Face used to render red color code.
The foreground color is used as ANSI color 1 and the background
color is used as ANSI color 9."
  :group 'vterm)
```

**Comment by ioreshnikov** [comment]
@jixiuf I actually figured it out. The inconsistency I see is a combination of both how my `colortest.sh` is written --- bright colors are printed through escape sequence for bold text --- and the way Gnome Terminal handles bold --- by additionally highlighting bold text with upper part of the palette.

Everything is fine as far as color mapping goes. It's just we lack one additional feature that seems to be quite common among terminal emulators. I will close this issue and create a FR instead.

Thank you, again, for all the work you do.
