### ISSUE TITLE
C-m sends incorrect command

### ISSUE THREAD

**Issue by antoine-levitt** [akermu/emacs-libvterm#491]
C-m sends a command that bash doesn't seem to be able to parse. Fixed locally with
(define-key vterm-mode-map (kbd "C-m") 'vterm-send-return)

**Comment by jixiuf** [comment]
https://github.com/akermu/emacs-libvterm/blob/fb12d7f49e2da121d9b17ed583d269166e0da087/vterm.el#L568

` (kbd "C-m") ` == `(kbd "RET")`

**Comment by antoine-levitt** [comment]
That's very weird because something bound it to vterm-send-C-m instead of send-RET. Even now in my session I get vterm-send-C-m is an interactive Lisp function in ‘vterm.el’, but I can't find its definition. Anyway, sorry this doesn't seem to be reproducible, will reopen if I figure it out.
