### ISSUE TITLE
Tmux does not display bottom bar or copy-mode indicator

### ISSUE THREAD

**Issue by rakanalh** [akermu/emacs-libvterm#5]
Hi,

In the description, you advise using tmux. However, when you launch tmux, it doesn't show the bottom information bar nor does it show the copy-mode indicator (when using the copy-mode bound key, for me it's PREFIX+[)

**Comment by rakanalh** [comment]
I can also report that for some reason, hitting Ctrl-A (My tmux prefix) is required twice to activate the prefix. 

I am using GNU Emacs 25.1.1 (x86_64-apple-darwin16.4.0, NS appkit-1504.81 Version 10.12.3 (Build 16D32))
 of 2017-02-19

**Comment by akermu** [comment]
Thanks for the report! It shows the copy indicator for me, but not the status bar. I will investigate. Could you open another issue for the prefix key? Thanks!

**Comment by rakanalh** [comment]
Nevermind the prefix issue, i realized i was outside tmux when i tried this. After double checking, seems like it works.

**Comment by rakanalh** [comment]
![Screenshot](http://i.imgur.com/HPeTusc.png) 
Shows that a bit of the bottom buffer appears to be unused.

**Comment by akermu** [comment]
Hmh, does `(window-body-height)` return the right line count for the window?
