### ISSUE TITLE
A more sophisticated entry point?

### ISSUE THREAD

**Issue by utkarsh181** [akermu/emacs-libvterm#505]
Hi! Thanks for the excellent vterm package.

Current vterm implementation creates a new vterm buffer on successive
call of M-x vterm.  Whereas we can do something more sophisticated by
following eshell-entry point design.

Eshell doc string:
```
(eshell &optional ARG)

Create an interactive Eshell buffer.
Start a new Eshell session, or switch to an already active
session.  Return the buffer selected (or created).

With a nonnumeric prefix arg, create a new session.

With a numeric prefix arg (as in ‘C-u 42 M-x eshell RET’), switch
to the session with that number, or create it if it doesn’t
already exist.
```
One of the use cases of this type of entry point is that we can bind
these function to key binds such as s-\<return\> or s-S-\<return\> and use
to jump to our terminal session whereas in the current scenario
every a new instance of vterm pops up or else we have to follow the
tiring process of switch-to-buffer vterm.

NOTE: following code is taken from eshell.el

Suggested code:

```
(defcustom vterm-buffer-name "*vterm*"
  "The basename used for vterm buffers.
This is the default name used when running `eshell'.

With a numeric prefix argument to `vterm', the buffer name will
be the value of this variable followed by the number.  For
example, with the numeric prefix argument 2, the buffer would be
named \"*vterm*<2>\"."
  :type 'string
  :group 'vterm)


(defun vterm (&optional arg)
    "Create an interactive Vterm buffer.
Start a new Vterm session, or switch to an already active
session.  Return the buffer selected (or created).

With a nonnumeric prefix arg, create a new session.

With a numeric prefix arg (as in `C-u 42 M-x vterm RET'), switch
to the session with that number, or create it if it doesn't
already exist.

The buffer name used for Vterm sessions is determined by the
value of `vterm-buffer-name', which see."
  (interactive "P")
  (cl-assert vterm-buffer-name)
  (let ((buf (cond ((numberp arg)
		    (get-buffer-create (format "%s<%d>"
					       vterm-buffer-name
					       arg)))
		   (arg
		    (generate-new-buffer vterm-buffer-name))
		   (t
		    (get-buffer-create vterm-buffer-name)))))
    (cl-assert (and buf (buffer-live-p buf)))
    (pop-to-buffer-same-window buf)
    (unless (derived-mode-p 'vterm-mode)
      (vterm-mode))
    buf))

```

**Comment by Dieken** [comment]
This breaks doom emacs (+vterm/here),  it can't create new terminal any more...

https://github.com/hlissner/doom-emacs/blob/develop/modules/term/vterm/autoload.el#L59

**Comment by jixiuf** [comment]
does  ( vterm “buffername”) work for you

**Comment by utkarsh181** [comment]
jixiuf <notifications@github.com> writes:

> does  ( vterm “buffername”) work for you 

Hi jixiuf,

To manage buffer with same name if have this config which just put
buffer_name<number> where buffer_name may be same but numbers are always
unique(it's built in):

(use-package uniquify
  :custom
  (uniquify-buffer-name-style 'post-forward-angle-brackets)
  (uniquify-strip-common-suffix t)
  (uniquify-after-kill-buffer-p t))

If we pass argument to vterm func with declaration:

(use-package vterm
  :ensure t
  :custom
  (vterm-kill-buffer-on-exit nil)
  :config
  (defun my-vterm ()
    (interactive)
    (vterm "*vterm*"))
  :bind ("s-<return>" .  my-vterm))

Now if we press s-<return> N times we will be greeted with
vterm<1..N times> N buffers. 

I know changing something this crucial is tough we can also settle with
an alternative entry point also.
-- 
Utkarsh Singh

**Comment by Dieken** [comment]
> does ( vterm “buffername”) work for you

This does work,  `(vterm "buffername")`  or `(vterm vterm-buffer-name)`  both work,  I temporarily use `(vterm t)` which I feel ugly.

I feel the default behaviour of `(vterm)` shouldn't be changed,  it should just create a new term named with `vterm-buffer-name<N>`.   If we want a semantic "create-if-not-existed", that should be `(vterm "buffername")`,   or we have to write this ugly code:

```elisp
(let ((vterm-buffer-name "buffername"))
  (vterm))
```

Or more clean, we just have a keyword argument `:if-existed :no-create` to `(vterm ...)`.

**Comment by jixiuf** [comment]
how about add
```
(defun vterm-new (&optional buffer-name)
  (vterm (or buffer-name vterm-buffer-name))
```
It seems `eshell`  `shell`  `term`  behave similar, starting a new Eshell/Term/Shell session, or switch to an already active
session.

**Comment by Dieken** [comment]
> how about add
> 
> ```
> (defun vterm-new (&optional buffer-name)
>   (vterm (or buffer-name vterm-buffer-name))
> ```
> 
> It seems `eshell` `shell` `term` behave similar, starting a new Eshell/Term/Shell session, or switch to an already active
> session.

If the caller has to change, I would like to keep vterm current status, ask Doom emacs to change from `(vterm)` to `(vterm vterm-buffer-name)`.

**Comment by Dieken** [comment]
> Yubao Liu <notifications@github.com> writes:
> If the caller has to change, I would like to keep vterm current status, ask Doom emacs to change from `(vterm)` to `(vterm vterm-buffer-name)`.
> You can also add alternate function to keep backward comparability. Also can you please re-open the issue? -- Utkarsh Singh

There is only a `Comment` button, seems I'm not permitted to reopen it.

I think this change is fine to be consistent with eshell/shell/term,  I just don't know what's the best change for callers such as Doom Emacs. When Doom Emacs bumps vterm next time, its `(+vterm/here)` will break if it doesn't update its `autoload.el`.

Other Emacs starter kits that integerate vterm also have to change, that's annoying.

**Comment by utkarsh181** [comment]
Sorry @deb0ch

This issue was closed after the commit c2c2c8a. But I was reading
this as the maintainer closed the issue without even checking the
problem.  There was some mistake on my side.

Regarding incompatability with Doom Emacs +vterm function we should create and 
issue on their bug tracker and even go through Space Emacs vterm module if there is one.

@jixiuf please add a note or tag to the commit as this is an breaking
change in regards to backward compatibility

**Comment by jixiuf** [comment]
> Sorry @deb0ch
> 
> This issue was closed after the commit [c2c2c8a](https://github.com/akermu/emacs-libvterm/commit/c2c2c8afb935c11778388721912250cd1103aaf9). But I was reading
> this as the maintainer closed the issue without even checking the
> problem. There was some mistake on my side.
> 
> Regarding incompatability with Doom Emacs +vterm function we should create and
> issue on their bug tracker and even go through Space Emacs vterm module if there is one.
> 
> @jixiuf please add a note or tag to the commit as this is an breaking
> change in regards to backward compatibility

Could you open a pr for that , My English is poor for writing good documents.

**Comment by deb0ch** [comment]
Hello @utkarsh181, I do not understand why I was mentioned ?

**Comment by Dieken** [comment]
> Hello @utkarsh181, I do not understand why I was mentioned ?

that's a mistake, he meant to mention me :-)

**Comment by ra1nb0w** [comment]
@jixiuf can you re-request the push of https://github.com/hlissner/doom-emacs/pull/4756 now that the bump is done? thank you

**Comment by Dieken** [comment]
this is included in https://github.com/hlissner/doom-emacs/pull/4836, but it’s also not merged😓

**Comment by ra1nb0w** [comment]
Thank you @Dieken . We hope in a soon merge.
