### ISSUE TITLE
Non echo of characters until backspace is pressed

### ISSUE THREAD

**Issue by matteo-l** [akermu/emacs-libvterm#506]
With the last version installed from melpa (vterm-20210305.1522) when I start to type a command at the prompt no character is echoed until i press backspace, when the whole string appears. As a workaround I added a space and a backspace in the definition of `vterm_printf`: `printf "\e]%s\e\\ \b" "$1"` instead of `printf "\e]%s\e\\" "$1"`.

If I didn't make a mistake with `git bisect` 694b79cc56e30658d36cefefbf162d5ad693c362 is the first bad commit.

Emacs: version 27.1, built from source
OS: Ubuntu 20.04

**Comment by jixiuf** [comment]
I don't known how to reproduce the bug， Can you share your .zshrc/.bashrc

**Comment by matteo-l** [comment]
I observe the bug commenting the whole content of /etc/bash.bashrc and leaving only `source ${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh` in ~/.bashrc. `BASH_VERSION` is `5.0.17(1)-release`

**Comment by matteo-l** [comment]
My locale is `it_IT.UTF-8` but also i get the bug also setting `LC_ALL="C"`

**Comment by bradprob** [comment]
Same issue!

**Comment by jixiuf** [comment]
that commit is reverted.

Can you tell me the value of  `locale-coding-system`

**Comment by matteo-l** [comment]
`locale-coding-sistem` is `utf-8-unix`

I'll try the `master` branch ASAP

**Comment by matteo-l** [comment]
`master` works! Thank you

**Comment by matteo-l** [comment]
The last version fixes the bug for me, should I close the issue?
