### ISSUE TITLE
Skeleton Pair not working

### ISSUE THREAD

**Issue by Ossifragus** [akermu/emacs-libvterm#507]
If I have skeleton-pair for an character, I cannot input that character in vterm and I got the following message:
_Buffer is read-only: #<buffer *vterm*>_

For example, if I have the following in my .emacs file

> (setq skeleton-pair t)
> (global-set-key (kbd "(") 'skeleton-pair-insert-maybe)

I got the following message if I enter `(`

> Buffer is read-only: #<buffer *vterm*>

**Comment by Sbozzolo** [comment]
You cannot directly insert a character into a vterm buffer, you have to use the `vterm-send-string` function that guarantees that the information is sent to the shell beneath the buffer. I don't think would be trivial to fix `skeleton` to use with vterm at the moment, but I don't know much about the package.

**Comment by Ossifragus** [comment]
Thanks @Sbozzolo for the clarification. I see the problem and will disable skeleton-pair for the vterm buffer.

**Comment by wenjie2wang** [comment]
IMHO, having an option to enable users to insert matching delimiters would be great because `vterm` can also be used as REPL by some other packages such as `julia-repl`.

FYI, my temporary workaround is as follows:

```elisp
(define-key vterm-mode-map (kbd "(")
  '(lambda () (interactive)
     (vterm-send-string "()")
     (vterm-send-left)))
(define-key vterm-mode-map (kbd "{")
  '(lambda () (interactive)
     (vterm-send-string "{}")
     (vterm-send-left)))
(define-key vterm-mode-map (kbd "\"")
  '(lambda () (interactive)
     (vterm-send-string "\"\"")
     (vterm-send-left)))
(define-key vterm-mode-map (kbd "'")
  '(lambda () (interactive)
     (vterm-send-string "''")
     (vterm-send-left)))
(define-key vterm-mode-map (kbd "`")
  '(lambda () (interactive)
     (vterm-send-string "``")
     (vterm-send-left)))

(defun my-vterm-remove-empty-pairs ()
  "Remove right-char for empty pairs in vterm."
  (if (or (and (char-equal (following-char) ?\)) (char-equal (char-before) ?\())
          (and (char-equal (following-char) ?\}) (char-equal (char-before) ?\{))
          (and (char-equal (following-char) ?\]) (char-equal (char-before) ?\[))
          (and (char-equal (following-char) ?\") (char-equal (char-before) ?\"))
          (and (char-equal (following-char) ?\') (char-equal (char-before) ?\'))
          (and (char-equal (following-char) ?\`) (char-equal (char-before) ?\`)))
      (vterm-send-C-d)))
(advice-add 'vterm-send-backspace
            :before (lambda () (my-vterm-remove-empty-pairs)))
```

**Comment by Ossifragus** [comment]
Many thanks @wenjie2wang Your solution works greatly for me.
