### ISSUE TITLE
Laggy send key with repetition.

### ISSUE THREAD

**Issue by akoppela** [akermu/emacs-libvterm#515]
Hi. Thank you very much for vterm for emacs.
I'd like do understand what is wrong. I'm on MacOS and use emacs from terminal. I have key repeat set to fastest value. In vterm if I press and hold arrow up emacs hangs for a while (depends on how long I held it). I've tested it in GUI and it works correctly. How can I debug it further?

**Comment by akoppela** [comment]
I remaped arrow keys to use `vterm-send-up/down/left/right` and it fixed the issue. Closing.

**Comment by chasecaleb** [comment]
Using `vterm-send-up` et al.  is still laggy for me, although I'm on Linux. Does this still work for you @akoppela?

@akermu Do you have any insight?
