### ISSUE TITLE
Lost means to create multiple vterm buffers

### ISSUE THREAD

**Issue by csheaff** [akermu/emacs-libvterm#525]
Hi, I updated my version for the first time in several months, and it appears I've lost the ability to create more than one vterm buffer. i.e. if one vterm buffer is open, running `M-x vterm` would create another which would be named something like \*vterm (2)\*.  However running the command, after updating, just takes me to the original buffer. Any clues or assistance would be appreciated.

**Comment by Sbozzolo** [comment]
I don't know what is the current state, but have a look at
https://github.com/akermu/emacs-libvterm/issues/505

**Comment by dakra** [comment]
If you look at the docstring of `vterm` you see that you have to call it with a non-numeric prefix.

E.g. something like:
```emacs-lisp
(defun ian/new-vterm-instance ()
  (interactive)
  (vterm t))
```

**Comment by ianpan870102** [comment]
> E.g. something like:

Cheers, working like a charm now!
I actually read the documentation and saw the part where it says "nonnumeric prefix", but I was scratching my head trying to find out a nonnumeric prefix -- turns out a simple `t` does the trick.

**Comment by Sbozzolo** [comment]
I personally use `vterm-extra-dispatcher` from
https://github.com/Sbozzolo/vterm-extra.

**Comment by csheaff** [comment]
thanks for the snippet @ianpan870102 , although when using it i do not get the desired behavior with creating a new vterm buffer if one is already open.

**Comment by ianpan870102** [comment]
> although when using it i do not get the desired behavior with creating a new vterm buffer if one is already open.

Are you invoking M-x ian/new-vterm-instance for the creation of a new vterm instance?
