### ISSUE TITLE
Arrow key issue.

### ISSUE THREAD

**Issue by Ergus** [akermu/emacs-libvterm#529]
Hi:

When using emacs from the terminal and I open vterm inside; everything works more or less as expected.

But:

- There is an issue when I try to move with the left and right arrows. If I press the `left`/`right` arrows several times (fast) the cursor moves to the left/right as expected like with `C-b`/`C-f`; in every touch.
- But if I keep the `left`/`right` keys pressed the cursor does not move and stays like frozen there making the terminal feel like unresponsive. 
- Not `C-c` or anything "unfreezes" the terminal.
- After a while trying different keys the cursor jumps somewhere in the line and the terminal unfreezes. Like if it had "accumulated" the "left"/"right" actions and release them all together.
- The issue only happens with the arrows keys, not with `C-b` or `C-f` and only when using emacs inside a terminal.

**Comment by Ergus** [comment]
To explain a bit more on this. When I try `C-h k <left>` it seems like vterm detects something else:

![image](https://user-images.githubusercontent.com/6975176/121924094-e09bbf00-cd3b-11eb-9527-1c0c5a3502a3.png)

While in gui it detects `<left>` normaly expected. Outside vterm emacs detects left properly too.

**Comment by Sbozzolo** [comment]
That looks weird. Are you able to reproduce with a clean configuration?

On my machine, <left> is bound to `vterm-send-left`, as it should be.

**Comment by Ergus** [comment]
The problem seems to be that somehow emacs is sending `M-0` to vterm... I can't explain why. But everywhere else it recognizes left as left. <left> is bound to `vterm-send-left` as it should be; but vterm never receives left but `C-0`

How can I load libvterm with `emacs -Q` it keeps tellign me that I should build the module.

**Comment by Sbozzolo** [comment]
You have to add the folder that contains `vterm-module.so` to the `load-path`. Something along the lines of
`(add-to-list 'load-path "PATH")`. Alternatively, you can cd where vterm is compiled and type `make test`.

**Comment by Ergus** [comment]
> You have to add the folder that contains `vterm-module.so` to the `load-path`. Something along the lines of
> `(add-to-list 'load-path "PATH")`. Alternatively, you can cd where vterm is compiled and type `make test`.

Done!

Yes I can reproduce it in the clean environment.

```
emacs -Q
M-: (add-to-list 'load-path "mypath")
M-x load-file vterm.el
M-x vterm
write something
<left>
```

And `C-h k <left>` shows:

![image](https://user-images.githubusercontent.com/6975176/121966336-c0392800-cd6e-11eb-91b9-72b9ad825532.png)

What terminal are you using?

**Comment by Sbozzolo** [comment]
> What terminal are you using?

I tried with a tty and I was finding the correct behavior. Now, I tried with `xterm` and I can reproduce what you report.

**Comment by Ergus** [comment]
Sorry, probably should have mentioned that it was in a terminal emulator. Not in a tty. Any way, some idea about whats going on?

**Comment by Sbozzolo** [comment]
When running in a terminal, Emacs cannot distinguish some combinations of keys with others (e.g. TAB, <C-i>). Maybe this is another of those instances.

**Comment by Ergus** [comment]
Actually no, because in a terminal emulator `C-h k C-i ` shows `TAB`. So it meand that emacs can't distinguish `C-i` from `TAB`.

But `C-h k <left>` shows `<left>` so emacs identifies `<left>` properly. Except in vterm where it shows `M-O`.

**Comment by Sbozzolo** [comment]
You are right. Actually, all the arrow keys are mismapped. But if you inspect `vterm-mode-map`, you'll find that `left` is correctly bound to `vterm-send-left`.

Would you be able to check if this is a regression? Just pick an older commit, compile the module again, and see if the behavior is still there. At some point, the code to distinguish the symbols on keypads was introduced, maybe it is responsible for this regression.

**Comment by Ergus** [comment]
> You are right. Actually, all the arrow keys are mismapped. But if you inspect `vterm-mode-map`, you'll find that `left` is correctly bound to `vterm-send-left`.
> 
> Would you be able to check if this is a regression? Just pick an older commit, compile the module again, and see if the behavior is still there. At some point, the code to distinguish the symbols on keypads was introduced, maybe it is responsible for this regression.

The issue appears for me for the first time in commit 0b8be604f7f8971e42aa13e5404a4

Actually when I revert that commit the issue disappear. So I supose vterm needs another method to make `vterm-send-key` and `vterm-send-string` wait process output.

**Comment by Ergus** [comment]
Any progress on this?

**Comment by naistran** [comment]
Seems like this is related to #496.

**Comment by Ergus** [comment]
> Seems like this is related to #496.

This looks more like a workaround.
