### ISSUE TITLE
C-a moves the cursor to the begining of the line vs beginning of the prompt

### ISSUE THREAD

**Issue by termlen0** [akermu/emacs-libvterm#534]
Hello,
Within vterm (using zsh and the recommended shell configurations), when I use the C-a key, the cursor does not move to the beginning of the prompt. It moves beyond the prompt all the way to the beginning of the line. From there even using C-f to move forward does not seem to work.
Happy to help provide any output or debug details if it helps.

**Comment by noorul** [comment]
@termlen0 For me this happens only in `VTermCopy` mode. This mode is enabled when I use `C-c C-t`

**Comment by termlen0** [comment]
Thanks @noorul. I wonder if this is because I am using [prelude](https://github.com/bbatsov/prelude.) Are you using any layers over the default emacs install?
I'll test again with a vanilla install and close out the issue if that's the case. Thank you!

**Comment by termlen0** [comment]
looks like prelude has an already open issue for exactly this: https://github.com/bbatsov/prelude/issues/1332. Closing out this issue. Thanks!
