### ISSUE TITLE
How to mark with keyboard?

### ISSUE THREAD

**Issue by deadtrickster** [akermu/emacs-libvterm#54]
Mouse (even scrolling) perfectly works here, usual C-SPC doesn't (well it does but kinda buggy).

**Comment by akermu** [comment]
Do you want to use `C-SPC` like in the terminal? Or do you want to mark things like in a emacs buffer?

**Comment by akermu** [comment]
Can you try if the latest master fixes this issue for you?

**Comment by deadtrickster** [comment]
yea, can't mark with C-SPC

**Comment by seanfarley** [comment]
I'm also running into this problem. How will we be able to mark text that is not just the command but also the output?

**Comment by Sbozzolo** [comment]
It is my impression that if you un-bind the `C-SPC` from `vterm-mode-map`, then you mark everything without any problem.

`(define-key vterm-mode-map (kbd "C-SPC") nil)`

**Comment by seanfarley** [comment]
It's not so much marking text as it is navigating with the keyboard to text that is above or below the current line.

**Comment by Sbozzolo** [comment]
I have removed from `vterm-mode-map` all the motion commands (e.g. `C-n`, `C-f`, ...), and I can move around the buffer as if were plain text, and so mark and copy everywhere. I haven't encountered any problem with this setup yet.

**Comment by Sbozzolo** [comment]
I take it back, now moving the point in the input line is ineffective. 
So, a possible solution to this problem would be to send different commands depending on where the point is. I don't know if this is possible, though.

**Comment by seanfarley** [comment]
Yeah, that was the problem I encountered as well. For instance, `ctrl-r` could mean "search my history" or "search the buffer before current point."

**Comment by akermu** [comment]
This is solved by the `vterm-copy-mode' in #108.

**Comment by seanfarley** [comment]
Ah, this is great!! Works exactly as I want!
