### ISSUE TITLE
Installing vterm prior to magit mysteriously breaks magit

### ISSUE THREAD

**Issue by trev-dev** [akermu/emacs-libvterm#540]
I thought I would open an issue here as this conversation has been going on for a while over at magit and felt it might be helpful to get more eyes on it on the vterm side of things.

References: 
* https://github.com/magit/with-editor/issues/86
* https://github.com/magit/magit/issues/4465

Long story short if I delete my `~/.emacs.d/elpa` directory and re-order my config to install `(use-package :ensure t)` magit first, magit does not break. If vterm is installed first, for some reason magit's `with-editor.el` tilts.

**Comment by Sbozzolo** [comment]
Can you please summarize what is the problem and what was found so far?

**Comment by trev-dev** [comment]
@Sbozzolo I would love to, but unfortunately it's a bit all over the place. https://github.com/magit/with-editor/issues/86 has everything anyone has tried in a thread.

What's consistently happening for me and a couple other people here is that if vterm is installed with package.el before magit, magit (specifically with-editor.el) breaks.

The errors look like this, repeated 41ish times for every package part of magit that tries to (require 'with-editor).  
```
In toplevel form:
magit-remote.el:30:1:Error: Loading file /Users/yuezhu/.emacs.d/elpa/with-editor-20201030.1232/with-editor.elc failed to provide feature ‘with-editor’
```
Inexplicably if you remove _just_ magit and attempt to re-install it, it stays broken.

If the elpa folder is removed and the install order is changed to magit first, then vterm, things go smoothly.
