### ISSUE TITLE
vterm can't create ssh using docker-tramp

### ISSUE THREAD

**Issue by yanglimingcn** [akermu/emacs-libvterm#542]
vterm can't create ssh using docker-tramp
Messages below
Tramp: Opening connection for root@297953d29648 using docker...
Tramp: Sending command ‘exec docker  exec -it -u root 297953d29648 sh’
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on ‘297953d29648’
Tramp: Opening connection for root@297953d29648 using docker...done

**Comment by jixiuf** [comment]
It works when 
```
(setq vterm-shell "/bin/sh")
```
