### ISSUE TITLE
vterm over tramp/ssh broken

### ISSUE THREAD

**Issue by aport** [akermu/emacs-libvterm#545]
When opening `vterm` over tramp, I now get the following error:

`Symbol's value as variable is void: method`

Appears to be introduced in commit b1a6d1ce566

**Comment by jixiuf** [comment]
tell me your emacs version

**Comment by aport** [comment]
Apologies for not including

`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0) of 2021-08-31`

I built from `feature/pgtk` branch commit `4c49ec7f865bdad1629d2f125f71f4e506b258f2`
