### ISSUE TITLE
vterm-kill-buffer-on-exit doesn't kill buffer

### ISSUE THREAD

**Issue by dangoncalves** [akermu/emacs-libvterm#553]
Hello,
I installed libvterm through my package manager (Fedora 35 - libvterm 0.1.4) ands emacs-libvterm through melpa (version 20210908.640). Emacs is just a vanilla emacs installed from my package manager.

As mentionned in subject, vterm-kill-buffer-on-exit doesn't kill the vterm buffer.

**Comment by Sbozzolo** [comment]
Sorry for the (embarrassingly) long time to get back to you. 

> As mentionned in subject, vterm-kill-buffer-on-exit doesn't kill the vterm buffer.

Can you please elaborate? The default behavior should be that when you leave your shell (e.g., with `C-d`), the vterm buffer is closed. Are you finding a different behavior?

**Comment by dangoncalves** [comment]
> Sorry for the (embarrassingly) long time to get back to you.
I can't blame you while you're volunteer and do that on your spare time: you've got a life!

A libvterm update from Fedora solved this issue.
