### ISSUE TITLE
How to use for comint and compilation modes?

### ISSUE THREAD

**Issue by sandinmyjoints** [akermu/emacs-libvterm#56]
Is this even possible? It very well may not be but I wanted to ask just in case. Compilation mode gets sluggish for me when I use it to run large suites of unit tests with spec reporter output. I'd love to use the speed of vterm while still enjoying the niceties of compilation mode like hyperlinked errors, if possible.

**Comment by brotzeit** [comment]
I've also been thinking about this since I'm adding libvterm support to remacs. My goal is to eventually replace the emacs terminal emulation, however I'm expecting difficulties as I probably need to port most term related lisp functions. I didn't take a closer look at it, but I expect that it will be a lot of work. However it should be possible for remacs, I guess.

Regarding emacs-libvterm, I think that's not possible but I really don't know.

**Comment by jixiuf** [comment]
a workaround
```
function compile(){
    tmpfile="/tmp/scratch-`/bin/date +%Y-%m-%d_%H-%M-%S`-`uuidgen`"
     `$@ 2>&1  |cat>$tmpfile &`; emacsclient --no-wait --eval "(with-current-buffer (find-file \"$tmpfile\")(setq default-directory \"`pwd`\")(goto-char (point-max))(compilation-mode) (auto-revert-tail-mode))">/dev/null
}

```
```
compile make test
compile go build 
```

**Comment by akermu** [comment]
Currently it's not possible and I also currently don't know how feasible it is. Adding support for the error "links" on top of vterm might be the way to go..

**Comment by deb0ch** [comment]
> Adding support for the error "links" on top of vterm might be the way to go..

Would require parsing all the output of the shell process in elisp, and we all know how performant that would be...

Or maybe, if there was a way that `vterm-module` would do the parsing in C and somehow give Emacs some metadata about what's in the buffer ?

**Comment by deb0ch** [comment]
In any case, having clickable file names would be an awesome feature

**Comment by jixiuf** [comment]
it seems that  just need to enable `compilation-shell-minor-mode` in vterm-mode-hook 
and then you can call `next-error`

**Comment by jixiuf** [comment]
this should be supported after #126 is merged

**Comment by azzamsa** [comment]
what is the status of `comint` support.

It will be great (at least for me) to use `helm-comint-input-ring` as before.

Thank you
