### ISSUE TITLE
vterm not showing zsh symbols

### ISSUE THREAD

**Issue by vijaypanchalr3** [akermu/emacs-libvterm#564]
This is my vterm,
![Screenshot from 2021-12-15 15-03-38](https://user-images.githubusercontent.com/72692300/146161295-31ddcd6a-c3c8-4678-853e-f4c41ff3e341.png)

and here is my system terminal,
![Screenshot from 2021-12-15 15-04-12](https://user-images.githubusercontent.com/72692300/146161492-f707a8da-42e0-431e-b10f-37abca4fb334.png)

**Comment by mkvoya** [comment]
Is that caused by the lack of emoji fonts?
I wonder what if you copy the green arrow (from your system terminal) into the *Scratch* buffer, will that be displayed correctly?

**Comment by rmu0** [comment]
> Is that caused by the lack of emoji fonts? I wonder what if you copy the green arrow (from your system terminal) into the _Scratch_ buffer, will that be displayed correctly?


:wave: I am having the same issue, and no it doesn't
![image](https://user-images.githubusercontent.com/69181766/146195998-e638086c-4233-46f5-acc7-ad4df4685fc2.png)

Probably a font issue

**Comment by Sbozzolo** [comment]
This could be how you set up Emacs to display characters.
It looks like that you see correctly emojis, but not other
symbols. You can find more about the symbol with the
function `describe-char` and you can try to use the
`Symbola` font pack for a wider support for other symbols.

**Comment by vijaypanchalr3** [comment]
but it is 

> 

but it is not a problem for a eshell. Problem exist only in vterm in emacs

**Comment by Sbozzolo** [comment]
What is the missing symbol? (E.g., what is the output of `describe-char` on the symbol in eshell?)

**Comment by sxrthxk** [comment]
Did OP find a fix? Looking for the same.

**Comment by ps-143** [comment]
@vijaypanchalr3  were you able to fix this issue? I think I'm also having the same issue. Also did you try this in term as well?

**Comment by vijaypanchalr3** [comment]
Yes, install icons in terminal. It should fix your issue.
