### ISSUE TITLE
how to change encoding system in vterm ?

### ISSUE THREAD

**Issue by vijaypanchalr3** [akermu/emacs-libvterm#566]
Well, i have default UTF-8 with signature but vterm uses ISO-LATIN. Which can't show certain symbols.

**Comment by Sbozzolo** [comment]
How do you determine that vterm is using iso-latin? Are you using *BSD, or GNU/Linux (or others)?

**Comment by vijaypanchalr3** [comment]
I use Debian stable. 
Well from modeline,
![g919](https://user-images.githubusercontent.com/72692300/146883478-cf53d4b5-5725-4b7c-a480-d97c757e53c1.png)

**Comment by Sbozzolo** [comment]
On GNU/Linux, you should have no problem with UTF8. `vterm` is not visiting a file, so it does not use exactly a coding system. I am not sure why you are seeing iso-latin in the modeline. What happens if you use a clean copy of Emacs and vterm?
