### ISSUE TITLE
Resizing horizontally while htop is running

### ISSUE THREAD

**Issue by brotzeit** [akermu/emacs-libvterm#57]
When I open htop in the terminal and resize the window it only resizes vertically. But when I exit htop and run it again, it gets the correct size of the resized window. Any ideas ?

**Comment by akermu** [comment]
I already track this pack in #33, so I'll close this one. But I tried to debug it a couple of times and I still have no clue what's the issue here. I'll guess it's some weird interaction between the `tty` and how `emacs` interacts with it's file handle.
