### ISSUE TITLE
GNU Guix on wsl2 vterm won't start

### ISSUE THREAD

**Issue by cerealman23** [akermu/emacs-libvterm#571]
I'm running GNU Guix as a an SD on wsl2.  I was able to successfully compile the vterm module, however when running the vterm function nothing happens.  No error message and no debug minibuffer.  I'm not sure what this issue could be as shell term and ansi-term all work, vterm is however giving me issues.

**Comment by Sbozzolo** [comment]
Are you compiling from the sources?

What happens if you try with `make run` in the vterm source directory
(after you compiled it)?

**Comment by cerealman23** [comment]
In the directory ~/.emacs.d/elpa/vterm-20211226.817/build/ when I run make run emacs is launched however vterm still won't load.

**Comment by Sbozzolo** [comment]
I don't know what is going on. Maybe you can try to see if you get an error
by enabling `debug-on-error`.

**Comment by cerealman23** [comment]
I get this error I can't make sense of

`* vterm(nil)
  funcall-interactively(vterm nil)
  call-interactively(vterm record nil)
  command-execute(vterm record)
  counsel-M-x-action("vterm")
  ivy-call()
  ivy-read("M-x " [## c-clear-char-property-fun ada-ref-man lsp-omnisharp-code-structure-request\? locals 0 tramp-compat-exec-path message-all-epg-keys-available-p magit-submodule-update edebug-trace tramp-adb-parse-device-names vterm-yank markdown-xhtml-body-preamble lsp-make-formatting-capabilities lsp-folding-range-limit extend-region-p :filterText ols electric-help-orig-major-mode lsp--check-document-changes-version doom-modeline-eldoc-bar resourceOperations web-mode-warning-face avl-tree--stack-store--cmacro cl-print--preprocess lsp:set-ccls-inheritance-name blue-alt-faint edebug-clear-frequency-count wicon lsp:signature-help-active-signature\? ccls-code-lens-position 0 :tooltip shr-parse-image-data c-mode-var :End Edebug\ All\ Defs test-command & \' tramp-rename-files osx-org-clock-menubar :start-time org-babel-results-keyword muletibetan-2 dont-create tagger-params f-empty\? expired message-send-mail-function ...] :predicate #f(compiled-function (sym) #<bytecode 0xee35dd>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
`

**Comment by cerealman23** [comment]
Heres the error when used on make run it's a lot easier to read.

* vterm(nil)
  funcall-interactively(vterm nil)
  call-interactively(vterm record nil)
  command-execute(vterm record)
  execute-extended-command(nil "vterm" "vterm")
  funcall-interactively(execute-extended-command nil "vterm" "vterm")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by Sbozzolo** [comment]
What is the first line of the traceback? (E.g., `Debugger entered--Lisp error: (void-function mytest)`)

Also, can you try running `vterm` directly from the source directory, you can use something like
`emacs -nw -Q -L $(pwd) --eval "(require 'vterm)" --eval "(toggle-debug-on-error)" --eval "(vterm)"`

**Comment by cerealman23** [comment]
This is what I got `Debugger entered--Lisp error: (wrong-number-of-arguments #<module function Fvterm_new from /gnu/store/a2w57dni5hf3jmxry19dkww90armqv7q-emacs-vterm-0.0.1-0.a670b78/lib/vterm-module.so> 8)`

**Comment by Sbozzolo** [comment]
Okay, I think that there is some inconsistency between your `.el` and your
compiled module. I see from your elpa directory that you are using an older
version of vterm. Commit c138252f2a2c615ad2cd2157e68353da512a4f97 changed
the number of arguments in `vterm_new`. It should work once you update
everything to the last version.

**Comment by cerealman23** [comment]
Even after running guix pull and guix upgrade I can't for the life of me seem to update vterm to a newer commit.  And I am no longer getting error messages when running vterm just nothing happens.  I think I lack understanding of guix to get vterm to properley work right now.  Thanks for your help.

**Comment by Sbozzolo** [comment]
If I look at line 23203 in [emacs-xyz.scm](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/emacs-xyz.scm?id=e658c8d783f48bf17a90e4c72ceb802ef231ecf0#n23203) I see that the referenced commit is a670b78, so that's probably what you are installing.

**Comment by cerealman23** [comment]
Okay I understand although I'm not sure how to change that package to a newer commit.

**Comment by Sbozzolo** [comment]
I don't use Guix, so I cannot help you, but you can always ask the maintainer of the derivation to update the version of vterm that they distribute.

**Comment by cerealman23** [comment]
Okay sounds good I'll see what I can do.  Thanks for your help.
