### ISSUE TITLE
Arrow keys not working properly

### ISSUE THREAD

**Issue by Ergus** [akermu/emacs-libvterm#575]
Hi:

When using emacs in a terminal and I use the arrows keys, vterm is detecting arrow keys wrongly.

To reproduce:
```
emacs -Q -nw --eval "(require 'vterm)" --eval "(vterm)"
C-h k
press key <up> 
```
The *help* window shows: `M-O runs the command vterm-send-M-O (found in vterm-mode-map),....`

(similar issue happens with the other arrow keys).

From lossage  I get this for the `<up>` arrow:
```
ESC O			;; vterm-send-M-O
 A			;; vterm--self-insert
```

while in other modes I get:
```
ESC O A       ;; previous-line
```

On the other hand `C-<up>` works properly: `C-<up> runs the command vterm-send-up...`

And get this from lossage
```
 ESC [ 1		; 5 A ;; vterm-send-up
```

I checked for the other modes and they work properly, so this is somehow some specific details vterm enables.

Any help?

PD: As a work around I unbound `M-O` from `vterm-mode-map`... but this seems to be a temporal solution. In general when emacs is running in `-nw` I think it is wrong to bind `[M.C]-[A-Z]` keys. Normaly the terminals don't use them directly.

**Comment by dispensable** [comment]
Same issue here ...
