### ISSUE TITLE
Is it possible to pass messages back to the shell?

### ISSUE THREAD

**Issue by indigoviolet** [akermu/emacs-libvterm#577]
Can I get the return value from an Emacs function "back" into the shell? For example, can I execute something like `vterm_cmd window-width`, and receive the result instead of it showing in the minibuffer like `message`?

**Comment by Sbozzolo** [comment]
Yes, as said it is not easy, so the best you can probably hope for is some ugly workaround. If your goal is to have a variable WIDTH in your shell that contains the value of window-width, I would mostly attack the problem from the Emacs side. I would write a function that uses a regular expression to capture the name of the variable (vterm knows where the prompt ends, so you can match to the end of the line, or to the equal sign), calls the Emacs function I want to call, and uses `vterm-send-string` to run the command `VARIABLE=VALUE` in the next instruction.

I know, this is quite ugly. There's probably a better way, but I cannot think of a much simpler method of the top of my head.

**Comment by indigoviolet** [comment]
ok thanks.
