### ISSUE TITLE
Apply vterm filtering to custom processes

### ISSUE THREAD

**Issue by Silex** [akermu/emacs-libvterm#578]
Hello,

I was wondering if you foresee issues when trying to apply vterm to custom processes?

Basically it looks like if I can replace https://github.com/akermu/emacs-libvterm/blob/master/vterm.el#L715-L728 I should be good to go.

I have current code that calls `start-file-process-shell-command` and I tried naively doing `(set-process-filter process #'vterm--filter)` but that segfaulted :sweat_smile:

**Comment by Sbozzolo** [comment]
`emacs-libvterm` is based on an external library, `libvterm`. When you create a `vterm`, a `Term` object (from `libvterm`) is also created and the pointer to this object is stored in the variable `vterm--term`. I am not surprised you see segfaults when this pointer is invalid.

If you want to change the command, you have to take everything else in vterm-major-mode with you.

**Comment by Sbozzolo** [comment]
Suppose you want to start a python session, what you can do is:
```
(defun my-python-in-vterm (extra-args)
   "Run python in a vterm session with arguments EXTRA-ARGS"
   (vterm-other-window)
   (vterm-send-string (concat "python " extra-args "\n")))

(my-python-in-vterm "-i")
```

Would this fit your use case?

**Comment by Silex** [comment]
That's an interesting idea. I'm exploring vterm's internals for https://github.com/Silex/docker.el/issues/179

My first idea was to adapt vterm-mode so it takes the process from https://github.com/Silex/docker.el/blob/async/docker-core.el#L59-L73, but your idea might work if I'm able to:

1. Hide the prompt?
2. Get the command output?

Basically I need to run commands like:

* `docker container ps --format {{SOMEJSON}}` and parse the JSON output.
* `docker container run -it --rm ubuntu:latest bash` and have a console attached to the never ending process. At the moment I use `shell-mode` but it fails to parse a lot of ansi colors.

**Comment by Sbozzolo** [comment]
Actually, I forgot that we have a `vterm-shell` variable. If you want to start a different process, you can simply set `vterm-shell` to what you want. Again, with `(setq vterm-shell "/usr/bin/python")`, I'd get Python. 

> Hide the prompt?
> Get the command output?

Unfortunately, I don't see any clean way to do this. You would have to hide the prompt on the side your application (docker in this case), while keeping a prompt text property around. This would allow you to extract the output by selecting the region between two "prompts".

**Comment by Silex** [comment]
> Actually, I forgot that we have a `vterm-shell` variable. If you want to start a different process, you can simply set `vterm-shell` to what you want. Again, with `(setq vterm-shell "/usr/bin/python")`, I'd get Python.

Well, I can't pass arguments there can I? docker is not a shell, it's a command like `grep`.

**Comment by Sbozzolo** [comment]
Yes, you can pass arguments. `vterm-shell` is used [here](https://github.com/akermu/emacs-libvterm/blob/a940dd2ee8a82684860e320c0f6d5e15d31d916f/vterm.el#L728), so you can pass all the arguments you want and it will be executed. You can always use a `let` form to change `vterm-shell` locally and add the arguments you want.

Of course, you still need the program to be somehow interactive, which would be for your point 2. So, you could try with something like
```emacs-lisp
(defun my-docker-in-vterm ()
    (interactive)
    (let (vterm-shell "docker container run -it --rm ubuntu:latest bash")
         (vterm-other-window)))
```

**Comment by Silex** [comment]
OMG it works! :partying_face: 

Thanks a lot.

**Comment by Silex** [comment]
@Sbozzolo: 

Please look at https://github.com/Silex/docker.el/blob/master/docker-process.el#L77-L82

I have the weirdest behavior: *sometimes*, vterm still starts with `/bin/bash`. If I edebug the function, then paf it works. Or sometimes if I eval the whole file then it works all the time.

I'm thinking maybe I need to add something like `(eval-when-compile (require 'vterm))` ? I never really understood this byte-compilation thing and how I'm supposed to fix it.

**Comment by Sbozzolo** [comment]
I think you have to require vterm no matter what, not only during the compilation. Otherwise, you will get an error when you try to execute the function (unless, by chance, you opened a vterm buffer before).

**Comment by Silex** [comment]
Well, vterm is optionnal for my package. But I think I found how without ugly `eval-when-compile`:

https://github.com/Silex/docker.el/commit/eecdafd7cb63e4704631b59d0296a38894f5a723

Thanks!
