### ISSUE TITLE
Directory Tracking Does Not Work

### ISSUE THREAD

**Issue by linux40** [akermu/emacs-libvterm#583]
Launch Emacs 27.2 with `emacs -Q -l debug-vterm.el`, execute `M-x vterm`, `cd .config`, and `C-x C-f`, then `find-file` starts at `~/` rather than `~/.config/`. `echo $PS1` does show `\[$(vterm_prompt_end)\]` at the end of the variable.

`debug-vterm.el`:
```
(add-to-list 'load-path "~/.local/share/emacs/elpa/vterm-20211226.817")

(require 'vterm)
```

**Comment by Sbozzolo** [comment]
What is your shell configuration? Are you using any of the provided examples?

**Comment by linux40** [comment]
> What is your shell configuration?

Barely copied from README.

`.profile` just sets `PATH` and `JAVA_HOME`, then `. ~/.bashrc`.

`.bashrc`:
```sh
case $- in *i*) ;; *) return;; esac

vterm_printf() {
    if [ -n "$TMUX" ] && { [ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ] ; }  then
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}

if [ "$INSIDE_EMACS" = "vterm" ]; then
    export EDITOR="emacsclient -s $EMACS_SERVER"
    alias clear='vterm_printf "51;Evterm-clear-scrollback"; tput clear'
    alias clear-screen=clear
    if [ -n "$PROMPT_COMMAND" ]; then
        export PROMPT_COMMAND="$PROMPT_COMMAND"'; echo -ne "\033]0;$(whoami)@$(hostname):$([ ! \"${PWD#$HOME}\" = \"$PWD\" ] && echo -n \~)${PWD#$HOME}\007"'
    else
        export PROMPT_COMMAND='echo -ne "\033]0;$(whoami)@$(hostname):$([ ! \"${PWD#$HOME}\" = \"$PWD\" ] && echo -n \~)${PWD#$HOME}\007"'
    fi
    PS1="$PS1"'\[$(vterm_prompt_end)\]'
fi

if [ "$TERM" = "dumb" ]; then
    PS1="> "
fi
```

**Comment by Sbozzolo** [comment]
I don't immediately see what is the problem. Can you try manually calling the `vterm_prompt_end` function in your shell? 
Can you also try using [this](https://github.com/akermu/emacs-libvterm/blob/master/etc/emacs-vterm-bash.sh) to see if it works?

**Comment by linux40** [comment]
Both calling `vterm_prompt_end` and letting `.profile` source `emacs-vterm-bash.sh` do not work.

**Comment by Sbozzolo** [comment]
I don't know what could be the problem. Could you try to set up directory tracking for a built-in shell, like `ansi-term`? This will tell us if the problem is `vterm` or something else.

**Comment by linux40** [comment]
`ansi-term` works with the same both shell and emacs configurations.

**Comment by linux40** [comment]
Sorry for bother. After deleting the package and reinstall it, the directory tracking works. Probably `vterm-module` failed to compile after a certain upgrade.
