### ISSUE TITLE
invalid characters shown after commit c8ddfed

### ISSUE THREAD

**Issue by aconchillo** [akermu/emacs-libvterm#584]
I'm not really sure how to file this issue but this is something I observed after upgrading to the latest vterm version through `melpa` version `20220416.946` (I made sure I recompiled the module). After this update, some characters are not displayed properly. Before, it was displaying properly.

See these two screenshots (the issue seems to be similar in both cases)

This is from a prompt using powerlinke10k (https://github.com/romkatv/powerlevel10k):

![Screenshot from 2022-04-16 21-10-52](https://user-images.githubusercontent.com/951761/163741789-9867338d-20fa-4906-8643-998b12df5532.png)

This other one is from using nordic tmux plugin (https://github.com/arcticicestudio/nord-tmux):

![Screenshot from 2022-04-17 18-41-08](https://user-images.githubusercontent.com/951761/163741798-d81b1897-0066-4fa1-8a01-32973fdbd67d.png)

I'd be happy to try anything to help.

**Comment by jixiuf** [comment]
Can you share your `~/.p10k.zsh` , I don't use `powerlinke10k` ,I can't see what's wrong with the prompt.
And can you share a screenshots before `20220416.946`

**Comment by aconchillo** [comment]
Of course. This is the config:

[p10k.zip](https://github.com/akermu/emacs-libvterm/files/8503606/p10k.zip)

Here's another screenshot with current melpa version (vterm-20220416.946) during p10k configuration:

![Screenshot from 2022-04-17 21-22-54](https://user-images.githubusercontent.com/951761/163757347-004f1253-615d-4e58-823f-ba0e0a7ec5e6.png)

I was able to download to previous version (vterm-20220412.1140) which uses commit `a2f2286c40725244257f46d3a27a730e73f9f596` and this is how it looked like:

![vterm-20220412 1140](https://user-images.githubusercontent.com/951761/163757475-2f7afa76-073e-4087-a50f-5f0ad901de5a.png)

**Comment by aconchillo** [comment]
It works. Thank you!
