### ISSUE TITLE
libvterm is archived

### ISSUE THREAD

**Issue by avishefi** [akermu/emacs-libvterm#588]
libvterm is archived, is there an alternative?

**Comment by Sbozzolo** [comment]
I created a mirror of the baazar repo here: https://github.com/Sbozzolo/libvterm-mirror

**Comment by avishefi** [comment]
@Sbozzolo I don't see the mirror being used in emacs-libvterm, is that planned?

**Comment by Sbozzolo** [comment]
Ideally yes. I am watching my mirror to see if it is reliable or not. The mirror uses GitHub actions to convert from a bazaar to a git repo, but the process is not exactly clean and robust...
