### ISSUE TITLE
Newest libvterm.so breaks 256 color terminal

### ISSUE THREAD

**Issue by pataquets** [akermu/emacs-libvterm#589]
Using current, latest `vterm.el` package works fine. However, color has broken.
`TERM=xterm-256color`.
Colored test output belongs to `colortest-256` program, from `colortest` Ubuntu Bionic's package repos.
Reverting to previous `libvterm.so` library solves the problem.

Before:
![libvterm1](https://user-images.githubusercontent.com/1286254/165502717-56f5be89-44c3-490a-9ce4-87a751c6d8e1.png)

After:
![libvterm2](https://user-images.githubusercontent.com/1286254/165502740-83e8518e-0cb3-48ab-910e-a044f35e07cd.png)

Maybe related with #584.

**Comment by aconchillo** [comment]
@jixiuf FYI: I updated my system with libvterm 0.2 and everything works fine now (after the revert). I was actually experiencing some weird issues with libvterm 0.2 and that commit.

**Comment by pataquets** [comment]
That solved the issue. Thanks!
