### ISSUE TITLE
Which libvterm  is used by emacs-libvterm? And are there any other terminal applications built with it?

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#596]
When searching on Github for _libvterm_, two repos come up:

* `https://github.com/neovim/libvterm` and
* `https://github.com/TragicWarrior/libvterm`

Which one is used by emacs-vterm? I think it is the neovim repo, but this is archived by its owner... 

Also, are there any other terminal apps (apart from emacs) built with libvterm?

**Comment by Sbozzolo** [comment]
`emacs-libvterm` uses the [lbvterm](https://launchpad.net/libvterm) developed by [Paul "LeoNerd" Evans](https://launchpad.net/~leonerd). A mirror is available on [GitHub ](https://github.com/Sbozzolo/libvterm-mirror).

A reference implementation of a terminal with libvterm is [pangoterm](https://www.leonerd.org.uk/code/pangoterm/)

**Comment by halloleo** [comment]
Thanks, @Sbozzolo. Good to know.

Just as an aside, the link in the [README](https://github.com/akermu/emacs-libvterm/blob/master/README.md) points to the neovim repo. I'm happy to update it to Evan's repo.
