### ISSUE TITLE
REPLs running in vterm under bash miss the last output when they wait for input

### ISSUE THREAD

**Issue by halloleo** [akermu/emacs-libvterm#598]
When I run REPLs like the Haskell REPL `ghci`  under bash in emacs-vterm ,  I get the waiting cursor _before_ the last line of the output can be printed to the buffer. To explain this I show here how calling ghci look in a normal terminal app like XTerm or iTerm:

```
$ ghci
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Prelude> _
```

(The cursor is waiting at the `_` character - _after the prompt is printed.)

In emacs-vterm I see this:

```
$ ghci
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
_
```

The prompt `Prelude> ` Is only printed later, when input was accepted with return.

Any idea why this happens and how I can fix it?

**Comment by mekeor** [comment]
this happens to me, too. i use zsh. i'd thus guess that it's shell-agnostic.

**Comment by jjdosa** [comment]
I am having the same issue. Has any solution been found yet?

**Comment by halloleo** [comment]
> this happens to me, too. i use zsh. i'd thus guess that it's shell-agnostic.

Definitely shell-agnostic. I am using mainly xonsh (and tested this only for reference  under bash) -- and it happens in both shells.

**Comment by jixiuf** [comment]
Could you try #617

**Comment by halloleo** [comment]
Sure. But I guess the versio  with that fix is not on melpa yet, right? What is the best way to test this?

**Comment by jixiuf** [comment]
the diff is small https://github.com/jixiuf/emacs-libvterm/commit/6f49cae411df76988fc7dfa8e19cc76a17bd8c1a

just add a char `=` in `vterm-control-seq-regexp`

**Comment by halloleo** [comment]
Cool. Just tried it -- and it seems to work! 

Fantastico! Thanks a lot!

**Comment by jjdosa** [comment]
Installing the most recent commit of `emacs-libvterm` worked for me. Thanks a lot here too!
