### ISSUE TITLE
Is it possible to get electric pair mode working in vterm buffers?

### ISSUE THREAD

**Issue by atanasj** [akermu/emacs-libvterm#608]
Is it possible to get electric pair mode working in vterm buffers?

**Comment by Sbozzolo** [comment]
No, I don't think that there's any easy use to use `electric-pair-mode` with vterm. Your best bet is probably to write your own functions to replicate the features you are interested in having.

**Comment by atanasj** [comment]
Thanks. I've moved back to `zsh` which can do this via plugins. So, although I don't get completion via `corfu`, good enough with the other plugins and `fzf`. 😃
