### ISSUE TITLE
Error when kill vterm buffer 

### ISSUE THREAD

**Issue by SteamedFish** [akermu/emacs-libvterm#63]
* set `(setq-default vterm-exit-functions #'kill-buffer)`
* Open vterm buffer
* press <kbd>C-d</kbd> to kill the buffer
* Emacs gives the following error:

   ```
   Error running timer ‘vterm--delayed-redraw’: (error "Selecting deleted buffer") 
   ```

**Comment by akermu** [comment]
Can you give me an example which works with `emacs -Q`? Because I cannot reproduce the issue here.

By the way if you use `add-hook` to add this functionality you can add multiple functions:

```elisp
(add-hook 'vterm-exit-functions (lambda () (kill-buffer)))
```

**Comment by SteamedFish** [comment]
I can reproduce it with recent Emacs macOS version from https://emacsformacosx.com, with both the most recent commit(0a78fe1653e405da26ae305c74b6df960ad44624) and an older commit(777d215db8d94746fe555ec2f8e794e78fb504dc), and with the following minimal configrations:

```lisp
(add-to-list 'load-path "~/emacs-libvterm/")
(setq-default vterm-exit-functions #kill-buffer)
;; (add-hook 'vterm-exit-functions #'(lambda () (kill-buffer)))
(require 'vterm)
```

Use `M-x vterm` to open a vterm buffer and then press <kbd>C-d</kbd> will result the following:

![image](https://user-images.githubusercontent.com/69167/51878370-62c4fc00-23aa-11e9-9884-ddd957afa103.png)


I also tried with the `add-hook` configuration instead of the `setq` one, which result the following:

```
error in process sentinel: run-hook-with-args: Wrong number of arguments: (lambda nil (kill-buffer)), 1
error in process sentinel: Wrong number of arguments: (lambda nil (kill-buffer)), 1
```

**Comment by jixiuf** [comment]
```
(defun vmacs-auto-exit(buf) ;;need one param
  (when buf (kill-buffer buf)))

(add-hook 'vterm-exit-functions #'vmacs-auto-exit)

```
try this

**Comment by SteamedFish** [comment]
> ```
> (defun vmacs-auto-exit(buf) ;;need one param
>   (when buf (kill-buffer buf)))
> 
> (add-hook 'vterm-exit-functions #'vmacs-auto-exit)
> ```
> try this

I tried with both your code and the following:

```lisp
(add-hook 'vterm-exit-functions #'(lambda (buf)
                                      (when buf (kill-buffer buf))))
```

Both works. But the error `Error running timer ‘vterm--delayed-redraw’: (error "Selecting deleted buffer")` still exists.

**Comment by SteamedFish** [comment]
I can reproduce the same error under ArchLinux and emacs 26.1-2.

**Comment by cullan** [comment]
I was getting the same error. It is resolved for me with the latest master.

**Comment by SteamedFish** [comment]
It has been fixed, thanks
