### ISSUE TITLE
vterm_prompt_end() - bash vs zsh

### ISSUE THREAD

**Issue by doolio** [akermu/emacs-libvterm#635]
In the [README](https://github.com/akermu/emacs-libvterm#directory-tracking-and-prompt-tracking), you define the `vterm_prompt_end()` function for both `zsh` and `bash`. The only difference being the trailing `;` in the `zsh` version. Am I right in thinking these could be identical and that the presence/absence of the `;` in this case makes no difference?

`zsh`
```zsh
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}
```
vs `bash`
```bash
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}
```
Then in terms of the function itself does it have to contain elements of the existing `$PS1` at all? That is could it simply be the following:
```bash
vterm_prompt_end() {
    vterm_printf "51;A"
}
```
and then just include it as follows: `PS1=$PS1'\[$(vterm_prompt_end)\]'`?

Thanks for your time and this package.

**Comment by Sbozzolo** [comment]
Yes, I think that the semicolon is unimportant. 
```bash
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}
```
What this function is doing is (1) pushing some pieces of information that are used for shell tracking, (2) marking the end of the prompt. If you remove everything and only keep `51;A`, you will lose the ability to track directory in your shell.

**Comment by doolio** [comment]
Grazie Gabriele. I'd be happy to update the README if you like. Is it more accurate that the semi-colon is present or not? Sorry, I'm just learning to programme myself. In any case, I think we can close this issue.

**Comment by Sbozzolo** [comment]
The semicolon is unnecessary. If you want to remove it, please go ahead.

**Comment by doolio** [comment]
OK, submitted PR #637 for consideration.
