### ISSUE TITLE
Run last command from other buffer

### ISSUE THREAD

**Issue by ChoppinBlockParty** [akermu/emacs-libvterm#647]
I have a key binding that runs last command in a last shell buffer used. How can I have the same with vterm buffer? Thank you.

**Comment by Sbozzolo** [comment]
Assuming you are using a POSIX shell and that you immediately append all your commands to history (e.g., as zsh does by default, iirc), you could use something like this
```emacs-lisp
(defun vterm-execute-last-command-in-history ()
    (interactive)
    (vterm-send-string " fc -e : -1\n"))
```
The key insight is taken from https://unix.stackexchange.com/a/147608.

**Comment by ChoppinBlockParty** [comment]
Thank you. But I have extended a bit with taking care of  the cursor position and making it to emulate the manual actions instead of command.

```lisp
   (defun my-vterm-run-last-command ()
  "Run last command in shell mode."
  (interactive)
  (let ((proc (get-buffer-process (current-buffer))))
    (unless (and proc
                 (>= (point) (marker-position (process-mark proc))))
      (goto-char (point-max)))
    (vterm-send-key "<up>")
    (vterm-send-return)))
```
