### ISSUE TITLE
Cursor is not allowed to be placed beyond some character

### ISSUE THREAD

**Issue by ChoppinBlockParty** [akermu/emacs-libvterm#649]
I am using vterm with evil, latest evil, emacs 28.2, latest vterm. I have a lot of problems where I cannot bring cursor at a position, for example to the end of the line. I noticed this chiefly happens when the command is a previous command, chosen by up arrow. I have to retype the whole command if I have to modify a previous command((. I wonder does anyone have such problems?

**Comment by Sbozzolo** [comment]
Do you mean with something like `C-a`, `C-e`?

**Comment by ChoppinBlockParty** [comment]
> Do you mean with something like `C-a`, `C-e`?

Yeah, I chose a previous command via `[up]` and try to modify it.

**Comment by Sbozzolo** [comment]
This sounds like due to some other packages/configurations, maybe you can try bisecting your config to find the origin of the problem.

**Comment by ChoppinBlockParty** [comment]
Yeah, my zsh config has vi enabled, seems like this messes up vterm.

To fix added 
```
if [[ -z $INSIDE_EMACS ]]; then
  bindkey -v
fi
````
