### ISSUE TITLE
Feature Request: make cmake dependency optional

### ISSUE THREAD

**Issue by bymoz089** [akermu/emacs-libvterm#653]
`cmake` is not needed to compile `vterm-module.so`. One can simply do:

    gcc -fPIC -shared elisp.c utf8.c vterm-module.c -o vterm-module.so -l vterm

to compile this library in `vterm-directory`.

At the moment I created an `:around` `advice` to function `vterm-module-compile` prior to loading file `vterm.el`. This new function removes the cmake check and replaces the cmake call with above compile command.

It would be nice if the compile command can be customized, in order to make cmake dependency optional.

(in any case, this ticket is an hint, that `cmake` is no essential dependency)

**Comment by Sbozzolo** [comment]
I'd say that `cmake` is not an essential dependency if you know exactly what and where you are compiling and have all the other dependencies. For instance, one of the thing that `cmake` does in `emacs-libvterm` is to fetch the source code of library if it is not available. I'd also say that the compile command can already be customized. `vterm.el` only checks if `vterm-module` is compiled. If you want to compile `vterm-module` by without `cmake`, you are free to do so, and `vterm.el` will never bother you (as long as you compile it before loading `vterm`). For instance, you could have something like this in your `init.el`:
```emacs-lisp
(unless (require 'vterm-module nil t)
  (your-function-to-compile-vterm))
```
where the function calls a process with your compilation command.
