### ISSUE TITLE
windmove vs. vterm: overriding C-<up>/<down>/<left>/<right>

### ISSUE THREAD

**Issue by ontheair81** [akermu/emacs-libvterm#658]
Disclaimer: Not an issue, just kindly asking for help ;-)

Most of the time I use several windows in a frame. For quick navigating through windows I use `windmove`, with `C-<arrow-keys>` as keybinding.

But when working in a window containing vterm, `C-<arrow-keys>` seems to be sent to the running process, so can not be used to navigate windows.
Is there a way to change this?

I am aware that the use of `vterm-copy-mode` makes vterm a "normal Emacs buffer" where windmove works as expected. Still, I would like `C-<arrow-keys>` not to be send to the running process in general.

Any help is highly appreciated!

**Steps to reproduce**

1. Configure `windmove` with `C` as keybinding
```
(when (fboundp 'windmove-default-keybindings)
(windmove-default-keybindings 'control))
```
2. Navigating through windows works with `C-<arrow-keys>` in most modes.
3. As soon as a window with vterm is highlighted, windmove with `C-<arrow-keys>` does not work anymore.

**Comment by Sbozzolo** [comment]
I think this should work:
```emacs-lisp
(add-hook 'vterm-mode-hook (lambda () (local-set-key (kbd "C-<up>") 'windmove-up)))
```

**Comment by ontheair81** [comment]
That works great, thank you very much for your help!
