### ISSUE TITLE
Make error on Ubuntu

### ISSUE THREAD

**Issue by ztlevi** [akermu/emacs-libvterm#66]
I got the following issue when building on Ubuntu 18 with `sudo apt install libvterm-dev` installed.

```
~/emacs.d/.local/packages/elpa/vterm-20190219.1419/build
➜    make

[  8%] Performing update step for 'libvterm'
[ 16%] No configure step for 'libvterm'
[ 25%] Performing build step for 'libvterm'
LINK libvterm.la
/home/ztlevi/anaconda3/bin/libtool: 1: eval: /tmp/build/80754af9/libtool_1538243245774/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: not found
Makefile:58: recipe for target 'libvterm.la' failed
make[3]: *** [libvterm.la] Error 127
CMakeFiles/libvterm.dir/build.make:110: recipe for target 'libvterm-prefix/src/libvterm-stamp/libvterm-build' failed
make[2]: *** [libvterm-prefix/src/libvterm-stamp/libvterm-build] Error 2
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/libvterm.dir/all' failed
make[1]: *** [CMakeFiles/libvterm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

According to the solution over [here](https://github.com/RcppCore/Rcpp/issues/770), I tried `conda install gxx_linux-64` but it didn't work out. Also, it's weird building emacs-libvterm uses conda binaries.

**Comment by QiangF** [comment]
I got this error on Debian 9:

    q@debian: emacs-libvterm$ make
    Scanning dependencies of target libvterm
    [  8%] Creating directories for 'libvterm'
    [ 16%] Performing download step (git clone) for 'libvterm'
    Cloning into 'libvterm'...
    Note: checking out 'a6293a0e033e7e86c74889b4527787993656883a'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

    git checkout -b <new-branch-name>

    HEAD is now at a6293a0 The F1 to F4 keys should send SS3 rather than CSI when unmodified
    [ 25%] No patch step for 'libvterm'
    [ 33%] Performing update step for 'libvterm'
    [ 41%] No configure step for 'libvterm'
    [ 50%] Performing build step for 'libvterm'
    TBL src/encoding/DECdrawing.tbl
    TBL src/encoding/uk.tbl
    CC src/encoding.c
    make[3]: libtool: Command not found
    Makefile:62: recipe for target 'src/encoding.lo' failed
    make[3]: *** [src/encoding.lo] Error 127
    CMakeFiles/libvterm.dir/build.make:110: recipe for target 'libvterm-prefix/src/libvterm-stamp/libvterm-build' failed
    make[2]: *** [libvterm-prefix/src/libvterm-stamp/libvterm-build] Error 2
    CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libvterm.dir/all' failed
    make[1]: *** [CMakeFiles/libvterm.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by AlphaAlgorithms** [comment]
got the same errors.

**Comment by jixiuf** [comment]
I am trying to reproduce this with this docker image ,found it compile vterm successfully when I run `emacs`.
and I found I am using the `libtool` in  `/usr/bin/libtool`, 
and you use `/home/ztlevi/anaconda3/bin/libtool`
so maybe you need try to  install `libtool-bin` with `apt-get install  libtool-bin` and try again


Dockerfile
```
FROM docker.io/ubuntu:latest
RUN apt-get update 
RUN apt-get -y install software-properties-common # install add-apt-repository command

# http://ubuntuhandbook.org/index.php/2019/02/install-gnu-emacs-26-1-ubuntu-18-04-16-04-18-10/
RUN add-apt-repository ppa:kelleyk/emacs # for emacs26  (default emacs is not compile with module support)
RUN apt-get update

RUN apt-get -y install cmake make git libtool-bin

RUN apt-get -y install emacs26-nox #run emacs26 
RUN mkdir -p ~/.emacs.d/

RUN echo "(require 'package)" > ~/.emacs.d/init.el  
RUN echo "(add-to-list 'package-archives '(\"melpa\" . \"http://melpa.org/packages/\"))" >> ~/.emacs.d/init.el  
RUN echo "(or (file-exists-p package-user-dir) (package-refresh-contents))" >> ~/.emacs.d/init.el  
RUN echo "(package-initialize)" >> ~/.emacs.d/init.el  
RUN echo "(package-install 'vterm)" >> ~/.emacs.d/init.el
RUN echo "(let (vterm-install) (require 'vterm))" >> ~/.emacs.d/init.el

```
build and run 
```
docker build -t vterm .
docker run -t -i vterm
```

**Comment by ztlevi** [comment]
I figure out the problem was the anaconda environment has an alternative libtool and it's default on my shell env. I just need to remove anaconda path from PATH temporarily and everything works fine.

Thank you for the catch up.

**Comment by suzil** [comment]
Got the same problem and I also tried `conda install gxx_linux-64`. I fixed it the same as above by temporarily removing Anaconda from PATH. Maybe it would be worth putting a note about this in the README?

**Comment by ztlevi** [comment]
I agree. Otherwise, a hack to remove `anaconda/miniconda` path from `exec-path` is also acceptable.

**Comment by exp2ipi** [comment]
For anyone hitting this, here's a  path-remove function:

```
path_remove ()  { export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }
```

**Comment by SreenivasVRao** [comment]
hi, I'm sorry I don't follow your comment @exp2ipi 

I have the same error. My path variable is:
```
/home/sreenivas/anaconda3/bin:/home/sreenivas/anaconda3/condabin:/home/sreenivas/.pyenv/bin:/home/sreenivas/bin:/home/sreenivas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:~/doom-emacs/bin
```

**Comment by helblazer811** [comment]
This worked well for me. 
`conda install gxx_linux-64`

https://github.com/RcppCore/Rcpp/issues/770
