### ISSUE TITLE
Error (use-package): Failed to install vterm: https://melpa.org/packages/vtermlibtool-bin-20230217.228.tar: Not found

### ISSUE THREAD

**Issue by serafdev** [akermu/emacs-libvterm#671]
I'm trying to install the vterm package from melpa and it seems like the installation files are unavailable. I tried that url on my browser and it gave me 404

Is it an issue with Melpa or is something broken with the package configuration?

All I added is:

```elisp
(use-package vterm)
```

Thanks in advance!

**Comment by Sbozzolo** [comment]
Which url?

**Comment by serafdev** [comment]
@Sbozzolo no it's fixed now, I think I removed the melpa package from my config by mistake so it didn't refresh for a long time

I ran refresh-package manually and added the packages back

Thanks for checking!
