### ISSUE TITLE
Working directory tracking does not work

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [akermu/emacs-libvterm#675]
When I open a `vterm` (`0.0.2` from GNU Guix) in Emacs (`GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)` also from GNU Guix) the current directory of that vterm always is the one I started it in. When changing directory using for example `cd` or `pushd`, the directory change is not tracked.

This is a nuisance for example when I navigate into a directory that is a git repository and then try to use magit `C-x g` (for git status), but since the working directory tracking did not work, magit thinks I am still inside the directory, in which I initially opened the vterm, not in the directory, to which I navigated using `cd` or `pushd`. To fix this, I have to open a new vterm where my repository is. **edit:** I also cannot open a new `vterm` from the old `vterm` obviously, since that one still has the wrong working directory. Often I need to open a `dired` to go to the correct directory and _then_ open a new `vterm`.

**Comment by Sbozzolo** [comment]
Directory tracking has to be set up manually, and the readme contains
information about it. Have you check that out?

**Comment by ZelphirKaltstahl** [comment]
My bad. I already had `vterm_printf` in my `.bashrc`, but not the following:

```sh
vterm_prompt_end(){
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}
PS1=$PS1'\[$(vterm_prompt_end)\]'
```

Somehow I misread the readme and did not think I need that or that it is connected to directory tracking.
