### ISSUE TITLE
Question: Helm Integration

### ISSUE THREAD

**Issue by Bee-Mar** [akermu/emacs-libvterm#68]
First off, bravo on this project! I have high hopes for this to be ultimate terminal emulator for Emacs. I do have one question though, how might the current directory the terminal is in be integrated with things like helm (this may very well be out of your control, and fall under the responsibility of those other packages)?  Also, I understand this is still in the somewhat early stages of the project, but I was just curious if there are any plans, or if there's already something that can be set to allow for that integration. Just so it's clear, right now with multi-term, if I `cd` into, say `~/Downloads`, I can run `helm-find-files`, and helm's current directory will be `~/Downloads`. 

Once again, this is awesome, and will be watching the progress!

**Comment by jixiuf** [comment]
see #55
