### ISSUE TITLE
can I create a vterm buffer and immediately run a command?

### ISSUE THREAD

**Issue by dwang20151005** [akermu/emacs-libvterm#687]
I had a function that would prompt me for a command and then run it in a new vterm.  However, my function relied on dynamic rebinding of `vterm-shell` which has since become lexical.  Is there any interest in supporting this mode of operation upstream?

This let me use my emacs a little like screen or tmux, easily managing inferior processes like htop or ncdu that present complex text UIs.  

I preferred typing into a `read-shell-command` prompt over typing into a vterm buffer after the shell is running, because

- dabbrev completion using `M-/` works out of the box (very handy if I have a hex identifier on my screen somewhere)
- in general editing is more intuitive (I use evil mode)
- don't have to wait for the shell (my zshrc is nontrivial)

My (no longer working) function:

``` 
(defun wang/vterm-run (command)
    "run a command in a vterm

Prompt for a command, with completion, if COMMAND is nil.

Close the vterm buffer when COMMAND exits."
    (interactive (list (read-shell-command "run in vterm: " nil nil)))
    (let ((vterm-shell command)
          (vterm-buffer-name (format "*vterm: %s*" command)))
      (vterm)))
```

**Comment by Sbozzolo** [comment]
`vterm` has used lexical binding since its publication to MELPA in 2019 and I think your function should work (it does on my Emacs 28.3). What was the breaking change?

**Comment by dwang20151005** [comment]
Thanks, you made me realize I was wrong to blame `vterm-shell`.  It was only the `vterm-buffer-name` which causes the
`apply: Defining as dynamic an already lexical var`

error I was seeing.  So this works for me:
```  (defun wang/vterm-run (command)
    "run a command in a vterm

Prompt for a command, with completion, if COMMAND is nil.

Close the vterm buffer when COMMAND exits."
    (interactive (list (read-shell-command "run in vterm: " nil nil)))
    (let ((vterm-shell command)
          ;(vterm-buffer-name (format "*vterm: %s*" command))
          )
      (vterm)))
```
In case you care, I'm using
```
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.15.12, Xaw scroll bars) of 2023-02-09
```
and
```
.emacs.d/elpa/28.2/janelpa/vterm-20210908.640
```
