### ISSUE TITLE
share my vterm-toggle package

### ISSUE THREAD

**Issue by jixiuf** [akermu/emacs-libvterm#71]
Toggle to and from the vterm buffer 
 https://github.com/jixiuf/vterm-toggle
```
(global-set-key [f2] 'vterm-toggle)
(global-set-key [C-f2] 'vterm-toggle-cd)
```
 Provides the command `vterm-toggle` which toggles between the
 vterm buffer and whatever buffer you are editing.

 This is done in an "intelligent" way.  Features are:
 1. Starts a vterm if none is existent.
 2. Minimum distortion of your window configuration.
 3. When done in the vterm-buffer you are returned to the same window
    configuration you had before you toggled to the shell.
 4. If you desire, you automagically get a `cd` command in the shell to the
   directory where your current buffers file exists(**even in a ssh session**); just call
   `vterm-toggle-cd` instead of `vterm-toggle`.

**Comment by suonlight** [comment]
Actually, I have created https://github.com/suonlight/multi-libvterm. It is similar to `multi-term`.

**Comment by jixiuf** [comment]
https://github.com/manateelazycat/awesome-tab

**Comment by QiangF** [comment]
@jixiuf Maybe you should let vterm-toggle-cd only toggles to a dedicated scratch term, eg. make a local variable scratch-vterm, and toggle or create a vterm with the variable set to true. Just in case you have multiple terms active for different purposes.

**Comment by jixiuf** [comment]
@QiangF  I   removed ">" from vterm-toggle-prompt-regexp ,it should not toggle to a buffer with python interpreter .
and I will trying to add an option   `vterm-toggle-use-dedicated-buffer`  later

**Comment by QiangF** [comment]
@jixiuf I set vterm-toggle-use-dedicated-buffer t just when I want to use a scratch buffer.

        (defun my-vterm-toggle-cd ()
          (interactive)
          (let ((vterm-toggle-use-dedicated-buffer t))
                (vterm-toggle-cd)))

There is still a problem, once in the dedicated vterm, I can't switch away with vterm-toggle-forward or vterm-toggle-backward.

**Comment by QiangF** [comment]
Sorry for the noise, the other vterm buffers are created before loading vterm-toggle.

**Comment by QiangF** [comment]
The vterm buffer has to be killed, use exit will cause an error.

**Comment by jixiuf** [comment]
@QiangF  restart your emacs

**Comment by akermu** [comment]
I mention both your packages now in the README.
