### ISSUE TITLE
ls --color=auto does not show colors in vterm

### ISSUE THREAD

**Issue by rennsax** [akermu/emacs-libvterm#717]
Hello, I have a simple question: why `ls --color=auto` show no colors in vterm, while `ls --color` does render colors? It happens for BSD (macOS version) ls but not for GNU coreutils ls.

<img width="206" alt="image" src="https://github.com/akermu/emacs-libvterm/assets/93167100/0e7441c7-4a46-41bc-adb3-b444c44071c0">

**Comment by rennsax** [comment]
I fix this issue by appending

```sh
[ -n "$INSIDE_EMACS" ] && export COLORTERM="truecolor"
```

to my shell init file.

**Comment by mgeisler** [comment]
> I fix this issue by appending
> 
> [ -n "$INSIDE_EMACS" ] && export COLORTERM="truecolor"
> to my shell init file.

I ran into the same problem and found that I could solve it from Emacs itself:

```elisp
  (add-to-list 'vterm-environment "COLORTERM=truecolor")
```

was all I needed.
