### ISSUE TITLE
`vterm-send-return` just highlights the command i typed and nothing happens

### ISSUE THREAD

**Issue by Seme4eg** [akermu/emacs-libvterm#727]
No errors, reported. I am using emacs 30.0.50. Doom config, unpinned vterm package. Typing `ls`, `exit` or literally any other command and pressing 'enter' just highlights the command and nothing happens. Vterm compiled successfully with no reported errors.

**Comment by Sbozzolo** [comment]
Is this something you can reproduce in vanilla Emacs?

**Comment by Seme4eg** [comment]
Yes

**Comment by Seme4eg** [comment]
turned out to be #371 case, i had 

```
bindkey '^K' history-substring-search-up
bindkey '^J' history-substring-search-down
```

in my zsh config, needed to rebind it to ctrl+n ctrl+p
