### ISSUE TITLE
Howto set colors?

### ISSUE THREAD

**Issue by mklemm2** [akermu/emacs-libvterm#73]
Hi,

I'm monitoring this project for a while and my latest tests indicate that I can finally move away from iTerm2 and fully into Emacs ;-)

There are a couple of cosmetic issues, though. One of them is that I have no idea howto set my terminal's colors, properly. The Readme says to customize faces like "vterm-color-default-bg", but none of them is defined and doing so myself by evaluating

```
(defface vterm-color-default-bg
  '((default
     )
    (((class color) (min-colors 88))
     :background "black"))
  "vterm background color."
  :group 'vterm-faces
  :group 'basic-faces)
```

doesn't do anything, apparently.

Could you please provide some hints on howto configure this?

Best regards and thank you for this great project!
Marcus

**Comment by jixiuf** [comment]
```

 (setq ansi-color-names-vector
   ["#202020" "#ff8272" "#b4fa72" "#fefdc2" "#a5d5fe" "#ff8ffd" "#d0d1fe" "#f1f1f1"])

```

**Comment by mklemm2** [comment]
Perfect, thank you!
