### ISSUE TITLE
Allow preserving scroll position when new text is emitted to the terminal and when expanding the minibuffer

### ISSUE THREAD

**Issue by evertedsphere** [akermu/emacs-libvterm#730]
If a process is producing text and a vterm window is scrolled to view the scrollback, any output from the process forces the scroll position to be reset to the bottom, which is inconsistent with the behaviour of most terminal emulators.

In a similar way, if a vertical completion window (such as is provided by vertico for `M-x`) is opened temporarily, the scroll position is unexpectedly reset.

Could an option be added to disable this behaviour?

**Comment by Sbozzolo** [comment]
Please, see #397

Closed as duplicated of #397
