### ISSUE TITLE
Support derived modes in vterm.el

### ISSUE THREAD

**Issue by peterpazien** [akermu/emacs-libvterm#732]
I've created some modes derived from vterm, and it would be really helpful if vterm.el changed its checking from:
```
(equal major-mode 'vterm-mode)
```
to:
```
(or (equal major-mode 'vterm-mode)
      (derived-mode-p 'vterm-mode))
```

The changes are straight-forward. I have a patch to do that if it would be helpful.

**Comment by Sbozzolo** [comment]
Yes, I don't see any harm in doing that. I'll merge the pull request if you open one.

Thank you!
