### ISSUE TITLE
Sourcing of .bash_profile (or .profile)

### ISSUE THREAD

**Issue by arichiardi** [akermu/emacs-libvterm#738]
Hi all, writing this because I am in a small conundrum.

My emacs configuration is using `exec-path-from-shell` and following the advice from its [README.md](https://github.com/purcell/exec-path-from-shell):

> To be safe, exec-path-from-shell starts an interactive (and login) shell by default, but this can be much slower than necessary. Interactive shells often have fancy features enabled that are only helpful when one interacts directly with the shell, and this can frequently cause startup time to exceed 750ms. This can be avoided:

>    Follow best practice by setting your environment variables so that they are available to both interactive and non-interactive shells. In practical terms, for most people this means setting them in ~/.profile, ~/.bash_profile, ~/.zshenv instead of ~/.bashrc and ~/.zshrc.

In practice, that means my `PATH` has been set in `.bash_profile`.

However, I see now that this package does not source that file and I was wondering what would the best way for me to move forward (obviously without start a war between file-clans, just want to understand what is the best approach here).

Thank you in advance for any advance you'll be willing to give and for the project itself - it is very fast!!!

**Comment by arichiardi** [comment]
I found this comment [on reddit](https://www.reddit.com/r/emacs/comments/ik54s5/comment/g3ixk8p/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) that also makes sense there:

> Shells that you would run via emacs, and the vterm, are "interactive", but not "login" shells. 

So it does make sense to only source `.bashrc`. Still unsure where my `PATH` should be as there is a mismatch between recommendations at this point from the two packages.

I might end up just adding the hook in the above reddit thread.

**Comment by arichiardi** [comment]
For posterity, this is my workaround

```elisp
(use-package vterm
  :commands (vterm-send-string vterm-send-return)
  :hook (vterm-mode . (lambda ()
                        (vterm-send-string "source ~/.profile" t)
                        (vterm-send-return))))
```

**Comment by Sbozzolo** [comment]
Your shell can also identify if it being run from vterm or not. You can use the `INSIDE_EMACS` variable to trigger different behaviors from vterm and other cases.

**Comment by arichiardi** [comment]
I am aware @Sbozzolo I just thought it would look backwards to have an `if` in `.bashrc` to source `.profile` - I guess you could do it both ways - another way that might work is to run `exec-path-from-shell` before starting vterm? Not sure.
