### ISSUE TITLE
vterm cancel copy-mode

### ISSUE THREAD

**Issue by jvillasante** [akermu/emacs-libvterm#740]
Is it possible to bind keys as in `tmux`, for example
```
# copy region, stay in copy mode
bind -Tcopy-mode M-w send -X copy-pipe

# get out of copy mode without actually copying anything
bind -Tcopy-mode Enter send -X cancel
```

In particular, having a `vterm-copy-mode-cancel` that does not saves anything to the kill ring?

I can only find `vterm-copy-mode-done` which will save the current line or the region to the kill ring.

**Comment by jvillasante** [comment]
Never mind, the solution is very simple:

```
(define-key vterm-copy-mode-map (kbd "<return>")
                '(lambda () (interactive) (vterm-copy-mode -1)))
```

**Comment by Anyborr** [comment]
Not sure how this is an issue for you. When I activate the vterm copy mode (C-c C-t) and then deactivate it using the same bind (C-c C-t) nothing gets saved to the kill-ring. So rebinding this key to whatever you want should preserve this behavior.
