### ISSUE TITLE
Browsh support -- cannot trigger navigatation with Enter

### ISSUE THREAD

**Issue by sandinmyjoints** [akermu/emacs-libvterm#77]
https://www.brow.sh/ sort of works in vterm in Emacs! Currently, on macOS emacs-mac port 26.1.92, it loads the default homepage (which is https://www.brow.sh/), and I can type a new url to visit into the url bar, but I cannot get it to navigate to the new url by hitting Enter (or any other way that I can think of). I wonder if this is related to https://github.com/akermu/emacs-libvterm/issues/67

**Comment by sandinmyjoints** [comment]
Tried the key bindings suggested in #67 but no dice

**Comment by adrianparvino** [comment]
Hi! This doesn't seem to be fixed. RET seems to be translated to C-j when every other terminal emulator uses C-m.

**Comment by adrianparvino** [comment]
I think the best method is to revert #77, add ICANON checking on Emacs, C-m/C-j handling on Elisp. That means adding /get-icanon. Let me hack one up real quick.

**Comment by adrianparvino** [comment]
I did *just that* but ICRNL is not being reflected by libvterm, even though stty detects it properly, *and keeps state*. Weird.

**Comment by akermu** [comment]
Could you open a new issue?
