### ISSUE TITLE
build fails: no rule to make target

### ISSUE THREAD

**Issue by leotaku** [akermu/emacs-libvterm#78]
When I try to build emacs-libvterm the way the repository README suggests, make fails with the following error message:

```
[  8%] Performing update step for 'libvterm'
[ 16%] No configure step for 'libvterm'
[ 25%] Performing build step for 'libvterm'
[ 33%] No install step for 'libvterm'
[ 41%] Completed 'libvterm'
[ 66%] Built target libvterm
make[2]: *** No rule to make target 'libvterm-prefix/src/libvterm/.libs/libvterm.a', needed by '../vterm-module.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/vterm-module.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

I don't really know my way arround cmake or even make, so please excuse me if this is an obvious problem.

**Comment by vizs** [comment]
I'm having the same issue. To add some more info, I'm running Alpine and my C compiler is clang. I don't think this will help but I do have libvterm and libvterm-dev installed.

**Comment by akirak** [comment]
I experience the same issue. I tried to build the package using straight.el and [made some changes](https://github.com/akirak/emacs-libvterm/commits/straight-nix) but encounter the same error. Perhaps the makefile need some changes, but I have no idea how.

**Comment by akermu** [comment]
Does `ac68d6b` fix your issue? In any case, can you post the exact command line you invoke for the build? And is there something in your build folder `libvterm-prefix/src/libvterm/.libs`?

**Comment by vizs** [comment]
It builds now but the problem comes when I try to run `vterm`. 
I get an error saying `Cannot open load file: No such file or directory, vterm-module`. I tried the melpa package and compiled it on my own. Nothing's different.

The commands I ran:
```
$ mkdir build
$ cd build
$ cmake ..
$ make
```

Then added the following to my emacs config.
```
(add-to-list 'load-path (concat user-emacs-directory "/emacs-libvterm"))
(require 'vterm)
```
where the `emacs-libvterm` dir is in `~/etc/emacs.d/emacs-libvterm` (`~/etc/emacs.d` is my user-emacs-directory). FWIW I do have a `vterm-module.so` file in that path. 

And yes I do have the libraries in the directory you mentioned.

```
$ pwd
/home/viz/etc/emacs.d/emacs-libvterm/build/libvterm-prefix/src/libvterm/.libs
$ ls
libvterm.a  libvterm.la@  libvterm.lai  libvterm.so@  libvterm.so.0@  libvterm.so.0.0.0*
```

**Comment by akermu** [comment]
@vizs Has your emacs enabled support for modules? You can verify that by checking if the variable `system-configuration-features` contains the string `MODULES.

**Comment by vizs** [comment]
Good catch. My emacs build didn't have support for modules. Now it works like a charm :)

**Comment by akermu** [comment]
Perfect :)
