### ISSUE TITLE
A way to disable bold fonts

### ISSUE THREAD

**Issue by guskovd** [akermu/emacs-libvterm#79]
I usually use this method:
```elisp
(mapc
 (lambda (face)
        (when (eq (face-attribute face :weight) 'bold)
          (set-face-attribute face nil :weight 'normal)))
 (face-list))
```
But in the vterm buffer, this approach does not work.
As a workaround, I disabled bold fonts in C code. I want to understand how to do this through elisp

**Comment by akermu** [comment]
It's currently not doable from elisp. Would a `defvar` to disable bold fonts in vterm an acceptable solution for you?

**Comment by vizs** [comment]
@akermu can we have a update on this? I would like to disable bold fonts from elisp too.
