### ISSUE TITLE
Seeing ^? when pressing backspace.

### ISSUE THREAD

**Issue by jojojames** [akermu/emacs-libvterm#89]
Repro: M-x vterm -> $ vim -> Type in vim -> press backspace -> ^? ^? will show up instead.

```
/ $ stty -a
speed 9600 baud; 44 rows; 88 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
        -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
        -extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
        -ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
        -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
        eol2 = <undef>; erase = <undef>; intr = ^C; kill = <undef>;
        lnext = ^V; min = 1; quit = ^\; reprint = ^R; start = ^Q;
        status = ^T; stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

```
erase = <undef>
```

```
/ $ stty erase ^? # (obtained through C-v BACKSPACE || Press C-v then press backspace)
```

Go into vim again, now backspaces are entered correctly.

Not sure if this is something vterm can set itself?

**Comment by epaulson10** [comment]
@jojojames , I also have this issue. I am guessing you have a Mac? Both term.el and emacs-libvterm rely on `stty sane` to make sure the terminal is setup correctly. I just did a test and it seems that calling sane doesn't set the ERASE control character to something meaningful on my Mac, but it does set it to something meaningful on a Linux server I tested it on.

**Comment by jojojames** [comment]
Yup, mac.
