### ISSUE TITLE
vterm.el won't byte compile when install via package.el 

### ISSUE THREAD

**Issue by xuchunyang** [akermu/emacs-libvterm#92]
`vterm.el` won't get byte compiled when user installs the package. User should get this error message:

> vterm.el:77:1:Error: Cannot open load file: No such file or directory, vterm-module

because `vterm.el` contains this line in the top level:

    (require 'vterm-module)

Users won't be able to resolve the issue by themself because package.el downloads and byte compiles the package at the same time, and users won't get a chance to compile `vterm-module` *before* package.el byte compiles `vterm.el`.

Something like this maybe work (?)

```elisp
(eval-when-compile
  (unless (require 'vterm-module nil t)
    (vterm-module-compile)))

(require 'vterm-module)
```

Though I think it's better to ask Emacs maintainers how to distribute package with dynamic module through ELPA.

**Comment by jixiuf** [comment]
#86

**Comment by akermu** [comment]
#86 is merged, so the issue should be resolved.
