### ISSUE TITLE
lexical-binding and boundp

### ISSUE THREAD

**Issue by xuchunyang** [akermu/emacs-libvterm#94]
README and `Commentary` section contains

```elisp
(let (vterm-install)
  (require 'vterm))
```

`vterm.el` contains

```elisp
(when (boundp 'vterm-install)
  (vterm-module-compile))
```

The issue is if user enables the lexical binding in the init file (including me), it won't work, `(boundp 'vterm-install)` still returns nil if you let-bind the variable.

**Comment by jixiuf** [comment]
this is not necessary after #86 is merged .

**Comment by akermu** [comment]
Since #86 is merged, I close this as fixed.
