### ISSUE TITLE
Is binding to super possible?

### ISSUE THREAD

**Issue by cwhatley** [akermu/emacs-libvterm#96]
Is there a known way to do this with the current code or is there work to be done in this area?

I've tried adding keys to vterm-keymap-exceptions, adding to vterm-mode-map, deleting from vterm-mode-map.

In particular I use simpleclip for mac pasteboard integration and want to get `S-v`working in vterm with an equivalent that uses vterm-send-string to deliver the clipboard contents to the terminal.

When I'm in the vterm buffer and do 'C-h v' for 'S-v', it shows simpleclip-paste, but when I type 'S-v' simpleclip-paste is never called and I get `apply: Buffer is read only: #<buffer vterm>` in `*Messages*`. Super-v is definitely defined in the vterm-mode-map as shown by `which-key-show-full-keymap`

A binding of Control-Super-v to my command works fine.

**Comment by jixiuf** [comment]
```
;;;###autoload
(defun simpleclip-paste ()
  "Paste the contents of the system clipboard at the point."
  (interactive ) ;; remove "*" In addition, if the string begins with ‘*’, an error is signaled if the buffer is read-only.

  (let ((str-val (simpleclip-get-contents)))
    (unless str-val
      (error "No content to paste"))
    (cond
      ((derived-mode-p 'term-mode)
       (term-send-raw-string str-val))
      ((derived-mode-p 'vterm-mode)  ;; support vterm-mode
       (vterm-send-string str-val t))
      (t
       (when (use-region-p)
         (delete-region (region-beginning) (region-end)))
       (push-mark (point) t)
       (insert-for-yank str-val)))
    (when (and (not (minibufferp))
               (not simpleclip-less-feedback)
               (simpleclip-called-interactively-p 'interactive))
      (message "pasted from clipboard"))))
```

**Comment by cwhatley** [comment]
My problem was actually not how to make simpleclip-paste send chars to vterm. I have an advice around it that does just fine if called with M-x simpleclip-paste. My problem was that I was unable to bind anything to Super-v in vterm.

Simpleclip binds S-v, S-<insertchar>, and S-<insert> to simpleclip paste. For whatever reason, if I prevent simpleclip from binding S-<insert> and S-<insertchar> to simpleclip-paste and only bind "S-v", then simpleclip-paste is properly invoked in vterm mode.
