### ISSUE TITLE
Auto ssh with tramp?

### ISSUE THREAD

**Issue by N214** [akermu/emacs-libvterm#97]
I have a small function that directly ssh in my server instead using C-x C-f /ssh then open a terminal, but somehow I can't make it work with vterm, it works with shell tough... ? 

```
(defun ssh()
    (interactive)
    (let ((default-directory "/ssh:name@domain:"))
      (vterm)))
```

**Comment by jixiuf** [comment]
https://github.com/jixiuf/vterm-toggle
try my vterm-toggle

**Comment by N214** [comment]
Thanks, that's what I needed !

**Comment by Sbozzolo** [comment]
I am also interested in this function, but I don't see how vterm-toggle provides a solution. 
I would like to bind a key to open a terminal in a specified remote location.

**Comment by jixiuf** [comment]
```
(defun ssh()
    (interactive)
    (let ((default-directory "/ssh:root@host:~"))
      (vterm-toggle-cd)))
```

**Comment by Sbozzolo** [comment]
I see, thanks!

**Comment by jinnovation** [comment]
I don't really think "use this other package" is a solution to this issue. The behavior @N214 describes seems reasonable to expect of the native vterm package.

@akermu: Thoughts on re-opening this issue for a native solution?

**Comment by Sbozzolo** [comment]
Something like this should work:
```emacs-lisp
(defun vterm-ssh (host)
  (vterm)
  (vterm-send-string (concat "ssh " host "\n")))

(defun vterm-ssh-office ()
    (interactive)
    (vterm-ssh "office"))
```
